### PR TITLE
GCS: Branding update logos

### PR DESCRIPTION
**Pull request by VArcht**
First go at updating the GCS with dRonin logos. Will need to fine tune
things goin forward.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/165)

### CODE REVIEW

**Comment by VArcht** [comment]
Oh, I'll clean out the reamaining tau logos in a subsequent PR

**Comment by tracernz** [comment]
Unfortunately we're back to this again. :-( Can you fix them please?
screenshot from 2015-12-06 21 30 23

**Comment by tracernz** [comment]
Also now get this:
```
[Warning] QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[Warning] QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[Warning] QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[Warning] QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[Warning] QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[Warning] QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
[Warning] QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES"
```

**Comment by VArcht** [comment]
sRGB profile I can fix (have fixed)

Will have to look into "_GTK_LOAD_ICONTHEMES", any idea what that is?

**Comment by tracernz** [comment]
No, sorry, I'll see what I can find out.

**Pull request merged**
