### PR TITLE
WIP WIP WIP: Downsamplin': WIP WIP WIP

### PR DESCRIPTION
**Pull request by mlyle**
Rescue @trex4git's TL PR...

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/393)

### CODE REVIEW

**Comment by fujin** [comment]
Yay. I was going to reopen this myself! Glad you recovered it.

**Comment by Trex4Git** [comment]
Nice ;)

I was busy with work and family stuff, and had almost no time for this hobby.

But thought about setting up a dronin build environment and start working on this again on the next weekend.

Is there a minimal setup that i can do when I have already a running taulabs build environment on linux ?

**Comment by mlyle** [comment]
@Trex4Git -- you might be able to get away with just cloning us and symlinking the tools directory from the taulabs tree.

**Comment by dustin** [comment]
You don't even need to clone -- I used the same tree for changes to both
projects.



$ git remote -v
brain https://github.com/BrainFPV/TauLabs.git (fetch)
brain git@github.com:BrainFPV/TauLabs.git (push)
dronin git@github.com:d-ronin/dronin.git (push)
dronin https://github.com/d-ronin/dronin.git (fetch)
fujin git://github.com/fujin/dronin.git (push)
fujin git://github.com/fujin/dronin.git (fetch)
hshred git://github.com/mluessi/dronin.git (fetch)
hshred git://github.com/mluessi/dronin.git (push)
icee https://github.com/mlyle/taulabs (fetch)
icee git@github.com:mlyle/taulabs (push)
mine git@github.com:dustin/dronin.git (push)
mine https://github.com/dustin/dronin.git (fetch)
mytl git@github.com:dustin/TauLabs.git (push)
mytl https://github.com/dustin/TauLabs.git (fetch)
tl git://github.com/TauLabs/TauLabs.git (push)
tl git://github.com/TauLabs/TauLabs.git (fetch)

tracernz git@github.com:tracernz/TauLabs.git (push)

tracernz https://github.com/tracernz/TauLabs.git (fetch)

**Comment by fujin** [comment]
@Trex4Git you'll probably have to update Qt to 5.5.0 (iirc?) but otherwise just copying or hard/symlinking the tools directory ought do it.

**Comment by mlyle** [comment]
Superseded #713

**Pull request closed without merging**
