### PR TITLE
gcs: various cleanup commits from TL

### PR DESCRIPTION
**Pull request by mlyle**
[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/348)

### CODE REVIEW

**Comment by mlyle** [comment]
:lgtm: 

---

Reviewed 130 of 130 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/348#-:-K6PVWfN1Vj7HnqYHaJP:980077423)*

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mluessi** [comment]
Tested on Linux, seems fine.

**Comment by mlyle** [comment]
Can it merge then, please?

**Pull request merged**
