### PR TITLE
upgrader: don't try to upgrade naze or pipx

### PR DESCRIPTION
**Pull request by mlyle**
connects to #821

---

This change is [Reviewable](https://reviewable.io/reviews/d-ronin/dronin/834)

### CODE REVIEW

**Comment by mlyle** [comment]
tested by @droidicus -- not regressed, at least.

**Comment by dustin** [comment]
I ran into this earlier.  Caused much confusion.

**Comment by mlyle** [comment]
Worked for me

**Comment by mluessi** [comment]
Code looks good and test successful, merging.

**Pull request merged**
