### PR TITLE
androidgcs: branding, phase 1

### PR DESCRIPTION
**Pull request by mlyle**
Mostly package names, etc.

Confirmed that it starts up.

Need new icons and additional verification, but this seems like a good basis for an initial PR.

Connects to #705

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/715)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
build artifacts please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
Seems no more broken than before this PR, merging on that basis for further improvement in subsequent PRs before we eventually ship it.

**Pull request merged**
