### PR TITLE
naze32: reorder pios_servo_init before rcvrport setup

### LINKED ISSUE #936: PPM from D4R-ii does not work on Naze32Rev6
- Seen in version (release version or githash): tanto
- On flight controller (if applicable): naze32R6

Issue details:
Unknown cause.  Setting to 'PWM' sees the Chan1 toggling... so there's a signal there.  And the driver appears to be running.  But something is not right.

### PR DESCRIPTION
**Pull request by mlyle**
Necessary for PPM to work.

fixes #936

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Confirmed to work on developer-build on d4rii + nazer5 clone.

**Comment by mlyle** [comment]
Confirmed to work on developer-build on d4rii + nazer6

**Comment by fujin** [comment]
confirmed no s.bus regression on rxport/serial for nazer6:
image

**Comment by tracernz** [comment]
Not clear why this is necessary. Merging based on positive reports but I'd like to look further.

**Pull request merged**
