### PR TITLE
Improvements to GPS widget in GCS

### LINKED ISSUE #1698: Strange size of textbox on System tab
* Seen in version (release version or githash): a08a62cd

Issue details:
It seems to be overlapping some text?

image

### PR DESCRIPTION
**Pull request by mlyle**
1. Remove the message box part of the widget which is no longer used (would show NMEA sentences from a direct-connected GPS).
2. Improve the spacing and size of subwidgets-- make the graphical elements bigger.  Made a slightly bigger and better world map pixmap (which happens to be a smaller file).
3. Make the SNR bar graph widget useful.  Only show the first 18 satellites so that it is possible to read captions and see the bars-- if you have more than 18 satellites tracked you probably don't care about the last few lines :P
4. Adjust scaling of the data from flight.  The GPS widget assumes a opaque "1-99" SNR value which is not what UBX GPSes deliver; adjust our value so it's a bit more like NMEA.

Fixes #1698

### CODE REVIEW

**Comment by mlyle** [comment]
image

**Comment by mlyle** [comment]
Couldn't resist making another change--color coding constellations.

image

Yellow GPS, Red "Other" (Commie GLONASS satellites but also Beidou/Galileo in the future), Orange-y SBAS/differential

**Comment by mlyle** [comment]
OK I am done tweaking this for reals :P

image

**Comment by mlyle** [comment]
image

OK that's it for real.  I will stop lying.

**Review by tracernz — APPROVED** [review]
Very nice. :grinning:

**Pull request merged**
