### PR TITLE
python: telemetry: change lock model

### PR DESCRIPTION
**Pull request by mlyle**
I believe this was incorrect before; it attempted to use with:
but that didn't really fit into the generator model well.  Now
we explicitly weave acquires and releases in.

I will study this a little more, but this is necessary (but not
sufficient) to run dronin-api in pyjs.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/773)

### CODE REVIEW

**Comment by mlyle** [comment]
Confirmed, tested well over serial and over tcp and to logfiles.

**Comment by mlyle** [comment]
Read diff, it's sane (and was not sane before).

**Comment by tracernz** [comment]
Looks sane. Tested with get_config.py, worked okay. :lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/773#-:-KCOqWvo70SnCARKzI8O:-545342869)_

**Comment by mluessi** [comment]
Definitely looks more sane than before.

**Pull request merged**
