### PR TITLE
brainre1: enable protocols that were skipped

### PR DESCRIPTION
**Pull request by mlyle**
openlog, storm32bgc

### CODE REVIEW

**Comment by mlyle** [comment]
Was tested by @glowtape on IRC and found to function. (for the openlog one)

**Comment by fujin** [comment]
lgtm :+1:, is there a way to make these uhh.. less-optional so that they aren't skipped again in the future? some kind of compile-time assertion that they are available? It'd be nice to say a module should be running on all f1/f3/f4 barring some exclusions then be able to check against that (especially automatically.)

**Comment by mlyle** [comment]
I think the important thing is when a new target comes in, that the whole range of next since it was forked should have a similar target looked at for change as part of the review process.

**Comment by tracernz** [comment]
Basically, it's due to lazy rebasing :-P.

**Comment by mlyle** [comment]
Hmm.  It doesn't require a rebase to happen-- just for changes to be made across other targets that don't make their way to an out-of-tree one.

**Comment by mluessi** [comment]
Thanks for the fix and sorry for not adding them in the first place ;)

**Comment by tracernz** [comment]
> Hmm. It doesn't require a rebase to happen-- just for changes to be made across other targets that don't make their way to an out-of-tree one.

Hmm, I would always rebase a new target against next to make sure it's not broken before opening a PR. :stuck_out_tongue:

**Comment by mlyle** [comment]
Yes, but rebase or not, changes to other targets adding new features do not trigger a conflict or other notification.  It takes manual review to catch this (or some kind of compile-time assert about whether the feature has been considered for the target).

**Pull request merged**
