### PR TITLE
gcs: try to do meaningful things with cwd on startup

### LINKED ISSUE #684: GCS: OSX Default file location is unwritable.
File -> Export UAV Settings tries to put it in Machintosh HD, which is unwritable. Should put it somewhere better.

Also Tools -> Download Log.

### PR DESCRIPTION
**Pull request by mlyle**
Another attempt.  Fixes #684.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/693)

### CODE REVIEW

**Comment by mlyle** [comment]
Have not even confirmed this compiles yet.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Tried this out.  It works nicely-- if run from the command line on OSX, uses the actual CWD; else uses home.

**Comment by dustin** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/693#-:-KBfOIZ0Nq3lvdOh_-6H:980077423)_

**Pull request merged**
