### PR TITLE
Revo/Naze: New board graphics for uploader

### PR DESCRIPTION
**Pull request by tracernz**
Also turned on smooth pixel transform when resizing the board pics, before/after:
screenshot from 2015-11-04 18 44 32screenshot from 2015-11-04 18 43 10
[Altium PcbDoc](https://github.com/d-ronin/dRonin/blob/next/flight/targets/revomini/hw/Revolution.PcbDoc) used for the Revo image.
[Diptrace file](https://github.com/d-ronin/dRonin/blob/next/flight/targets/naze32/hw/OpenNaze.dip) with some additional 3D models used for the OpenNaze image.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/152)

### CODE REVIEW

**Comment by tracernz** [comment]
Also kills a null pixmap warning when using the revo since it didn't have a pic before.

**Comment by mluessi** [comment]
LGTM

**Comment by DTFUHF** [comment]
Are there any pics of actual naze? Now that closed source targets are allowed unabashedly.

**Comment by tracernz** [comment]
@DTFUHF: No source files available, so difficult to get some, and the original author isn't exactly co-operative on the matter so unlikely that we can use his artwork. We could use another photo but my feeling is that they always look worse than the renders.

**Comment by tracernz** [comment]
We could go to the trouble of trying the recreate a 3D model of the Naze32 which would be a matter of just laying the components on the top layer without any routing for this job but it's a bit of work.

**Pull request merged**
