### PR TITLE
openlrs: fix cast to not erroneously quantize bat data

### PR DESCRIPTION
**Pull request by mlyle**
As reported by [serge] on IRC.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/396)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by CrazyCoder** [comment]
I've tested it on Brushed Sparky 2 with DTF UHF Deluxe JR module for Taranis and current/voltage telemetry works correctly now. Thanks for the quick fix.

**Comment by mlyle** [comment]
@CrazyCoder Awesome-- thanks for testing!

**Comment by mlyle** [comment]
Cherry-pick'd in an RSSI change from taulabs/taulabs#2119

**Comment by mlyle** [comment]
(2119 has now merged @ Tau)

**Comment by mluessi** [comment]
Good catch!

**Pull request merged**
