### PR TITLE
pikoblx: initial target support

### PR DESCRIPTION
**Pull request by mlyle**
This is heavily WIP; so far just a transcribing of ports from Betaflight and hoping that things work.

TODO:

* [x] Figure out PPM support -- which "uart" does this replace etc, and impl on target
* [x] ~~Can RAM be found for the autotune averaging mode?  May defer this out of this PR~~
* [x] UI -- svg render defect?
* [x] I2C port configuration
* [x] ~~Support I2C periphs-- mag & baro~~
* [ ] Wiring diagram? :(

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
rebased on next, fixed up

jenkins, build artifacts please

**Comment by mlyle** [comment]
Rebased on top of #1655

**Comment by LitterBugs** [comment]
I have started testing.  So far the only issue I have found is DSM binding support does not work.  I have tried several Spektrum/LemonRX satellites and none of them go in to bind mode.  DSM works fine if the RX is prebound to the TX.

**Comment by mlyle** [comment]
Yes.  DSM bind will not work on this target since there is no USB-sense pin.  So we can't detect that there is no PC connected and boot faster with the current infrastructure.

**Comment by LitterBugs** [comment]
OK, no DSM bind support.

Output mapping maps correctly (4 motors using *flight layout).
Model moves correctly compared to board orientation.
ESC calibration works fine.  
Motors run fine using oneshot125.
Input wizard works fine with DSM.  RX failsafe detected.
Voltage monitoring works fine with 90.2 calibration factor.
Armed with props off.  Reacts to movements.

Tested using 03/22/2017 artifacts

**Comment by mlyle** [comment]
Nice!

**Comment by LitterBugs** [comment]
Got some crude initial flight testing and an autotune in VERY windy conditions.

[http://dronin.org/tunes#?key=ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAkKHywQoM](http://dronin.org/tunes#?key=ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAkKHywQoM)

Cheers!
LitterBug

**Comment by mlyle** [comment]
rebased, adjusted for #1655 and #1649

**Comment by mlyle** [comment]
Works fine after all the rebases etc

**Comment by LitterBugs** [comment]
Got another autotune in calm air.
[http://dronin.org/tunes#?key=ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAkP2yrggM](http://dronin.org/tunes#?key=ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAkP2yrggM)

Was flying Level and horizon modes LOS.  Handling really great.

**Comment by ohhorob** [comment]
I had a complete autotune in my garage.. http://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAkLCMjAsM

**Pull request merged**
