### PR TITLE
Matlab, add buffer length check

### PR DESCRIPTION
**Pull request by droidicus**
In case of truncated file, skip decoding of objects that have been truncated.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/651)

### CODE REVIEW

**Comment by droidicus** [comment]
Fixes #472

**Comment by mlyle** [comment]
You've tested thoroughly?

**Comment by droidicus** [comment]
I tested it with 5 log files that are truncated (fail with current next), and 10 more "normal" log files. Seems to be robust.

**Comment by mlyle** [comment]
GOod enough for me.

Changeset looks good; cleaned up somewhat.

**Pull request merged**
