### PR TITLE
packagework1 branch:  massive set of packaging changes in progress

### PR DESCRIPTION
**Pull request by mlyle**
incorporates @PTDreamer  work in taulabs/taulabs#2093.  

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/177)

### CODE REVIEW

**Comment by PTDreamer** [comment]
Thank you for this. This can also be improved by using the branding strings if/when the relevant PR gets merged.

**Comment by mlyle** [comment]
@PTDreamer Thank you for putting it together!

I'm going to hack on this for a couple days to get it into a better state--- may not get to all of branding strings, etc-- just going to focus on it working right.

**Comment by mlyle** [comment]
Rebased onto next after branding.

**Comment by mlyle** [comment]
This command sequence works on OSX to produce a package:

```
make -j8 all
make package_flight
make package_installer
```

**Comment by mlyle** [comment]
```
make -j8 all
make package_flight
make package_all_compress
```

Works on Linux.  Still some minor stuff with the package_installer on linux, for a subsequent PR.

**Comment by mlyle** [comment]
I got distracted by other stuff during the day... Will be going back into test with this tonight.

**Comment by mlyle** [comment]
mac:

```
make -j8 all
make package_flight
make package_all_compress
   (compressed zip is apparently OK)
rm -rf build/package-20151210-24dc5c39/
make package_installer
   (dmg is good)
```

linux:

```
make -j4 all
make package_flight
make package_all_compress
   (tar.xz appears good)
rm -rf build/package-20151210-24dc5c39
make package_installer
   (fails because of control file problems, subsequent PR)
```

windows:

```
GCS_BUILD_CONF=release make -j4 all
make package_flight
make package_installer
   (installer is good)
rm -rf build/package-20151210-24dc5c39-dirty/
make package_all_compress
   (works with system-installed info-zip)
```

TODO, subsequent PRs:

* Windows zip location / tools management
* Icons on OSX packaging, etc
* Linux deb packaging

**Comment by tracernz** [comment]
Reviewed 1 of 35 files at r1, 6 of 36 files at r2, 29 of 36 files at r3, 11 of 15 files at r4, 2 of 2 files at r5, 1 of 1 files at r7, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[make/templates/packageversioninfo.json, line 5 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59SFym1oQ4hVagBkDy:-K59SFym1oQ4hVagBkDz:908986580) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/make/templates/packageversioninfo.json#L5)):*
Should have a newline at the end.

---

*[make/tools.mk, line 441 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59SL0--E4_k3brneuR:-K59SL0--E4_k3brneuS:-1748965474) ([raw file](https://github.com/d-ronin/dronin/blob/2768c7a51630097c06cdfa927a46cfe3a24055ee/make/tools.mk#L441)):*
Ditching astyle should probably be a separate PR which is open for debate I think.

---

*[Makefile, line 172 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59SpxK1Cfh4UdcN3Z5:-K59SpxK1Cfh4UdcN3Z6:21936644) ([raw file](https://github.com/d-ronin/dronin/blob/2768c7a51630097c06cdfa927a46cfe3a24055ee/Makefile#L172)):*
Why remove the unbrick option?

---

*[package/linux/deb_common/changelog, line 3 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59UlfqXGUpfVem2NMj:-K59UlfqXGUpfVem2NMk:1695672370) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/deb_common/changelog#L3)):*
It would be nice if we could generate this automatically, or fetch it from somewhere like the github release api.

---

*[package/linux/deb_common/copyright, line 7 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59TCi7rnMzyG-ZIMNA:-K59TCi7rnMzyG-ZIMNB:-1781972106) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/deb_common/copyright#L7)):*
Fix branding in here..

---

*[package/linux/deb_common/manpage.1, line 21 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59TJ_1_S2UYFJuH1-V:-K59TJ_1_S2UYFJuH1-W:-2131883264) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/deb_common/manpage.1#L21)):*
branding

---

*[package/linux/dronin_menu.menu, line 6 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59TQe23Das4s8_nZQw:-K59TQe23Das4s8_nZQx:-2067239136) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/dronin_menu.menu#L6)):*
Branding

---

*[package/linux/dronin_menu.png, line 0 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59TYFM4RzaOql9ekEX:-K59TYFM4RzaOql9ekEY:1222251460) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/dronin_menu.png#L0)):*
Branding, should take this from ./branding if possible

---

*[package/linux/taulabs.png, line 0 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59TpOmbf9s-jaoKG8C:-K59TpOmbf9s-jaoKG8D:525601148) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/taulabs.png#L0)):*
Take from ./branding if possible.

---

*[package/Makefile, line 29 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59Ty4lyoy11ZQc24yU:-K59Ty4lyoy11ZQc24yV:130887964) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/Makefile#L29)):*
Can't use the existing code for this?

---

*[package/winx86/translations/languages.nsh, line 41 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59UMvN0HScPSILUKmW:-K59UMvN0HScPSILUKmX:-1360212331) ([raw file](https://github.com/d-ronin/dronin/blob/2768c7a51630097c06cdfa927a46cfe3a24055ee/package/winx86/translations/languages.nsh#L41)):*
Any reason to remove all these?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/177)*

**Comment by mlyle** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[make/templates/packageversioninfo.json, line 5 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59SFym1oQ4hVagBkDy:-K59X3SWLFBfxea9W40u:677588487) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/make/templates/packageversioninfo.json#L5)):*
done

---

*[make/tools.mk, line 441 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59SL0--E4_k3brneuR:-K59WoZTFCrkFCRN0HkV:-1932501508) ([raw file](https://github.com/d-ronin/dronin/blob/2768c7a51630097c06cdfa927a46cfe3a24055ee/make/tools.mk#L441)):*
OK.  You don't like uncrustify?  I think we shouldn't have two things.

---

*[Makefile, line 172 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59SpxK1Cfh4UdcN3Z5:-K59WZlAH73Vru3LEeH1:568149462) ([raw file](https://github.com/d-ronin/dronin/blob/2768c7a51630097c06cdfa927a46cfe3a24055ee/Makefile#L172)):*
I was told it didn't work-- also just a philosophy thing, I think it's a silly thing for the makefile to do (which requires special variables set and passed in).  I'd far rather provide a script if this is what we want.

---

*[package/linux/dronin_menu.menu, line 6 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59TQe23Das4s8_nZQw:-K59WNt8V7eWLb2AecEu:-228010448) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/dronin_menu.menu#L6)):*
In todo github comment for further issues to open on merging.

---

*[package/linux/taulabs.png, line 0 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59TpOmbf9s-jaoKG8C:-K59WHXbtGToCfw8ahhd:1756839695) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/taulabs.png#L0)):*
these came back from reverting package/linux --- pt says he has more work here, I have more work to do here.

---

*[package/Makefile, line 29 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59Ty4lyoy11ZQc24yU:-K59VoziH-QbTAV9D_oF:1717530253) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/Makefile#L29)):*
Inherited from PT.  I feel like it is OK but should get cut down with further work.  Main point is it works -- further cleanliness will be sought in a series of subsequent PRs.

---

*[package/winx86/translations/languages.nsh, line 41 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59UMvN0HScPSILUKmW:-K59VfygF5KQj8pqLKNd:-31699068) ([raw file](https://github.com/d-ronin/dronin/blob/2768c7a51630097c06cdfa927a46cfe3a24055ee/package/winx86/translations/languages.nsh#L41)):*
I killed the translated installers because the strings are out of date and bogus.  I figure if we want to I18N on the Windows installer we're best starting over.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/177)*

**Comment by mlyle** [comment]
Review status: 48 of 49 files reviewed at latest revision, 3 unresolved discussions.

---

*[package/linux/deb_common/changelog, line 3 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59UlfqXGUpfVem2NMj:-K59XJ-uB4fQhIujIURS:-774006928) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/deb_common/changelog#L3)):*
I agree

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/177)*

**Comment by tracernz** [comment]
Review status: 48 of 49 files reviewed at latest revision, 3 unresolved discussions.

---

*[package/linux/deb_common/changelog, line 3 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59UlfqXGUpfVem2NMj:-K59XuUxvY5jsn2rT7fz:1105585524) ([raw file](https://github.com/d-ronin/dronin/blob/9c1f12e350580a91fa4287ee5ddcd899b9179fde/package/linux/deb_common/changelog#L3)):*
Future PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/177)*

**Comment by mlyle** [comment]
Cherry-pick'd out remove astyle change

**Comment by tracernz** [comment]
Reviewed 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[make/tools.mk, line 441 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59SL0--E4_k3brneuR:-K59ZbcPTAXaJgzkuUv3:-2143867945) ([raw file](https://github.com/d-ronin/dronin/blob/2768c7a51630097c06cdfa927a46cfe3a24055ee/make/tools.mk#L441)):*
Yup, but should be up for discussion in a separate PR so everybody can have their say.

---

*[Makefile, line 172 \[r9\]](https://reviewable.io:443/reviews/d-ronin/dronin/177#-K59SpxK1Cfh4UdcN3Z5:-K59ZkmmrJuVKRBjUvcP:1656123595) ([raw file](https://github.com/d-ronin/dronin/blob/2768c7a51630097c06cdfa927a46cfe3a24055ee/Makefile#L172)):*
Well, I have something friendlier in the works but it's been on the back-burner lately. Can remove it if you really want.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/177)*

**Comment by tracernz** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/177#-:-K59eq59AA5r_J7Im9at:-1868698381)*

**Pull request merged**
