### PR TITLE
makefile: eliminate silliness

### PR DESCRIPTION
**Pull request by mlyle**
This is mostly here to play with PR building.  Jenkins isn't configured to do notification through github/doesn't have credentials yet.  But will it try to build?

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, add to whitelist

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, do test this please

**Comment by mlyle** [comment]
jenkins test this please

**Comment by mlyle** [comment]
jenkins test this please

**Comment by mlyle** [comment]
jenkins test this please

**Comment by tracernz** [comment]
See also shared/make_gui sandwich nonsense. Do we even want to keep the make gui? Does anybody use it or does it even work?

**Comment by mlyle** [comment]
jenkins, add to whitelist

**Pull request merged**
