### PR TITLE
GCS: Branding Logo Cleanup

### PR DESCRIPTION
**Pull request by VArcht**
Clean up app icon
Update Welcome Logo
Fix png color profile warnings
Add background for splash logo on dark backgrounds

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/175)

### CODE REVIEW

**Comment by tracernz** [comment]
Great! :-D

**Comment by VArcht** [comment]
@tracernz Still not sure what that icon issue is :/

**Comment by tracernz** [comment]
@VArcht Yeah, it's a bit weird, I'll have a look later and see if I can make some sense of it.

**Comment by VArcht** [comment]
sneak peak

screen_02

**Comment by tracernz** [comment]
The tray icon no longer works on Linux, it did before this PR.

**Comment by VArcht** [comment]
Maybe that's why the app icon was overwritten with a png?

**Comment by tracernz** [comment]
PNG should definitely work on Linux. Not sure about other OSes.

**Comment by jihlein** [comment]
On Windows 7, if I create a shortcut to the gcs, the shortcut has the Dronin icon. When I drag the shortcut to the desktop, it changes to the Taulabs icon.

**Pull request merged**
