### PR TITLE
flight: move to newlib-nano from newlib

### PR DESCRIPTION
**Pull request by mlyle**
On Sparky2, this saves 2588 bytes of flash and.. 968 (!) bytes of data
segment SRAM.

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
Great, didn't realise we weren't using nano. :blush:

**Comment by glowtape** [comment]
Stuck this in my flying branch, seems to work. No firmware crashes or any other odd stuff. (--edit: Seppuku.)

**Comment by mlyle** [comment]
@glowtape -- cool! thanks for the test

**Comment by tracernz** [comment]
I guess for completeness we should test this on a Cortex-M3 before merging too? That's actually just the PipX now though I guess...

**Comment by tracernz** [comment]
Test on a (manually bound re: pug's comment in #1602) PipX, all was well.

**Pull request merged**
