### PR TITLE
Ground: Fix crash reporting on OSX

### PR DESCRIPTION
**Pull request by mlyle**
Verified to make crash reporting work with latest changes.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/99)

### CODE REVIEW

**Comment by mlyle** [comment]
I am not able to make this work.

**Comment by mlyle** [comment]
Adjusted to catch additional signals that represent many/most crash scenarios (like the linux port).

**Comment by mlyle** [comment]
Confirmed to work when a SEGV is applied to process and on an invalid pointer reference.

**Comment by tracernz** [comment]
Awesome. ^_^

**Comment by tracernz** [comment]
Tested, merging. Great to get this sorted.

**Pull request merged**
