### PR TITLE
sparky2: bl: don't drive channels low on reset

### PR DESCRIPTION
**Pull request by mlyle**
Connects to #642

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/719)

### CODE REVIEW

**Comment by mlyle** [comment]
Jenkins, build artifacts please

**Comment by mlyle** [comment]
@thunderdan Hey, this may improve your issue.  You'll need a new bootloader.  Are you willing to try out a bootloader update I provide to see if it changes things?

**Comment by mlyle** [comment]
http://jar.lyle.org/~mlyle/bu_sparky2.tlfw

Procedure:  Rescue, flash this to board, "boot", wait for it to do its thing / stop blinking.

Then rescue, flash normal firmware to board.

Test IAP reset again to see if happier.

**Comment by tracernz** [comment]
Yeah, I think this is a good idea. Will put it on a scope at some point to see what it does before/after.

**Comment by thunderdan** [comment]
Hi.  I gave this a shot tonight with the two batteries I have for my plane.  With one battery, the start-up completes and the servos are centered.  With the other battery, the problem remains.  Start-up fails and it goes into a loop with the servos driven to their extreme position (which i think is the zero position).  The servos always move after attaching power with either battery.

Thanks @mlyle for the boot loader build.  This project is fun.

**Comment by pug398** [comment]
@thunderdan Sounds like the first battery cannot source enough current to actuate all the servos and causes a brownout. Do the servos start from a random position and jump to center or are they centered and jump to an extreme when first powered? A servo's zero position is in the middle and is driven there by a 1500us pulse. 1000 or 2000 would be at each extreme. In your dealing with this problem did you try latest TL next which sets pwm default to off instead of 1000us?

**Comment by thunderdan** [comment]
Yes I agree that is the situation.

Other suggestions to fix the issue were to add capacitance near the Sparky2 or a separate BECs for flight controller and servos.

I'll build the latest Tau Labs next branch tonight and give it a try.

It's great to see such an active community after open pilot.

-- Dan Morgan --

**Comment by pug398** [comment]
The TL is just a test. Flash firmware and then in partition browser>settings right click and erase settings, then boot. Power up and note servos. Then setup vehicle type. Power up and note servos. Continue setup until you encounter issue again or you may get same issue immediately. Just gathering more info.

**Comment by thunderdan** [comment]
Build is TL next from 20160302

Updated bu_sparky2.tlfw, fw_sparky2.tlfw, and erased settings

applied battery power with usb power still attached
- servos moved but they aren't at their extremes and board completed power-up
  disconnect usb and applied battery power (bat1)
- servos moved to extremes and board completed power-up
  usb still disconnected, applied battery power (bat2)
- servos moved to extremes and board completed power-up

Configured FC
applied battery power with usb power still attached
- servos moved from extremes to center and board completed power-up
- it was quick so power-up may complete then be driving the servos to correct position
  disconnect usb and applied battery power (bat1)
- servo move a little then move back to center
  usb still disconnected, applied battery power (bat2)
- power-up reset loop with servos bouncing

Thoughts:  In my fixed wing setup with 3 cheap servos powered through sparky2 the FC is sensitive to power dips.  I need to change my wiring to seperate power for FC and servos or add capacitance for FC.  Changes to BL and FW can't remove the pulse on the PWM lines that cause my servos to move during first power-up.

I have one other experience that really points to a power problem.  Check out this mid flight power-loss.  This is a very short flight where the battery should normally still have enough power to glide in.  Instead the FC resets.
https://youtu.be/Fh1Vij385bw

**Comment by pug398** [comment]
I think separating power for fc and servos is a good idea. After configuring board it looks like you got correct behavior with a good battery. With a configured board a small jump (depending on initial position) and then moving to center can be expected. dRonin should have the same response when configured. Make sure the configured min/max endpoints don't push the mechanical limits of the system.

**Comment by thunderdan** [comment]
I think this one can be closed too since #642 is closed.  The bootloader improvements were good and the final solution to my power brown-outs was adding more capacitance.   Thanks again for the help everyone.

**Comment by mlyle** [comment]
A decision needs to be made whether to merge this-- this is a PR that you tested to eliminate the power-up glitch.  It seems you and @pug398 like it, but @tracernz is probably waiting to scope it before he pushes the merge button.

**Pull request merged**
