### PR TITLE
sim: attempt to not require clock_gettime

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
Great. Ready to go with this? 😀

**Comment by mlyle** [comment]
Yes, I am.

Turns out Dustin and I were able to build because we're on 10.12, but because the OSX builder is on 10.11 it was not.

**Pull request merged**
