### PR TITLE
F3frsky - Restore operation under PIOS_HAL

### PR DESCRIPTION
**Pull request by jihlein**
Code builds correctly.  Have not tested it yet.  I can try running it on Sparky, Quanton, and AQ32, but most likely not until the weekend.

Figured we could at least start looking it over for the review.

### CODE REVIEW

**Comment by mlyle** [comment]
Fixes #46

**Comment by mlyle** [comment]
This is our week of livin' dangerously.  Merge now, test later. :>

Thanks for the fix.

**Comment by jihlein** [comment]
Confirmed patch works on Sparky with D4R-II on PPM, FrSky Sensor Hub selected on main port.  Don't have cables for flex port, but should be fine there too.

**Comment by jihlein** [comment]
Confirmed operation on Quanton with D4R-II on PPM, FrSky Sensor Hub on Uart4 with external inverter.

**Pull request merged**
