### PR TITLE
Flyingf3 - Move to PIOS_HAL

### PR DESCRIPTION
**Pull request by jihlein**
Implement PIOS_HAL on Flyingf3. Compiles clean, needs testing by someone with Flyingf3 FC board.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/414)

### CODE REVIEW

**Comment by mlyle** [comment]
I really appreciate all these.

It's going to take us a little bit to get to them (though, yay, we'll have a robust PR queue after we ship to work on).

We'll also have to be careful since they will conflict with your #403.

**Comment by mlyle** [comment]
_[flight/targets/flyingf3/fw/pios_board.c, line 367 [r1]](https://reviewable.io:443/reviews/d-ronin/dronin/414#-K8WsgnJ8FLxQPm-EmD2:-K8WsgnKBwJ8tSAfAkJL:-382021025) ([raw file](https://github.com/d-ronin/dronin/blob/3a53473482bf78a3f81a2f093dabacf842b5c4d9/flight/targets/flyingf3/fw/pios_board.c#L367)):_
Is this incorrect? e.g. this is supposed to trigger inverters.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/414)_

**Comment by mlyle** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[flight/targets/flyingf3/fw/pios_board.c, line 469 [r1]](https://reviewable.io:443/reviews/d-ronin/dronin/414#-K8WsxXYXzR-F52RcC5v:-K8WsxXYXzR-F52RcC5w:1183535494) ([raw file](https://github.com/d-ronin/dronin/blob/3a53473482bf78a3f81a2f093dabacf842b5c4d9/flight/targets/flyingf3/fw/pios_board.c#L469)):_
I don't know how I feel about these changes but can live with them.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/414)_

**Comment by jihlein** [comment]
"I don't know how I feel about these changes but can live with them."

FWIW, this is the same way we handled the RX port on Quanton, if that helps.... :)

and

I need to push a fix for the FrSky ports, they are indeed wrong.

**Comment by mlyle** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/414#-:-K8XKFruYebro5sQejxj:1417088721)_

**Pull request merged**
