### PR TITLE
flight: support openlog on lux

### PR DESCRIPTION
**Pull request by mlyle**
[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/458)

### CODE REVIEW

**Comment by mlyle** [comment]
just written and compiled.  No test yet.

**Comment by henn1001** [comment]
Seems to work -> #450

**Comment by mlyle** [comment]
@henn1001 You have a Lumenier LUX and tried it on that target?

**Comment by henn1001** [comment]
Nope - sorry i meant it works on sparky2. But it was more or less a copy paste from your implementation.

**Comment by mlyle** [comment]
Please feel free to open an PR :)

**Comment by henn1001** [comment]
My commit depends on some changes in this PR - should i make it standalone or base it on this one?

**Comment by mlyle** [comment]
The only change this has outside the target is to work when there's no SPI flash on a target.  Sparky2 has a SPI flash, so it shouldn't need that part of the change  (that is, the #ifdef in logging.c will not omit any code on sparky2).

Lux is the first target we'd support logging on that doesn't have any logging flash internally.

**Comment by jihlein** [comment]
Actually AQ32 is that way too, it's why I put it on openlog originally.

**Comment by mlyle** [comment]
@jihlein ah, aq32 could probably be slightly cleaned up for how it bypasses that after this PR, then.

**Comment by mlyle** [comment]
Rebased

**Comment by mlyle** [comment]
Confirmed to work nicely on Lux.

**Pull request merged**
