### PR TITLE
GCS:Lux: Rename ports to match silk, fix GUI

### PR DESCRIPTION
**Pull request by tracernz**

### CODE REVIEW

**Comment by mlyle** [comment]
If we're going to do this, can we please rename the fields in the uavo to uart2/uart3 at the same time?

**Comment by tracernz** [comment]
Yep, gladly, all ports match the silk now. UART1 tx config added too (although unused ATM).

**Comment by tracernz** [comment]
Okay, now we always do PPM and can use UART1 for lots of things. Completely untested.

**Comment by mlyle** [comment]
I guess with the past refactor, the "always do PPM" behavior got lost.  Very nice.

**Comment by mlyle** [comment]
Reviewed and it looks good to me.  My proto Lux still detects receiver.  Thanks so much for improving this target.

**Pull request merged**
