### PR TITLE
Support for Oneshot42 and 24 MHz PWM

### PR DESCRIPTION
**Pull request by tracernz**
With the release of the latest KISS ESC 24A Race Edition ESCs comes Oneshot42. This is a first cut to add support for 24 MHz timer operation and Oneshot42 in the GCS setup wizard. 24 MHz output only tested on Sparky1 with scope so far. I think there are prescaler issues on F4/168 MHz SysClk when using timers on APB1 which I will need to investigate/solve. Possibly other issues I will discover when I delve into datasheets.

Anybody have Oneshot42 ESCs to flight test when this is ready (NOT YET)?

Note: the 2 commits from #440 are included in this PR as it will merge first and would otherwise clash with this. Is that the right thing to do?

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/442)

edit by mlyle: connects to #219

### CODE REVIEW

**Comment by mluessi** [comment]
I think this would be automatically solved by #219, WDYT?

**Comment by tracernz** [comment]
@mluessi Good suggestion. I'll include that in this PR and it will take care of my problems.

**Comment by fujin** [comment]
@tracernz I have these ESCs when you are ready for test.

**Comment by tracernz** [comment]
Superseded by #958

**Pull request closed without merging**
