### PR TITLE
package: adjust package naming

### LINKED ISSUE #1582: Packaging: Artifacts from each platform should have unique names
Some of the Windows and MacOS ones overlap currently. should be `dronin-{tag}-{platform}(-{extra-info})?.(zip|tar.xz)` or similar.

### PR DESCRIPTION
**Pull request by mlyle**
fixes #1582

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
argh, forgot to push.

**Comment by mlyle** [comment]
jenkins, build artifacts please.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

Will eventually get this right.

**Comment by tracernz** [comment]
Awesome! :+1:

**Pull request merged**
