### PR TITLE
Fix maximum yaw_scale to match the tested value

### PR DESCRIPTION
**Pull request by droidicus**
Fix maximum yaw_scale to match the tested value

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/262)

### CODE REVIEW

**Comment by mluessi** [comment]
LGTM. I assume it's safe to merge this (?).

**Comment by mlyle** [comment]
It'd be nice if it could see one third-party flight test, because I can't rule out that "bouncing" off the edge of the scale has some useful characteristic.  Or a good argument from plots that we get nowhere close to that on normal runs.

**Comment by mlyle** [comment]
@droidicus do you have a few plots of yaw_scale from past flights?

**Comment by droidicus** [comment]
Here is a typical plot from one of Fujin's runs on his 225mm race quad:
image

This would cause an increase in actuation during the initial convergence (0.2 -> 0.25), but no difference after ~7 seconds. I do not think that the step-decrease when going from a 0.25 to 0.251 is intentional, there doesn't seem to be a rational reason to have a discontinuity in the actuation curve.

**Comment by mlyle** [comment]
I don't understand the plot.  Isn't it supposed to be limited to 0.2/0.25?  How'd it get up to 1.3?

**Comment by mlyle** [comment]
Ah, this is just on the stabilization side.  I hadn't read this before.  No big deal.

**Pull request merged**
