### PR TITLE
Preliminary support for OmniPreSense mm-wave radars on pi/sim

### PR DESCRIPTION
**Pull request by mlyle**
New driver, etc.  Some enhancements to hardware initialization on pi to allow it to work via callbacks instead of dedicated tasks (e.g. like receiver protocols work on other targets).

https://omnipresense.com/index.php/product/ops241-a/

### CODE REVIEW

**Comment by mlyle** [comment]
Status so far: tested in sim mode on Linux, with me typing in ranges over telnet manually.  About to build and get on Pi... hopefully integrated with and flight tested tomorrow.

The current modules provide just doppler (velocity) information, so utility is limited.  But it will be interesting to compare the data against our current vel estimates.  There is no integration with actual state estimation or control path yet.

No effort has been made to correct velocities or ranges for actual attitude of craft.  (It's not clear to me we should do this in the driver, either, instead of up in the attitude estimation loop).   TBD.

**Comment by mlyle** [comment]
image

Ranges make it end to end (with manual entry) on Pi.

**Comment by mlyle** [comment]
@yamahabest fixed thx :P

**Comment by mlyle** [comment]
This doesn't work in practice, for poorly understood reasons having to do with USB-CDC serial and tcgetattr/tcsetattr hanging on the module.

**Comment by tracernz** [comment]
> This doesn't work in practice, for poorly understood reasons having to do with USB-CDC serial and tcgetattr/tcsetattr hanging on the module.

😢

**Review by tracernz — APPROVED** [review]
Didn't spot anything. 👍

**Comment by mlyle** [comment]
Yah, the device in question does odd things when you stty it.. though screen works.  It's similar to our CDC bugs, really.  Will be looking to work-around it.

**Comment by mlyle** [comment]
Rebased.  Still needs verification.

**Comment by mlyle** [comment]
image

Successfully flight tested.

**Comment by tracernz** [comment]
Got an unrelated commit in here somehow (88ac460).

**Comment by mlyle** [comment]
Good eye.

I'm not sure we want to merge this anyways-- right now the sensors are not plugged into the flight loop, and only provide doppler (vel) information.

**Comment by tracernz** [comment]
> I'm not sure we want to merge this anyways-- right now the sensors are not plugged into the flight loop, and only provide doppler (vel) information.

Still neat though. Unmerged things tend to rot.

**Comment by mlyle** [comment]
image

**Comment by tracernz** [comment]
Thoughts on merging? I'm happy to press the button if you think you can use this in the future.

**Comment by mlyle** [comment]
Sure, might as well do ti, I guess :D

**Pull request merged**
