### PR TITLE
i2c: refactor common between F3 and F4

### PR DESCRIPTION
**Pull request by mlyle**
This depends upon #2012 .  It's mostly a change in the direction of cleanliness, though some of the F4 state machine stuff is breaking the implicit rules of the past state machine code style to make intention more obvious and ease further cleanup.  (That is, many state entry functions are named by **operation** rather than state, now).

Good test on Sparky and Sparky2.

This common factoring is in preparation for async-I2C-- to allow more complicated solutions without duplicating it in two places.

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
Looks okay.

**Comment by mlyle** [comment]
Rebased

**Comment by tracernz** [comment]
I'm happy to merge this subject to a little test. I'm thinking external mag or baro might be a good idea (although I don't see any risk that's obviously specific to those scenarios).

**Comment by tracernz** [comment]
Ext mag looks good on the scope (well, the wave rises rather sedately but this is i2c... 😛 ). 👍

**Pull request merged**
