### PR TITLE
GCS: Output - Stop max resetting neutral

### PR DESCRIPTION
**Pull request by fxbisto**
slider until we've finished character entry.

### CODE REVIEW

**Comment by fxbisto** [comment]
Related: https://github.com/d-ronin/dRonin/issues/2253

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, build artifacts please

(just to confirm health of build sys).

**Comment by mlyle** [comment]
Thanks for the fix!

**Pull request merged**
