### PR TITLE
flight: remove support for original coptercontrol (not CC3D)

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by dustin** [comment]
Oh cool.  I started some work on this, but it was a bit difficult to tell them apart.  Happy to see it go.

**Comment by mlyle** [comment]
Not promising it's 100%.  But yes, let's make progress on CC3D again.

**Comment by pug398** [comment]
I have an original CC but it hasn't been in flight for over a year. Won't miss it.

**Comment by tracernz** [comment]
Yeah, it's pretty much impossible to support it since no devs (AFAIK) have one and they're not available.

**Comment by mlyle** [comment]
I've got one.  It's really nifty and a great accomplishment for the time.

But given a choice between supporting CC & CC3D and having both suck, or good CC3D support, the choice is clear IMO.

**Pull request merged**
