### PR TITLE
Sparky: Add XTAL & Baro to BoM

### PR DESCRIPTION
**Pull request by tracernz**
As per title, details were missing. Also noted that the USB termination resistors are only present on rev. 1.0.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/330)

### CODE REVIEW

**Comment by tracernz** [comment]
Turns out the F3 includes USB matching impedance internally so the external series termination resistors are unnecessary. :)

**Comment by mluessi** [comment]
Looks like you forgot to fill in the "Supplier Subtotal" column

**Comment by tracernz** [comment]
Oops, fixed, thx. :)

**Comment by mluessi** [comment]
Thanks!

**Pull request merged**
