### PR TITLE
frsky_packing: Don't read out battery stuff, if the UAVO isn't initialized.

### PR DESCRIPTION
**Pull request by glowtape**
Apparently shit crashes with S.Port, if battery monitoring isn't enabled.

### CODE REVIEW

**Comment by glowtape** [comment]
Jenkins, build artifacts, please.

**Comment by glowtape** [comment]
Jenkins, build artifacts please.

**Comment by glowtape** [comment]
Tested by @LitterBugs and @yds, fixes #2214.

**Review by tracernz — APPROVED** [review]
Ack. :+1:

**Pull request merged**
