### PR TITLE
pios: fix the build

### PR DESCRIPTION
**Pull request by mlyle**
The pios sim and srxl changes interacted.  With either alone it was
fine; with both we couldn't build.

### CODE REVIEW

**Comment by mlyle** [comment]
(I will be self-merging this once it gets through Jenkins if there are no objections)

**Comment by tracernz** [comment]
Hmm, I would like to make these macros available to all code if possible. They're useful, and should be used in place of other byte-swapping stuff elsewhere too (to standardise). Is `#ifndef ntohl` etc. feasible?

**Comment by mlyle** [comment]
@tracernz then it becomes dependent on other headers, and some platforms they're extern, etc.  Yes, it would be nice to do in a generalized way, but I'm trying to fix the build.

**Comment by tracernz** [comment]
Okay.
P.S. `#include <pios_usart_priv.h>` doesn't look like it was needed in pios_srxl.h, could be for debug stuff I had early on, or it could be needed only in pios_srxl.c. :)

**Comment by mlyle** [comment]
;) yah, i tried a couple of things, ... it'd be nice to make all this cleaner later but i'm willing to incur debt for things workin'

**Pull request merged**
