### PR TITLE
Brain: add check BOR

### PR DESCRIPTION
**Pull request by mluessi**
Brain didn't have this, may fix a problem a user reported

### CODE REVIEW

**Comment by mluessi** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Cool, thanks!  Have you tried this / made sure it's safe?

**Comment by mluessi** [comment]
It seems to be working down to a input voltage of about 3.9V, so it should be safe. Is there anything else that should be tested?

**Comment by mlyle** [comment]
Nope-- if you want this to merge I'm glad to merge.

**Comment by mluessi** [comment]
I asked a user who had a problem to try this version and I haven't heard back, but it shouldn't hurt to have it, so go for it :).

**Comment by mlyle** [comment]
Thx!

I'm curious if it solves that guy's issue (he stopped by IRC).

**Pull request merged**
