### PR TITLE
Add headfree support

### PR DESCRIPTION
**Pull request by mlyle**
Tested in simulation, but.. coordinate systems are weird / i need to really try this FML.

### CODE REVIEW

**Comment by mlyle** [comment]
Behavior in sim: https://www.youtube.com/watch?v=LwERr0j6Jyg

**Comment by mlyle** [comment]
Just flight tested it on Lux.  Works perfectly.

**Comment by mluessi** [comment]
Awesome :). Code looks good to me. Do we need to add GCS warnings like we did for the camera angle mode?

**Comment by mlyle** [comment]
@tracernz already put in the correct warnings for headfree, and this connects to them. :D

**Pull request merged**
