### PR TITLE
Telemetry improvements

### PR DESCRIPTION
**Pull request by mlyle**
This is still work in progress..

Partial progress on #641.  Probably stability problems when changing metadata, because all of that needs vetting.  

Connects to #641

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/654)

### CODE REVIEW

**Comment by mlyle** [comment]
@droidicus I don't expect this to entirely fix #461, but if you're bored while I'm gone you might want to try a log download and see if it goes better with this code.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by pug398** [comment]
Gave it a try on Sparky2 with both sbus/ppm rx. GCS locks up on radio wizard max limits page every time using a clean install.

**Comment by mlyle** [comment]
Yah, I'm not surprised we'd have issues with some of the wizards, etc.  Thanks.

**Comment by mlyle** [comment]
OK, simplified the registration a bit further.  And also eased some of the unnecessary abuse of the telemetry system by GCS... Need to study this more.

**Comment by mlyle** [comment]
rebased.

jenkins, build artifacts please

**Comment by mlyle** [comment]
I've played with input wizards, calibration, etc.. over radio and direct.  It seems OKish.  Asked @pug398 for his opinion on this changeset; I'm sure he'll come up with a good way to break it right away. :)

**Comment by pug398** [comment]
Hmm I can't find anything wrong with it. BT telemetry link noticeably faster and radio wizard setup, level calibration and 6 point calibration all completed successfully. Much better than before :)

**Comment by mlyle** [comment]
Quanton, baseline memory statistics:  101532 heap remaining, 52652 fastheap remaining.
Quanton, with this PR: 102184 heap remaining, 54196 fastheap remaining.

**Comment by mlyle** [comment]
@pug398 thanks for the test.  Hopefully it continues to work-- this is a scary set of changes.

**Comment by mlyle** [comment]
CC3D, baseline memory statistics at branch point: 2412 bytes free
CC3D, with this PR:  2652 bytes heap free

240 bytes of net improvement on CC3D.

**Comment by mlyle** [comment]
Seems to work on CC3D; input cal, level detection, etc.

**Comment by mlyle** [comment]
Log download would be good to compare, too.

**Comment by tracernz** [comment]
Seems to work okay on CC3D. Compiled GCS with TELEMETRY_DEBUG on and no errors reported after onAutopilotConnect. Also cranked the Accels and Gyros rates up to 10 ms.

**Comment by mlyle** [comment]
So at this point, I'm convinced that things mostly work.

What'd be most useful to know is---

Can we upload waypoints over the radio now (i doubt it) -- malc said he is going to look at that
Can we download logs successfully more of the time (this may be better, but not completely fixed)-- hopefully @droidicus can take a peek and give a qualitative finding

**Comment by droidicus** [comment]
I did a bit of testing with this last night, and it seemed to be better. The issue I was seeing previously is random, so it is difficult to measure. But, I didn't see a log download pause in half an hour of testing, which is much better than it used to be.

**Comment by mlyle** [comment]
@tracernz reported telemetry drops at 3 minute intervals on CC3D on Linux.  Will try and see today if I can repro.

**Comment by mlyle** [comment]
@tracernz man, I just can't repro this either.

Have been sitting in GCS so far for 750 seconds staring at CC3D (linux, over remote X/xpra).  No issues.

Sorry for image-of-text, XPRA does not seem to copy-and-paste right on OSX:

image

(only one onAutopilotConnect)...

**Comment by mlyle** [comment]
Turned up gyro rates, saved a bucnh of objects, and farted around another 10 minutes.  No disconnect.  FML.

**Comment by mlyle** [comment]
https://www.youtube.com/watch?v=aAZRldDrFqM :(

**Comment by ukmook** [comment]
Tested usb > oplink > Sparky2.
All working well, ran radio setup wizard, automatic level detection, six point calibration, kept link up for 20mins with no issues,
Uploading way points fails with a "warning message".

**Comment by tracernz** [comment]
Possibly related to having telemetry debug log turned on (causing delay while strings are printing).

**Comment by mlyle** [comment]
If that's it, I don't think that should block this (unless it's a new regression).

**Comment by tracernz** [comment]
Indeed. I will try again tonight.

**Comment by pug398** [comment]
Can upload waypoints via bt telemetry (115k). Hangs with warning using sparky2>oplink. Not sure these follow the same path.

**Comment by tracernz** [comment]
Stupidly I was running firmware from another branch with GCS from this. Works perfectly when they match.

**Pull request merged**
