### PR TITLE
glc_lib: fix mismatched malloc/delete

### LINKED ISSUE #1716: mismatched delete[]/malloc in glc_lib
```
==23728== Mismatched free() / delete / delete []
==23728==    at 0x4C2E76B: operator delete[](void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23728==    by 0x1C701FD2: GLC_3dsToWorld::create3DRep(Lib3dsMesh*) (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)
==23728==    by 0x1C7025DA: GLC_3dsToWorld::createMeshes(GLC_StructOccurence*, Lib3dsNode*) (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)
==23728==    by 0x1C703E9A: GLC_3dsToWorld::CreateWorldFrom3ds(QFile&) (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)
==23728==    by 0x1C73A68C: GLC_FileLoader::createWorldFromFile(QFile&, QStringList*) (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)
==23728==    by 0x1C7A7148: GLC_Factory::createWorldFromFile(QFile&, QStringList*) const (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)

==23728==  Address 0x2c6fd040 is 0 bytes inside a block of size 854,568 alloc'd
==23728==    at 0x4C2CB3F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23728==    by 0x1C701C12: GLC_3dsToWorld::create3DRep(Lib3dsMesh*) (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)
==23728==    by 0x1C7025DA: GLC_3dsToWorld::createMeshes(GLC_StructOccurence*, Lib3dsNode*) (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)
==23728==    by 0x1C703E9A: GLC_3dsToWorld::CreateWorldFrom3ds(QFile&) (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)
==23728==    by 0x1C73A68C: GLC_FileLoader::createWorldFromFile(QFile&, QStringList*) (in /usr/local/dRonin/lib/dr/libGLC_lib.so.1.0.0)
```

### PR DESCRIPTION
**Pull request by mlyle**
fixes #1716

### CODE REVIEW

**Comment by tracernz** [comment]
[Should submit this upstream](https://github.com/laumaya/GLC_lib/pulls?q=is%3Apr)?

**Comment by mlyle** [comment]
sigh :P

**Comment by mlyle** [comment]
Looks like they have it but our impl doesn't match theirs.

We're eliminating this eventually, right?

**Comment by tracernz** [comment]
Yep. Interestingly there is a PR up there which has never been merged that uses Qts GL wrapper functions, which allows runtime selection between software GL, ANGLE, and hardware GL, thus allowing us to run on all hardware with good performance.. that's one of the adavantages of Qt3D.

**Pull request merged**
