### PR TITLE
frsky: properly use detected cell count in bat telem

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by yds** [comment]
works better than having to preset NbCells :)

however, the GCS GUI does not allow setting NbCells < 1

**Comment by mlyle** [comment]
Yah, you don't set the cells <1 on that page, you check the box that says "auto cell count detection"...

**Comment by yds** [comment]
checking out this build again I noticed the _Live detected cell count_ gets it wrong in the GCS when the LiPo is plugged in _after_ being powered up via USB.  If I plug the LiPo in first, then connect to the GCS, the count is right, unplug the LiPo and the count drops to zero, plug it in again and the count is right.

probably doesn't matter out in the field, cuz it gets it right when booting off a LiPo..  but looks wrong in the GCS when the LiPo gets plugged in after the GCS has already booted the FC via USB power..  I've gotten count==1 and count==3 while testing with a 4S at 16v..

**Comment by tracernz** [comment]
That’s board specific. I guess your USB supply is leaking back to whatever ADC input you use to measure battery.

**Comment by mlyle** [comment]
That or it's related to rise time.

**Comment by mlyle** [comment]
Added two changes to battery:

* Do cell detection after stable voltage for 1 second--- this should eliminate any rise-time (but not leakage) related effects.
* Sample at 4Hz instead of 2Hz-- so we can capture power usage more accurately and so that things seem more responsive.

**Review by tracernz — APPROVED** [review]

**Comment by mlyle** [comment]
changed-- the holddown was not initialized

**Review by tracernz — APPROVED** [review]

**Comment by glowtape** [comment]
Seems to LGTM.

Detects battery ~~voltage~~ cells fine, even on run down 3S and 4S batteries, USB plugged in beforehand or not. Recognizes different ~~voltages~~ cells during runtime while switching out 3S and 4S, while keeping it hooked up on USB.

**Pull request merged**
