### PR TITLE
upgrade: Fallback to GITHASH_OF_LAST_RESORT

### PR DESCRIPTION
**Pull request by dustin**
This change is [Reviewable](https://reviewable.io/reviews/d-ronin/dronin/850)

### CODE REVIEW

**Comment by mluessi** [comment]
Is there a way to automatically grab the tag of the latest release? It will be easy to forget adjusting this line with every release.

**Comment by mlyle** [comment]
See #848 and #849 ... yes, in summary, but it's not easy

**Comment by mlyle** [comment]
Confirmed this to do the right things-- fallback behavior and detection of missing rev.

**Comment by dustin** [comment]
Yes, we can figure out an appropriate tag dynamically.  We may even have
that information loaded, but not in a ready form.

I think the longer term goal here is to have the caller roughly know the
applicable history, so this is mostly a "last resort" for existing versions
that don't have deeper knowledge.

**Pull request merged**
