### PR TITLE
Add support for STM32F446

### PR DESCRIPTION
**Pull request by mluessi**
[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/742)

### CODE REVIEW

**Comment by fujin** [comment]
Maybe grab https://github.com/fujin/dronin/commit/d372d2ca9ae0645e7b3b576dacd7428dc989bca2 into this?

**Comment by mluessi** [comment]
@fujin I added it slightly differently as it is the same as for other F4s (see second last commit)

**Comment by fujin** [comment]
@mluessi ah that makes more sense. I see it now. Thanks!

**Comment by mlyle** [comment]
How should these things come in?

I have a feeling that RE support isn't going to be complete for tanto.. Should this stuff merge to tanto and add risk?  Should we merge it immediately after?

**Comment by dustin** [comment]
Is there any risk to having half a new target?

I suppose there's no real risk in having branches hanging out waiting to
become targets, especially since the majority of the development is
happening in one place.

**Comment by fujin** [comment]
I don't feel as though it is risky to bring in the support for stm32f446, it looks to all be guarded off with preprocessor directives appropriately. This isn't RE1 specific, either, a user with a 446 Nucleo or someone else developing stm32f446 FC could use it, no?

**Comment by mluessi** [comment]
My idea was to open these PRs now, as they are only indirectly related to RE1 and can be used in other future targets. The changeset in this PR is fairly small, so I don't think it's a big risk for existing targets.

**Comment by tracernz** [comment]
@dustin They touch code used by other targets though. The risk is pretty minimal in this particular case though. Is there any harm in holding them until after Tanto?

**Comment by mlyle** [comment]
@tracernz, from IRC, he says that maintaining these things in his branches is getting to be a pain.  Meh.  Might as well, but the bar for these to get merged is going to increase as we get closer.

**Comment by tracernz** [comment]
None of these are files we modify regularly, if at all, but okay I guess...?

-e- Except for pios_servo

**Pull request merged**
