### PR TITLE
Package:Deb: Include flight firmware

### LINKED ISSUE #481: Linux: Deb package is missing firmware
This dir is empty: https://github.com/d-ronin/dRonin/blob/next/package/linux/deb/_package.dirs#L5

### PR DESCRIPTION
**Pull request by tracernz**
@mlyle This should probably go in the hotfix.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/538)

edit: Fixes #481

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins build artifacts

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
Firmware is now in the deb. :) The only issue I see with this (not this PR specifically but the deb package in general) is that when I open the deb in Software Centre it tells me I already have a newer version installed (I have the original release installed).

**Comment by tracernz** [comment]
Fixes #481

**Comment by mlyle** [comment]
Confirmed firmware is present in artifacts.  Nice, thank you.

**Pull request merged**
