### PR TITLE
Trim angles to sub trim

### PR DESCRIPTION
**Pull request by droidicus**
Renaming TrimAngles to SubTrim, as per TauLabs/TauLabs#2037, Part of dRonin #55 

This is my first PR against the codebase, I am more then welcome to suggestions and/or outright rejection of this PR!

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/161)

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins: test this please

**Comment by tracernz** [comment]
Nice pick for a first PR! Looks good to me. It will need a rebase though, let us know on IRC if you need help there.

**Comment by tracernz** [comment]
ok to test

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/161)*

**Pull request merged**
