### PR TITLE
i-BUS: Increase channel count to 10

### PR DESCRIPTION
**Pull request by tracernz**
For their 10 channel radios e.g. FS-i10.

Not tested at all yet.

To merge:
- [x] Confirm this works with my protocol generator
- [x] Test on FlySky hardware

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by tomasa73** [comment]
Tested the build, and it works with 10ch, and iBus. Haven´t done any testflight yet. Still the TX wizard doesn´t get through. When I get to the screen when I do the stick calibration (move everything), no respone is seen on the screen. If I then press save, and set the input and channel manually and the do the manual calibration it works.

**Comment by tracernz** [comment]
Thanks for the test! What are the approximate minimum/maximum/neutral values you see when calibrating manually? I will generate some i-BUS packets with the same range and see if I can track down the issue.

**Comment by tomasa73** [comment]
Throttle 1007/1985
Roll 1008/1500/1998
Pitch 1004/1500/2000
Yaw 1000/1500/1992

**Pull request merged**
