### PR TITLE
4wif passthrough implementation.

### PR DESCRIPTION
**Pull request by mlyle**
Please don't be too mad at the ugliness. :p

### CODE REVIEW

**Comment by mlyle** [comment]
woops sorry for bumping that.

**Comment by mlyle** [comment]
Current state is able to flash ESCs attached to PWM1 on Quanton, using both BlheliConfigurator and BlheliSuite.

I did brick one ESC, but I am currently blaming it on either a bad connector or having clicked the button in blhelisuite twice (which seems to do very bad things!)  Have done a lot of read/write eeprom and a fair number of flashes to simonk and blh loader.

**Comment by mlyle** [comment]
Current plan: wait for #1714 to clean up actuator module to provide a path to disable actuators and then proceed.

**Comment by mlyle** [comment]
Rebased on top of #1714 / mpl-action

**Comment by mlyle** [comment]
screenshot from 2017-04-16 18-47-27

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
flew #1724 + #1714 + #1682 on lux-- upgraded 4 ESCs to newest blheli, changed settings, flew autotune, applied.

**Comment by jhitesma** [comment]
Gave this a try over the weekend without a ton of success.  I merged this into next then merged #1714 on top of it going with 1714 on any conflicts.  It built but I was unable to connect to blheliconfigurator from either a pikoblx or DTFc on mac or windows or to blhelisuite on windows.

@mlyle gave me his tlfw of this for the dtfc and I was able to connect to blheliconfigurator on mac with that - but was unable to read the ESC's.  

So this probably needs some cleanup to work on next and there may still be deeper issues as well.  Even so surprised I got as far as I did with it so looking forward to it.

**Comment by mlyle** [comment]
Note this already --includes-- / is based on top of #1714.

**Comment by jhitesma** [comment]
I just realized that...I was looking at your last comment about flying it on "#1724 + #1714 + #1682" but 1724 already merged so I was just looking at 1714+1682....but I was about to close this page and scrolled further back before I did and saw that this was rebased on 1714.  So that probably explains why I wasn't able to build it successfully.

**Comment by mlyle** [comment]
Confirmed that based to current next (picked up. prm/1682) is OK with sparky2 + littlebee20A + blheliconfigurator.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by jhitesma** [comment]
So after rebuilding on next without merging the other PR's I got it working.  On my pikoblx with racerstar 6a 1-2 blheli_s esc's I was able to connect with blheliconfigurator and read/write settings.

I was also able to flash the ESC's - however I was only able to do so one at a time.  If I tried to do more than one it would fail partway through the second one.  Logfile of failure attached: 
[fail_log.txt](https://github.com/d-ronin/dRonin/files/985584/fail_log.txt)

I was still able to disconnect and then reflash the failed ESC.  At the time it failed there were no lights blinking on my FC.

Doing the ESC's one at a time I was able to flash them, and change settings - confirmed by playing with the different startup tones in blheli 16.65.  I also confirmed dshot300 seemed to be functional on this setup based on beep tones.

I haven't got to fly it yet because for some reason while the motors respond to the sliders with "test motors" on the Outputs page I'm not getting any response from them when I arm even though GCS is indicating it's armed...but I probably just fouled up a config somewhere so need to look into that.

**Comment by jhitesma** [comment]
Oh, and on my DTFc I'm still not having much luck.  I can connect in blheliconfigurator but attempting to read the ESC's fails.  Those are older littlebee 30's on there though and I was able to connect to them with blheli suite after flashing BF.  May try flashing something newer on them and see if they play nicer then.

**Comment by mlyle** [comment]
jenkins, test this please

(see whether cutting sprf3e is sufficient)

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
ffs wrong button

**Comment by mlyle** [comment]
Brief test on DTFc seems OK:

**Comment by jhitesma** [comment]
Not sure why my DTFc still isn't playing nice.  I but BF on it and flashed the ESC's to the latest build of blheli.  Then flashed back and still won't read settings off them. 

I'll try the artifacts tonight to see if they do any better than my own build.

**Comment by jhitesma** [comment]
Tried the DTFc with the artifacts above and still can't read after connecting.  Here's what the configurator log shows:

Connecting to: /dev/cu.usbmodem14121
SERIAL: Connection opened with ID: 59, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 59
MultiWii API version <span style="color: green">received</span> - <strong>1.31.0</strong>
Flight controller info, identifier: <strong>DRON</strong>, version: <strong>1.0.0</strong>
Running firmware released on: <strong></strong>
Board: <strong>dtfc</strong>, version: <strong>0</strong>
Unique device ID <span style="color: green">received</span> - <strong>0x2800365233570e20343839</strong>
Reading setup
sending cmd_DeviceInitFlash 0 0
received cmd_DeviceInitFlash ACK_OK 0 178,232,100,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_D_GENERAL_ERROR 1a00 0
received cmd_DeviceRead ACK_D_GENERAL_ERROR 1a00 0
ESC 1 read settings failed cmd_DeviceRead ACK_D_GENERAL_ERROR
sending cmd_DeviceInitFlash 0 1
received cmd_DeviceInitFlash ACK_OK 0 178,232,100,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_D_GENERAL_ERROR 1a00 0
received cmd_DeviceRead ACK_D_GENERAL_ERROR 1a00 0
ESC 2 read settings failed cmd_DeviceRead ACK_D_GENERAL_ERROR
sending cmd_DeviceInitFlash 0 2
received cmd_DeviceInitFlash ACK_OK 0 178,232,100,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_D_GENERAL_ERROR 1a00 0
received cmd_DeviceRead ACK_D_GENERAL_ERROR 1a00 0
ESC 3 read settings failed cmd_DeviceRead ACK_D_GENERAL_ERROR
sending cmd_DeviceInitFlash 0 3
received cmd_DeviceInitFlash ACK_OK 0 178,232,100,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_D_GENERAL_ERROR 1a00 0
received cmd_DeviceRead ACK_D_GENERAL_ERROR 1a00 0
ESC 4 read settings failed cmd_DeviceRead ACK_D_GENERAL_ERROR
sending cmd_DeviceInitFlash 0 4
received cmd_DeviceInitFlash ACK_D_GENERAL_ERROR 0 0,0,100,1
received cmd_DeviceInitFlash ACK_D_GENERAL_ERROR 0 0,0,100,1
ESC 5 read settings failed cmd_DeviceInitFlash ACK_D_GENERAL_ERROR
sending cmd_DeviceInitFlash 0 5
received cmd_DeviceInitFlash ACK_D_GENERAL_ERROR 0 0,0,100,1
received cmd_DeviceInitFlash ACK_D_GENERAL_ERROR 0 0,0,100,1
ESC 6 read settings failed cmd_DeviceInitFlash ACK_D_GENERAL_ERROR
sending cmd_DeviceInitFlash 0 6
received cmd_DeviceInitFlash ACK_D_GENERAL_ERROR 0 0,0,100,1
received cmd_DeviceInitFlash ACK_D_GENERAL_ERROR 0 0,0,100,1
ESC 7 read settings failed cmd_DeviceInitFlash ACK_D_GENERAL_ERROR
sending cmd_DeviceInitFlash 0 7
received cmd_DeviceInitFlash ACK_D_GENERAL_ERROR 0 0,0,100,1
received cmd_DeviceInitFlash ACK_D_GENERAL_ERROR 0 0,0,100,1
ESC 8 read settings failed cmd_DeviceInitFlash ACK_D_GENERAL_ERROR
Reading setup <span style="color: green">finished</span>

**Comment by jhitesma** [comment]
Tested @mlyle's last push with the timing tweak and it now works on my DTFc with LB30a ESCs!

**Comment by mlyle** [comment]
With this last commit, blhelisuite works on Windows.

**Comment by jihlein** [comment]
More testing - BL Heli Suite never connected in any of the cases below, but BL Heli Configurator worked fine.

AQ32 - ESCs on channels 1, 2, and 3
DTFc - ESCs on channels 3, 4, and 5
Naze32Pro - ESCs on channels 3, 4, 5, and 6
Quanton - ESCs on channels 5, 6, 7, 8, and 9

I reprogrammed the 4 ESCs on the Naze32Pro with no issues, all others I just read the settings, which were correct.  Only thing that I didn't like is that servo channels go hard over to the minimum value while connected to the BL Heli Configurator.  I'm not sure if it went to the minimum pulse width of 1000 ms or the configured min value, but it was definitely hardover at one of those.  If I didn't have to take the whole aircraft apart, I would have thrown the logic analyzer on it to find out.  While it was okay in my installation, this could cause binding in some installations depending on the mechanical setup of the aircraft.  Can servo channels be set to the neutral value while under BL Heli Configurator control?

**Comment by mlyle** [comment]
@jihlein -- right now they're all interrogated as serial ports.  It's probably the ESC serial pulses not a minimum value, etc.  We don't have any logic to disable / prevent it from talking to servo channels because I didn't want to require configuration-- might be best to implement something so that things explicitly configured as servos are skipped (but disabled & motor are listed).

Does the failure to use blhelisuite relate to not-working VCP (I remember you had a problem with Windows 7 / talking to it)?

**Comment by jihlein** [comment]
@mlyle - I got the CDC driver to install on Windows 7, so good there.  Don't both blhelisuite and blheliconfigurator use the same driver?

At any rate, configurator works all the time, it did connect once to suite.  Most of the time blhelisuite tries to reset the board and then errors out with a no connection error.  I'll get a screen shot next time I try.

**Comment by mlyle** [comment]
@jihlein -- what githash are you running?  (or i guess since it's your own branch, what subset of the above did you have merged?)

**Comment by jihlein** [comment]
I'm rebased to the current next, then merged with:
SHA-1: 8dc0832953f2c5455e1f1372c5de029b04af3fea

* 4wif: improve bit timing further

I'm currently behind one commit, which I'll merge shortly.

**Comment by jihlein** [comment]
@mlyle -- Have now merged:

SHA-1: d889487660ed68ac31227989b9c754343eee71b2

* 4wif: only do disabled or motor channels

This means if there's servo or camera stuff indexes won't line up any
more, but at least we won't send scary short pulses to servos.

On Quanton, all 5 ESCs readable, on both BLHeli Config and BLHeli Suite.  Servos stay at neutral, very nice.

On DTFc, all 3 ESCs readable, but only on BLHeli Config.  BLHeli Suite will not connect, tries to reset the board and then fails to open com.  After a failed attempt with BLHeli Suite, BLHeli Config will not connect until DTFc is powered down and reset.  Servos stay at neutral.

**Comment by mlyle** [comment]
@jihlein -- outstanding, I'm glad the skip-servos-worked (had not tested it myself yet).

Can you please, on dtfc/blhelisuite, enable the log and get a (yuck) screenshot of the first failed attempt, with whatever failures look interesting expanded?  I kinda wonder if it's something dumb like exhausting stack.

**Comment by jihlein** [comment]
@mlyle - looks like an MSP receive failure.

capture1

capture2

Let me know what else you need.

**Comment by jihlein** [comment]
@mlyle - FWIW, Sparky1 and Naze32Pro, also F3 based boards, generate the exact same errors as posted above fr DTFc.

**Comment by mlyle** [comment]
@jihlein -- maybe this is better?  I found F3's USB CDC implementation has one of the same bugs as F4 did. :D

**Comment by jihlein** [comment]
@mlyle - yes better, it connects reliably to both suite and configurator, but I'm getting a ram warning now, down to 712 bytes heap remaining.  I'm testing on a tricopter, so I disabled triflight routines and rebooted to see if that was the cause, but still had the warning and 712 bytes of heap remaining.

**Comment by mlyle** [comment]
Is that with autotune running?  If so it's normal.

**Comment by jihlein** [comment]
Good catch, autotune turned off and its back in the green at 9256.  

Is it safe to fly and autotune at 712?

**Comment by mlyle** [comment]
Yes, it should be-- I don't believe anything allocates memory after arming.

**Comment by mlyle** [comment]
@jihlein note if this is your own target, you probably want the autotune decimation stuff I added to other F3 targets, btw.

**Comment by jihlein** [comment]
@mlyle - Already have.  I've noticed in general F3 targets are beginning to be tight on memory, and the few F3 targets that run at 1 kHz gyro sample rate are bouncing around the 80% throughput point.  There's still some headroom, but I notice that if I run my triflight code with PPM RX, DTFc is around 77% CPU.  The same config with sBUS is around 82%.  This is with the autotune module enabled, I have not check it with autotune running......

**Comment by mlyle** [comment]
@jihlein new autotune is cheap in CPU (though right now we're running the old,expensive one in parallel), but it definitely uses memory-- 6k or so on 1KHz targets, which is pretty noticeable when you have 32k of ram (plus a couple k for stack and data structures for old autotune).

So once some other PRs get merged and I can get to work on completing new autotune, a bunch of resources will free up.  @glowtape has a PR in early stages that will significantly reduce memory and CPU use in sensors, too.

**Comment by mlyle** [comment]
@tracernz -- what does this need for merge?  thx

**Comment by tracernz** [comment]
Review. Hard to find a big enough chunk of time for a PR of this size sorry. :(

**Comment by mlyle** [comment]
I will break this up some.

**Comment by mlyle** [comment]
Superseded #1779 #1780 #1781

**Comment by tracernz** [comment]
Thanks! That makes it easier. 👍

**Pull request closed without merging**
