### PR TITLE
GCS:Uploader: Usability tweaks

### PR DESCRIPTION
**Pull request by tracernz**
Just some small tweaks I've wanted to make. The UI really needs some major work, but this is some small steps to make what we have better until that happens.
- Button visibility changed
- OSD capability added
- Progress bar only shown when used
- Partition browser sizing fixed
- General small tweaks

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/677)

### CODE REVIEW

**Comment by mlyle** [comment]
Can't test yet.  But if this does what I think you'd do--- prevent hiding buttons-- thank God.

**Comment by mluessi** [comment]
Very nice. I just tested this. Not having the button "jump around", i.e., always showing the same buttons at the same locations but disabling them is a huge usability improvement IMO.

An idea I had the other day: How about automatically selecting the correct firmware file when the board is connected? So one could just do "Rescue, Connect Board, Flash". Naturally, the "Open File" button should still be there in case one wants to open a bl_ file etc.

**Comment by tracernz** [comment]
@hshred, yep, I have a branch somewhere fixing the firmware file location stuff but osx is being a problem.

**Comment by tracernz** [comment]
Oops, @mluessi ^^

**Comment by mluessi** [comment]
@tracernz I didn't just mean the file location (which btw is broken in the last release), I meant when the board is connected, the uploader could automatically select the file, so one wouldn't have to click on "Open File".

**Comment by tracernz** [comment]
@mluessi, I understand. Finding the files is the pre-req and then it would be trivial to auto-load. Could probably go in the same  PR. ;-)

**Comment by mlyle** [comment]
Confirmed working by @mluessi, code looks good.  Thanks much!

**Pull request merged**
