### PR TITLE
flight: remove printf2

### LINKED ISSUE #377: We should use the printf from the libraries
Not our own custom one.

Also, we may need to set target specific flags depending on whether we want to handle printf of floats.  e.g. LDFLAGS += -u _printf_float

```
targets/aq32/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/bl/f1/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/bl/f3/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/bl/f4/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/brain/fw/Makefile:SRC += $(PIOSCOMMON)/printf2.c
targets/colibri/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/coptercontrol/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/discoveryf4/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/flyingf3/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/naze32/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/pipxtreme/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/quanton/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/revomini/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/sparky/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
targets/sparky2/fw/Makefile:SRC += $(PIOSCOMMON)/printf-stdarg.c
```

Also note brain is different/"special".

### PR DESCRIPTION
**Pull request by mlyle**
Alternate solution to #394.  Connects to #394.

Fixes #377 

Untested

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/410)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mluessi** [comment]
Nice :)

**Comment by mluessi** [comment]
Bench tested it on brain: It hangs after a few seconds (OSD does show up). It hangs in `vectors.c`, `_unhandled_exception`. Unfortunately there is no backtrace, so not sure what point in the code is causing it.

**Comment by mlyle** [comment]
Interesting.  This worries me that something is calling sbrk, which will have undefined behavior.

**Comment by mlyle** [comment]
Added a commit to assert(0) in _sbrk.  If the crash relates to sbrk then at least the trace that causes it will be clear and we can go from there.  @hshred Any chance you can try this again?

**Comment by mlyle** [comment]
jenkins test this please

**Comment by mlyle** [comment]
god damn clicked wrong button

**Comment by mluessi** [comment]
`_sbrk` is getting called by sprintf:
call stack: _sbrk / _sbrk_r / _malloc_r / _calloc_r / _Balloc / __d2b / _dtoa_r / _svfprintf_r / sprintf 

deferring this to after the release.

**Comment by mlyle** [comment]
_dtoa_r ends up doing multiple precision stuff.  Looks like we need our own implementation of it.

**Comment by mlyle** [comment]
So I've fiddled with this.

Not super pleased with it.  Not sure it works, even now.  And it doesn't fit well on F1/F3; so debug printf stuff doesn't really want to work on those targets (not sure it would really work there anyways).

Anyways, deferring for further study.

**Comment by mlyle** [comment]
Not worth it for now, abandoning.

**Pull request closed without merging**
