### PR TITLE
uavos: logging: log a few more objects by default in custom profiles

### PR DESCRIPTION
**Pull request by mlyle**
AttitudeActual/StabilizationDesired are the minimum needed to have some
idea what's going on... ManualControlCommand doesn't hurt.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/397)

### CODE REVIEW

**Comment by mluessi** [comment]
@mlyle for them to be logged with the default profile, they would need to be added in the code. This just makes them being logged with the custom profile.

**Comment by mlyle** [comment]
Thanks for pointing that out.  I assumed that the actual default profile had both of these, but it was slightly different.

**Comment by mluessi** [comment]
LGTM. Did you have a chance to test this? I think it should be fine to merge without test.

**Comment by mlyle** [comment]
No test, unfortunately.

**Comment by ekaszubski** [comment]
@mluessi @mlyle I can test this after lunch today

**Comment by ekaszubski** [comment]
Fetching and testing now

**Comment by ekaszubski** [comment]
@mluessi  @mlyle Confirmed logging periods are set correctly on sparky2.

**Comment by mluessi** [comment]
@ekaszubski thanks for the test!

**Pull request merged**
