### PR TITLE
onscreendisplay: fix home distance in imperial units

### LINKED ISSUE #38: home_dist calculation error
in onscreendisplay, home_dist is multiplied by convert_distance twice before it is displayed on the user screen, resulting in a 3.28X home distance if displaying in imperial units. See lines 1121 and 1348.

Attached is the updated onscreendisplay.c file with the issue corrected.
[onscreendisplay.zip](https://github.com/BrainFPV/TauLabs/files/78764/onscreendisplay.zip)

### PR DESCRIPTION
**Pull request by mlyle**
Credits to @droney

fixes brainfpv/taulabs#38

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/395)

### CODE REVIEW

**Comment by dustin** [comment]
Can you just set @droney as the author?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/395#-:-K7ISlL3ibuGuos03kK8:1137005042)*

**Comment by mlyle** [comment]
I don't have his email address.

**Comment by mluessi** [comment]
Oh wow, silly bug. Good find.

**Comment by droney** [comment]
I updated my profile to make my email address visible. I hope that was not a mistake ;)

**Comment by mlyle** [comment]
Attribution fixed.

**Comment by mluessi** [comment]
LGTM and bench tested, merging. Thanks!

**Pull request merged**
