### PR TITLE
Use shared USB ID definitions, move all boards to dRonin IDs

### PR DESCRIPTION
**Pull request by tracernz**
Move all targets to dRonin USB IDs (while GCS will still support legacy IDs for the foreseeable future). Windows installer is modified to allow installation of CDC driver on Windows <10.

P.S. target_code--

To test:
- [x] Win installer, Win 10
- [ ] Win installer, Win <10
- [x] Debian installer

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Super nice / I'm excited for this stuff :D  

Not in a rush to merge anything though :)

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
@lrvick I cherry-picked your commit and hacked it so I could lazily give you credit. Let me know if you're unhappy with that.

Also, cleaned up the original formatting of the script (tabs->spaces... editor is setup for flight code, and made some lines a bit shorter).

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
.deb and Windows 10 good, Windows 7 doesn't show the driver: #1604

**Pull request merged**
