### PR TITLE
GCS:Config:Input: Add description of arming timeout

### LINKED ISSUE #427: Arming timeout in GCS very confusing to end users.
We need to improve this.

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #427 

Also changes default input tab to be RC input.

screenshot from 2016-01-15 16 01 38

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/446)

### CODE REVIEW

**Comment by mlyle** [comment]
Edited top desc

**Comment by DTFUHF** [comment]
I agree this needs to be changed.... but this is far too confusing and
wordy.

Maybe the solution is to use radio buttons for each arming type, with a
tooltip for each one.

**Comment by mlyle** [comment]
We could move arming timeout to its own box with the second paragraph.

**Comment by tracernz** [comment]
Better?
screenshot from 2016-01-15 16 40 04

**Comment by mlyle** [comment]
@dtfuhf Like that more?  I think I do.  (Maybe slightly nudge down the Arming timeout since we have lots o' space)

**Comment by DTFUHF** [comment]
It's a start, but I disagree more with the paragraph of text.

If you don't like radio buttons, maybe the text can be updated to describe the currently selected arming mode. If the user isn't using a switch arming mode, then the text does not have to be complicated with its description.

**Comment by mlyle** [comment]
I agree it's a little TLDR for many of our users.  It's still better than nothing, and I'd prefer solutions that don't incur code and just change .ui files.  Can always improve more in future releases.

**Comment by tracernz** [comment]
I don't want to go changing code and introducing bugs at this point in the release cycle. We can revisit at the next release.

**Pull request merged**
