### PR TITLE
Actuator clipping management

### LINKED ISSUE #229: Actuator Clipping Management (ghettomixer v2+)
Discuss ghettomixer, settle on sane controls implementation @mlyle should probably sign off on

References https://github.com/d-ronin/dRonin/issues/182

### PR DESCRIPTION
**Pull request by mlyle**
This is the beginning, no "air mode" or anything yet.  Just wanted to get this in, and in place.

Adds a clipping alarm.  Removes the previous "anti-negative-clip" mechanism as it was unsafe.  

Unfortunately this will break a small part of #151 / #457 because of code relocation.

Fixes #229 
Connects to #228

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/608)

### CODE REVIEW

**Comment by mluessi** [comment]
Nice. I wonder what the best way to handle this is. It seems to me that knowledge of the mixer input and matrix would be helpful, so actuator output could be managed to give the desired response without clipping.

**Comment by mlyle** [comment]
@mluessi IMO this does the sane thing-- if the commands are just bumped off the top it sacrifices throttle.  If the commands also exceed total range, it scales, which has the effect of mostly preserving the extreme / large command and slightly sacrificing other axes.

> It seems to me that knowledge of the mixer input and matrix would be helpful, so actuator output could be managed to give the desired response without clipping.

You've got to give up on something.  And it has to be the next layer up / an actual control loop that does it, so that integrators don't wind, etc.  That's a future item to work on (actuator clip feedback).

Next step after this merges will be to handle the negative-clipping case, low-power rate loop integrator windup cases, and to decay throttle before going to force-all-motors-to-neutral (air mode).  We also really need at least a minimal actuator curve fit, but Droidicus's autotune thing has to merge before that.

Also need space freed on sparky before this one can merge, so all in all a lot of dependencies to manage.

**Comment by droidicus** [comment]
Feel free to break #457, it is fixable.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by fujin** [comment]
yay, even a clipping alarm! excited to test this when I'm back in NZ.

**Comment by mlyle** [comment]
Interesting effect when playing with this at zero-throttle.  Moving the sticks causes an "ACTUATOR" alarm, because anything clips.

**Comment by mlyle** [comment]
Apologies for world's worst video.... unknown cause of that.

Here's some clipping management (and setting off the clip alarm) during aggressive rolling.

https://youtu.be/-1gIK2GcjP8?t=1m57s

**Comment by dustin** [comment]
This looks pretty good so far.  :lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/608#-:-K9nF0TD_yY-MD8J0ldp:-215887419)_

**Pull request merged**
