### PR TITLE
gcs: inputwizard: require minimum ranges for all channels

### LINKED ISSUE #380: InputWizard: Improve flight mode switch handling
If switches are configured, do not allow user to proceed from input wizard calibration until a minimum range is realized.

Also, add a message to emphasize toggling switches.  TauLabs/Taulabs#1241

### PR DESCRIPTION
**Pull request by mlyle**
Also text edits.  Fixes #380

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/381)

### CODE REVIEW

**Comment by mlyle** [comment]
Tested with DSM and SBUS on F1.

**Comment by droidicus** [comment]
Tested with Sparky2 over SBUS on Win10, next plus this PR and #364 . Looks like it is working.

One concern is that there is no feedback on why you cannot press "next", and there is no way to bypass this if need be.
It also appears that the Manual Calibration function is not obeying the minimum ranges, not sure if it should though.

**Comment by mlyle** [comment]
I made no changes to manualcalibration.

Any advice on feedback?  I'm not sure I see a good reason for a user to bypass it (if they want to do something really weird, they should use manual calibration).

**Comment by droidicus** [comment]
it might be nice if there was a message on the screen that said something along the lines of "Yaw axis must be moved more to continue"...

Another option would be to use the "centering" arrows (from the previous step), and remove them after each axis has been moved enough to proceed.

UI is not really my strong suit though.

**Comment by PTDreamer** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[ground/gcs/src/plugins/config/configinputwidget.cpp, line 588 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/381#-K78781gHFvT_mkpqIDy:-K78781gHFvT_mkpqIDz:-2029721160) ([raw file](https://github.com/d-ronin/dronin/blob/ee8a2a7315936f33d3062717b5479e4682cc81a7/ground/gcs/src/plugins/config/configinputwidget.cpp#L588)):*
Remove commented out code

---

*[ground/gcs/src/plugins/config/configinputwidget.cpp, line 971 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/381#-K786FVsO81nGnutdxWT:-K786FVsO81nGnutdxWU:461893520) ([raw file](https://github.com/d-ronin/dronin/blob/ee8a2a7315936f33d3062717b5479e4682cc81a7/ground/gcs/src/plugins/config/configinputwidget.cpp#L971)):*
Can this magic values be #defined on top?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/381)*

**Comment by PTDreamer** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/381#-:-K787LM7nMNqdUtc3QSW:676834233)*

**Comment by mlyle** [comment]
@droidicus Too hard.  I'll adjust the label text. ;)

**Comment by droidicus** [comment]
LGTM as well.

**Comment by mlyle** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[ground/gcs/src/plugins/config/configinputwidget.cpp, line 588 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/381#-K78781gHFvT_mkpqIDy:-K78Eu0ZG--MilBN4ZUT:-499146009) ([raw file](https://github.com/d-ronin/dronin/blob/ee8a2a7315936f33d3062717b5479e4682cc81a7/ground/gcs/src/plugins/config/configinputwidget.cpp#L588)):*
Done.

---

*[ground/gcs/src/plugins/config/configinputwidget.cpp, line 971 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/381#-K786FVsO81nGnutdxWT:-K78Euo8arO7GjEMXH3i:-499146009) ([raw file](https://github.com/d-ronin/dronin/blob/ee8a2a7315936f33d3062717b5479e4682cc81a7/ground/gcs/src/plugins/config/configinputwidget.cpp#L971)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/381)*

**Comment by mlyle** [comment]
https://www.youtube.com/watch?v=1eKNxsjx-OU

**Comment by mlyle** [comment]
(interesting bit is here: https://youtu.be/1eKNxsjx-OU?t=10s )

**Comment by mluessi** [comment]
LGTM, merging.

**Pull request merged**
