### PR TITLE
build: introduce new script to display credits information

### LINKED ISSUE #271: GCS: Fix Authors Credit
In the GCS "Help->About Authors.." is still referring to the TL project and the list of authors seems to be outdated. Ideally, the authors list should be created automatically from git commits.

### PR DESCRIPTION
**Pull request by mlyle**
Based on dumb metric for sorting (number of commits, exponentially
decaying with 18mo half life).

This is work in progress awaiting comment.  When complete: fixes #271

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/336)

### CODE REVIEW

**Comment by mlyle** [comment]
If we took this approach, we'd need to spend effort on the mailmap in git (to collapse identical authors, too, e.g. guilhermito vs. PT_Dreamer etc)

Output looks like this right now:

```
const char credits[] =  "James Cotton, Michael Lyle, guilhermito, lilvinz, Kenn Sebesta, Stacey Sheldon, Michael Corcoran, BrainFPV, PT_Dreamer, ernie of infect, peabody124, Edward T. Kaszubski, jihlein, edouard, Martin Luessi, Trex4Git, Oleg Semyonov, zedamota, Brian Webb, pip, Dustin Sallings, dankers, Laura Sebesta, Corvus Corax, DTF UHF, hernick-qc, Mike LaBranche, Kenz Dale, Daniel Strnad, Fredrik Arvidsson, David Ankers, Ed, stac, janfietz, KipK, sambas, Sambas, corvus, vassilis, elafargue, gussy, VArcht, ephy, Werner Backes, Dmytro Poplavskiy, AJ Christensen, FredericG, Murilo Pontes, Edouard Lafargue, a*morale, chris pember, Jan Hurst, Jose, Chris Pember, Jos\u00e9 Xavier, andrew, osnwt, taulabs, cranphin, ufoDziner, henkf, Mathieu Rondonneau, tracernz, cwabbott, Andrew Thoms, martin, droidicus, Mischa Aster Alff, fredericg, Lars Johnsen, Jose Xavier, sirPerna, PTDreamer, Alessio Morale, Richard Flay (Hyper), Nathan Feldkamp, cGiesen, unknown, ligi, David, gedsol, erhard, julien, chebuzz, Thomas Greer, naiiawah, David Willis, rdnzl, muralha, jonathan, Laurent, banigreyling, mattl, Erik Gustavsson, Oscar Andreasson, taumcg, les, Peter Gunnarsson, edboer, filnet, Laurent Ribon, m_thread, Hotlobster, Montspy, vke, Nickolay, Mike Smith, Ye Wang, Kari Hautio, kokomojoe, Jason Hitesman, tgreer, dschin, Koen Kooi, David Carlson, cloner, jb, joergrohde, Kevin Vertucio, Francesco Nero, Dmitry Zaitsev, LinuxJohannes, Patrick Huebner, Michael Schulz, Erik Bernhardson, PeterG, Tim G, guy, Fotis Georgatos, Sergiy Anikeyev, Carlos Antunes, dgodin, Moritz Ulrich, scenkov, Michael Hope, David Buzz Carlson, Paul McMillan, metropt, Ivan Sevcik, Luke, James Whitlock, Scott Parker, dasdboot, scott, Mikael Blomqvist, Bertrand Songis, darkz, thenobody, marcus bueschleb, banig, zillatrooper, loris, sparkie79, Frithjof Siebecke, pedro, Nuno Guedes, Igor Van Airde, dwobdar, Ryan Hunter, Theodore A. Roth, Michael Rumpler, LM, Brian Mahaffy, pete, esden, James, Pip, richard, nickolay, patrick, GoogleMap,GoogleSatellite,GoogleLabels,GoogleTerrain,GoogleHybrid,GoogleMapChina,GoogleSatelliteChina,GoogleLabelsChina,GoogleTerrainChina,GoogleHybridChina, OpenStreetMap,OpenStreetOsm,OpenStreetMapSurfer,OpenStreetMapSurferTerrain,YahooMap,YahooSatellite,YahooLabels,YahooHybrid,BingMap,BingSatellite,BingHybrid, ArcGIS_Map,ArcGIS_Satellite,ArcGIS_ShadedRelief,ArcGIS_Terrain,ArcGIS_MapsLT_Map" ;
```

**Comment by PTDreamer** [comment]
This is the one I have
[mailmap.txt](https://github.com/d-ronin/dRonin/files/71305/mailmap.txt)

**Comment by PTDreamer** [comment]
New file, probably still needs completing
[mailmap.txt](https://github.com/d-ronin/dRonin/files/71828/mailmap.txt)
Using that file the authors list is as follows:
AJ Christensen aj@junglistheavy.industries
Alessio Morale alessiomorale@gmail.com
andrew andrew
Andrew Thoms openpilot@andrewspizza.net
banig bani.greyling_at_gmail.com
Bertrand Songis bsongis@gmail.com
BrainFPV brainfpv@gmail.com
Brian Mahaffy bmahaffy@marvell.com
Brian Webb Brian.N.Webb@saic.com
Brian Webb webbbn@gmail.com
Carlos Antunes cmantunes@gmail.com
cGiesen info@klick-punkte.info
chris pember chris.pember@gmail.com
cloner timecop@ubuntu.(none)
Corvus Corax corvuscorax@cybertrench.com
cranphin cranphin
cwabbott cwabbott
Daniel Strnad d.strnad@mikroelektronika.cz
Daniel Strnad strnadda@gmail.com
darkz darkz
dasdboot dasdboot@gmail.com
David Ankers david@openpilot.org
David "Buzz" Carlson buzz@chebuzz.com
David David@OpenPilot.org
David Willis dwillis@nildram.co.uk
dgodin dgodin
Dmitry Zaitsev hhrhhr@gmail.com
Dmytro Poplavskiy dima@dima-desktop.(none)
droidicus droidicus@dr.com
dschin dschin
DTF UHF dtfuhf@gmail.com
Dustin Sallings dustin@spy.net
dwobdar dwobdar@gmail.com
edboer 222studio222@gmail.com
Edouard Lafargue edouard@lafargue.name
Edward T. Kaszubski ekaszubski@gmail.com
ephy ephy
erhard erhard
Erik Bernhardson ebernhardson@wikimedia.org
Erik Gustavsson cyrano@area26.se
ernie of infect ernie@web.de
esden esden
filnet filnet@filnet.org
Fotis Georgatos fotis.georgatos@uni.lu
Fotis Georgatos kefalonia@gmail.com
Francesco Nero nerofrancesco@hotmail.com
FredericG FredericG
Fredrik Arvidsson fredrik@arvidssons.org
Frithjof Siebecke frithjofsiebecke@web.de
gedsol gedsol@users.noreply.github.com
gussy gussy
guy guy
henkf henk.freimuth@gmail.com
hernick-qc onolog@gmail.com
Hotlobster hotlobster75@gmail.com
Igor Van Airde igor@public-files.de
Ivan Sevcik raven@localhost.localdomain
James Cotton peabody124@gmail.com
James james@JBook.config
James Whitlock james.whitlock@gmail.com
janfietz janfietz@gmail.com
Jan Hurst jan@janhurst.com
Jason Hitesman jhitesma@gmail.com
jihlein jihlein@hotmail.com
joergrohde joergrohde@t-online.de
John Ihlein jihlein@hotmail.com
jonathan jonathan
Jose Xavier josescxavier@gmail.com
José Xavier josescxavier@gmail.com
julien julien
Kari Hautio khautio@gmail.com
Kenn Sebesta kenn@eissq.com
Kenz Dale kenz@Kenz-Dales-iMac.local
Kevin Vertucio kevin.vertucio@eurorscg.com
KipK hotlobster75@gmail.com
Koen Kooi koen@dominion.thruhere.net
kokomojoe kokomojoe
Lars Johnsen larsjohnsen@gmail.com
Laurent loleaurc@gmail.com
Laurent Ribon laurent.ribon@gmail.com
les les
ligi ligi
lilvinz lilvinz@nscit.com
LinuxJohannes DerTrottel59@gmx.de
LM lm@student.ethz.ch
loris loris
Luke lukev@luke-dv2.(none)
marcus bueschleb ligi@ligi.de
Martin Luessi mluessi@gmail.com
martin martin
Mathieu Rondonneau mathieu.rondonneau@gmail.com
mattl mattl
metropt josescxavier@gmail.com
Michael Corcoran tracer@outlook.co.nz
Michael Hope michaelh@juju.net.nz
Michael Lyle mlyle@lyle.org
Michael Rumpler mike@apferl.(none)
Michael Schulz coding@calihem.de
Mikael Blomqvist fnurgel@gmail.com
Mike LaBranche mdlabranche@gmail.com
Mike Smith DrZiplok@me.com
Mischa Aster Alff mischa.alff@gmail.com
Montspy Montspy@gmail.com
Moritz Ulrich moritz@tarn-vedra.de
m_thread fredrik@arvidssons.org
muralha muralha
Murilo Pontes murilo.pontes@gmail.com
naiiawah naiiawah@blackbird-av.com
Nathan Feldkamp nathanf7@ksu.edu
Nickolay mykola.gerasymenko@frogdesign.com
nickolay nickolay
Nuno Guedes muralha@gmail.com
Oleg Semyonov os@openpilot.org
Oscar Andreasson oandreasson@gmail.com
Patrick Huebner phuebner86@gmail.com
patrick patrick
Paul McMillan paul.mcmillan@nebula.com
pedro pedro
pete pete
PeterG peter@pyne.se
Peter Gunnarsson peter@pyne.se
Pip cmoss296@blueyonder.co.uk
PT_Dreamer josemanuelbarros@gmail.com
rdnzl rdnzl@flashfingaz.de
Richard Flay (Hyper) hyperreality.au+openpilot@gmail.com
richard richard
Ryan Hunter rghunter@bu.edu
Sambas samik.korhonen@gmail.com
scenkov stefan.cenkov@gmail.com
Scott Parker carboninfusion@gmail.com
scott scott
Sergiy Anikeyev e3737c@gmail.com
sirPerna sir.perna@gmail.com
sparkie79 sparkie79@gmail.com
Stacey Sheldon stac@solidgoldbomb.org
taulabs taulabs@taulabs.(none)
taumcg tom@tommcg.com
thenobody thenobody
Thomas Greer UKTamo@gmail.com
Tim G tim@Timothys-MacBook-Pro.local
tracernz mrc93@uclive.ac.nz
Trex4Git trex_dev@gmx.net
ufoDziner wes@vvarner.net
unknown Connor@.(none)
unknown David@D620.(none)
unknown droidicus@dr.com
unknown kotsos@flightroom.(none)
unknown mykola.gerasymenko@.synapse.com
unknown Werner@U100.(none)
VArcht admin@varcht.net
vassilis vassilis
vassilis vassilis@vrhome.net
Werner Backes op-dev@bit-1.de
Ye Wang wangyeee@gmail.com
zillatrooper zillatrooper@gmail.com

**Comment by PTDreamer** [comment]
About the script the metric used is debatable regarding LOC vs Commits, the later is used on the script but it ultimately depends on the git fu style. Such a metric may motivate proper atomic commits but can also motivate unnecessary commits just to climb on the rates. 
About the value decay based on the age of the commit I completely disagree, that is like saying that the contribution of the guys which designed the initial system architecture is worth nothing today, and a simple clean up commit today will worth more. Things like UAV Objects were coded long ago but they are still used today so the people that wrote that code should undoubtedly have a place on the credits.

**Comment by mlyle** [comment]
@PTDreamer Yah, it's all a bogus metric no matter what.  Lines of code either measures hardware way too high or not at all.  I don't think the ranking is that important.

Also, there are lots of bits of old architecture that will be going away, probably.  e.g. the bits of the event system I ripped out.  I measured that the error coding we do on pipxtreme / sparky2 rescues basically no frames, because if there's significant noise the RFM chip never hears the prelude.

Should we just put it in alphabetical order?

**Comment by PTDreamer** [comment]
> @PTDreamer Yah, it's all a bogus metric no matter what. Lines of code either measures hardware way too high or not at all. I don't think the ranking is that important.
> 
> Also, there are lots of bits of old architecture that will be going away, probably. e.g. the bits of the event system I ripped out. I measured that the error coding we do on pipxtreme / sparky2 rescues basically no frames, because if there's significant noise the RFM chip never hears the prelude.
> 
> Should we just put it in alphabetical order?

I honestly don't know...maybe the output from the script on this PR and then an all time contributors list? I'll change my nick to 000AAAPT_Dreamer in the meantime though :)

**Comment by mluessi** [comment]
I think we should use alphabetic ordering and change the wording in the dialog so it doesn't refer to the authors listed as key people.

Alternatively, we could have two lists: 1) people who contributed to the current release (or last 6 months, or smth) (sorted alphabetically) 2) all authors (also sorted alphabetically). This would allow us to show who is actively involved in the project.

**Comment by mlyle** [comment]
Rebased and slightly updated.

**Comment by tracernz** [comment]
My proposal:

```
Active contributors:
[list of names from git shortlog -s <last release tag>]

Previous contributors:
[list of names from git shortlog -s]
```

shortlog sorts name alphabetically by default which I think is fine.

**Comment by tracernz** [comment]
We should really take care of this before Artifice.

**Comment by mlyle** [comment]
Superseded #1557

**Pull request closed without merging**
