### PR TITLE
GCS: Fix up use of deprecated functions, enable warnings

### PR DESCRIPTION
**Pull request by tracernz**
Use of deprecated Qt stuff will generate warnings (which will fail CI, and Linux builds) from now on.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Blows up on Windows

```
C:\Jenkins\workspace\dronin@2\Nodes\winx86-neo\ground\gcs\src\libs\qwt\src\qwt_thermo.cpp(563): error C2039: 'greater': is not a member of 'std'
C:\Qt5.8\5.8\msvc2015\include\QtCore/qsharedpointer_impl.h(886): note: see declaration of 'std'
C:\Jenkins\workspace\dronin@2\Nodes\winx86-neo\ground\gcs\src\libs\qwt\src\qwt_thermo.cpp(563): error C2065: 'greater': undeclared identifier
C:\Jenkins\workspace\dronin@2\Nodes\winx86-neo\ground\gcs\src\libs\qwt\src\qwt_thermo.cpp(563): error C2062: type 'double' unexpected
```

**Comment by tracernz** [comment]
Yay :D

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Nice :D

**Pull request merged**
