### PR TITLE
Fix Linux packaging 

### PR DESCRIPTION
**Pull request by PTDreamer**
[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/253)

### CODE REVIEW

**Comment by mlyle** [comment]
Expected to fix #216

**Comment by tracernz** [comment]
Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[branding/linux_packaging.dict, line 8 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/253#-K5O5GIXg776zRFlEXrN:-K5O5GIXg776zRFlEXrO:1818841972) ([raw file](https://github.com/d-ronin/dronin/blob/fbaa31ec24d009749201dbc418eea49c14bbf3b5/branding/linux_packaging.dict#L8)):*
That guy. :-P

---

*[branding/linux_packaging.dict, line 10 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/253#-K5O5IHY2rALPfuru5kY:-K5O5IHY2rALPfuru5kZ:-280810172) ([raw file](https://github.com/d-ronin/dronin/blob/fbaa31ec24d009749201dbc418eea49c14bbf3b5/branding/linux_packaging.dict#L10)):*
Should have newline at end.

---

*[ground/gcs/src/plugins/coreplugin/iboardtype.h, line 74 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/253#-K5O5thAglwlPxwNbPy3:-K5O5thAglwlPxwNbPy4:-1444877255) ([raw file](https://github.com/d-ronin/dronin/blob/fbaa31ec24d009749201dbc418eea49c14bbf3b5/ground/gcs/src/plugins/coreplugin/iboardtype.h#L74)):*
This will clash with #247, your solution is nicer.

---

*[ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp, line 202 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/253#-K5O66xo5KmB4L9TWzoR:-K5O66xo5KmB4L9TWzoS:1741769274) ([raw file](https://github.com/d-ronin/dronin/blob/fbaa31ec24d009749201dbc418eea49c14bbf3b5/ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp#L202)):*
Again will clash with #247. Maybe just revert #247.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/253)*

**Comment by mlyle** [comment]
After the couple small changes mentioned, will merge #258 and then this.

**Comment by PTDreamer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[branding/linux_packaging.dict, line 8 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/253#-K5O5GIXg776zRFlEXrN:-K5RggNkg2o4kf3x3onz:521977234) ([raw file](https://github.com/d-ronin/dronin/blob/fbaa31ec24d009749201dbc418eea49c14bbf3b5/branding/linux_packaging.dict#L8)):*
Does the project have an email? This guy is spammed for sure

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/253)*

**Comment by mlyle** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[branding/linux_packaging.dict, line 8 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/253#-K5O5GIXg776zRFlEXrN:-K5RjqdbaSvzs6ku10tN:-1213786981) ([raw file](https://github.com/d-ronin/dronin/blob/fbaa31ec24d009749201dbc418eea49c14bbf3b5/branding/linux_packaging.dict#L8)):*
It doesn't, but let's put dronin@dronin.org for now and call it good.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/253)*

**Comment by PTDreamer** [comment]
Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[branding/linux_packaging.dict, line 8 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/253#-K5O5GIXg776zRFlEXrN:-K5RyAcM9GszYkQRcz6B:-499146009) ([raw file](https://github.com/d-ronin/dronin/blob/fbaa31ec24d009749201dbc418eea49c14bbf3b5/branding/linux_packaging.dict#L8)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/253)*

**Comment by mlyle** [comment]
:lgtm:

---

Review status: 26 of 27 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/253#-:-K5SM-OiQfIU62AokFFY:1417088721)*

**Pull request merged**
