### PR TITLE
Mass-fix casts throughout the GCS code base

### PR DESCRIPTION
**Pull request by mlyle**
Many fewer C style casts in GCS now.

### CODE REVIEW

**Comment by tracernz** [comment]
The standard is no space around casts. Can you pretty-please fix?
https://wiki.qt.io/Qt_Coding_Style
```c++
 // Wrong
 char* blockOfMemory = (char* ) malloc(data.size());

 // Correct
 char *blockOfMemory = reinterpret_cast<char *>(malloc(data.size()));
```

**Comment by mlyle** [comment]
Ugh.  Maybe another pass of clang-format? :P

**Comment by mlyle** [comment]
Did a pass of clang-format just on the files affected by this PR.  Worth reading that commit's commitmessage.

**Review by tracernz — APPROVED** [review]
Looks good. Thanks for the extras, :+1: Note that qobject_cast is a bit faster than dynamic_cast for QObjects, but I'm fine with dynamic_cast.

**Pull request merged**
