### PR TITLE
pios_thread: correct chibios time math

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by tracernz** [comment]
Looks good on first inspection.

**Comment by tracernz** [comment]
Sim doesn't watchdog now. but it is still partially broken. I can connect with GCS briefly (a few seconds) repeatedly but the data stops flowing and the connection breaks each time. The task responsible for PIOS_LED stops.

**Comment by mlyle** [comment]
So, I made a subtle mistake when I rushed this together.  This is corrected, which could explain the problem, but may not.  Will be able to try it after my run today.

**Comment by mlyle** [comment]
I have a simulator uptime for 3 hours now that I"m able to connect to with GCS and fly (have not been doing stuff with it the whole time, though.

**Comment by mlyle** [comment]
https://www.youtube.com/watch?v=eaDUa1vdY2k   revo

**Comment by pug398** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
At some point someone's gonna need to be brave and hover through the 4294s barrier.

**Comment by tracernz** [comment]
Got over 6000 s on my Sparky1 and it seems to be doing everything correctly, but can't fly due to darkness outside. Seeing commands go to actuators when armed with GCSReciever and when I roll/pitch/yaw the board with my hand.

**Comment by tracernz** [comment]
Over 9000, we're done.
screenshot from 2016-05-03 20-13-52

**Comment by pug398** [comment]
My boards passed the bench test so next thing is flying it around on various targets. Kudos to you for finding the bug fairly quick. I thought it would take quite some time poking around.

**Comment by mlyle** [comment]
@pug398 ;) It was actually mostly @tracernz who found it

**Comment by tracernz** [comment]
:P
screenshot from 2016-05-04 05-54-22

**Comment by pug398** [comment]
Nice! Not sure I can stay awake that long though :D

**Comment by pug398** [comment]
So far running the gamut I have CC3D and Sparky1 flying basic flight. Revolution flying autonomous flight and none showing any problems as far as I can tell. Quanton and Sparky2 up next.

**Comment by tracernz** [comment]
Note: CC3D doesn't suffer this issue as it's still on FreeRTOS. This affects targets on ChibiOS which are all F3 and F4 targets. :)

**Comment by mlyle** [comment]
Also I think it'll be all-or-nothing-- this shouldn't vary by target.

The ... real test, that I don't have patience for at the moment, is to get to ~4250s of uptime, arm, and spin motors through 4294s looking for anomalies.  Then to try the same thing--with props-- to hover through the 4294s boundary.

**Comment by pug398** [comment]
Working towards that goal. As soon as I get sparky2 up and running I will let it run armed up to just before the limit then PH through it. It is a lightweight build and a failure, though not expected, should cause minimal damage.

**Comment by mlyle** [comment]
OK.  I'm willing to do it too; I'm just slow because I've just had a problem with having a couple of contiguous hours for test lately.

**Comment by pug398** [comment]
ph_time

Sparky2 did fine flying through the barrier. When battery alarm went off I triggered RTH just to get a test in on newer build and that performed well also.

**Comment by mlyle** [comment]
holy crap, thanks much @Pug398

**Pull request merged**
