### PR TITLE
transmitter_control: require minimum input ranges to be configured

### LINKED ISSUE #362: Engines may arm at startup with invalid RC input settings
As shown by this configuration file with invalid RC input settings https://gist.github.com/hernick-qc/f8da724a66874ba9d7b1

Some invalid RC input configurations result in uncommanded arming at startup. If autotune is also configured, autotuning may also begin automatically as soon as the battery is plugged in.

### PR DESCRIPTION
**Pull request by mlyle**
This prevents us from acting on input when there's basically no
resolution and it's all dominated by jitter.

Fixes #362 

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/364)

### CODE REVIEW

**Comment by dustin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[flight/Modules/ManualControl/transmitter_control.c, line 102 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/364#-K6obz52o38hOZjVV64C:-K6obz52o38hOZjVV64D:1089487150) ([raw file](https://github.com/d-ronin/dronin/blob/77d7dc6596111cfe3e704983836cb8208c6fe388/flight/Modules/ManualControl/transmitter_control.c#L102)):*
I'd really like us to document things in the header/declaration areas.  I've figured out what a lot of this does from the code, but I don't quite understand 'offset' here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/364)*

**Comment by mlyle** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[flight/Modules/ManualControl/transmitter_control.c, line 102 \[r1\]](https://reviewable.io:443/reviews/d-ronin/dronin/364#-K6obz52o38hOZjVV64C:-K6orpmOAbhqEafEyQz-:-2004292991) ([raw file](https://github.com/d-ronin/dronin/blob/77d7dc6596111cfe3e704983836cb8208c6fe388/flight/Modules/ManualControl/transmitter_control.c#L102)):*
Offset here is the "maximum amount" out of range a channel may be and we still consider it valid.  So if range is 1000-2000, we treat 750 to 1000 as "-100%" and 2000 to 2250 as "+100%".   2251 or 749 would be invalid input on the channel.

I agree we need more documentation.  I'm planning to add a bit more to the things i've changed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/364)*

**Comment by mlyle** [comment]
Added some documentation and confirmed that this works as intended.

**Comment by droidicus** [comment]
Tested on Sparky2 and Win10.

When configuration was invalid (minimum range violated) the system went into failsafe. The "RC Input" module went into warning state with the following status: "Error Code: No RX. No RC receiver detected, .The system has been put into failsafe mode".

Correcting the settings, and putting the input ranges/neutral position back to valid settings cleared the error, and brought the system out of failsafe, and back to a flyable configuration.

**Comment by dustin** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/364#-:-K79CwUAxsZIxcJpgB8L:1417088721)*

**Comment by dustin** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/364)*

**Pull request merged**
