### PR TITLE
Moved the break within the #ifdef section 

### PR DESCRIPTION
**Pull request by yamahabest**
It doesn't make sense to be after the #endif, because if one would
disable the PIOS_INCLUDE_MS5611 define, there would be a single break.

### CODE REVIEW

**Comment by tracernz** [comment]
It does make sense and would stop the board from crashing...?

**Comment by mlyle** [comment]
Would need to get teh case outside first.

@yamahabest  --- any chance that this can be cleaned up-- perhaps with a rebase -- to be a single commit instead of 20 merge commits plus one code change?

**Comment by yamahabest** [comment]
Let me check, I am using the GitHub client. Using the sync button to get the changes from dRonin/next to my next, and then making a branch of my next, gets me all this stuff. Starting google.

**Comment by tracernz** [comment]
Ah, now on desktop, I see where the ifdef was. I assumed it was inside the case, which would stop the crash and hopefully trigger a sensors alarm instead (although I don't recall the specifics of how we decide if we _should_ be getting updates from a particular sensor).

**Comment by yamahabest** [comment]
Damn.. what a mess.. This is going the wrong way.. Trying more..

**Comment by yamahabest** [comment]
Shhh... I don't know why it closed this one. Opened a new one: #1661. Looks better now.

**Pull request closed without merging**
