### PR TITLE
gcs,app: Wrangle AVs.

### PR DESCRIPTION
**Pull request by glowtape**
Attempt No. God-Knows-How-Much.

### CODE REVIEW

**Comment by glowtape** [comment]
Jenkins, build this please.

**Comment by glowtape** [comment]
Jenkins, build this, please.

**Comment by glowtape** [comment]
Build this please

**Comment by glowtape** [comment]
Jenkins, build artifacts please.

**Comment by glowtape** [comment]
Down to 2/66 on drgcs.exe with that commit above.

https://www.virustotal.com/#/file/189f679e4a2532e9efe4b1d5ef10447ad0a173974c763cd5ecd7f02d4802720a

Trying with LTCG now.

**Comment by glowtape** [comment]
Jenkins, build artifacts please.

**Comment by tracernz** [comment]
Does the application even have much to optimise with LTO? I think pretty much everything it uses is dynamically linked except breakpad exception handler?

**Comment by tracernz** [comment]
P.S. `CONFIG += link_ltcg`.

**Comment by glowtape** [comment]
IDK, over here it makes a difference for the better, but I think I'm on a slightly newer build of VS2015. On the Jenkins build, it gets worse for whatever reason, so LTCG is useless currently.

Here's the results for the installer package with just ~~a02ad31~~ 8db264b (shit got renamed)

https://www.virustotal.com/#/url/21c97626860e95435d49751eac236f79403d4746f8cc5277d3f04b32053e5fc3

Also clean(ish). Some report unrated, whatever that means, but no red.

I suppose with the two remaining warnings being labelled "not-a-virus", I suppose we're kinda clear for now.

--edit: Removed the LTCG thing.

**Pull request merged**
