### PR TITLE
sparky: remove unattainable rates

### PR DESCRIPTION
**Pull request by mlyle**
I thought we'd knocked all these down.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/764)

### CODE REVIEW

**Comment by fujin** [comment]
lgtm :+1:

**Comment by fujin** [comment]
refs #763 (kind of)

**Comment by tracernz** [comment]
Didn't look at jenkins but these are used in pios_board_init so I'm guessing that's why.

**Comment by mlyle** [comment]
Oh yah :P

**Comment by pug398** [comment]
@mlyle Is there a problem with using 666hz? I thought 666hz worked but 1000 slightly overloaded cpu.

**Comment by mlyle** [comment]
With 188Hz LPF, the only attainable rates are factors of 1000Hz; if you ask for 666Hz you silently get 500Hz.

With 256Hz LPF, you can get 8000 / 12 = 666Hz, but the aliasing/noise characteristics are super bad.

**Comment by pug398** [comment]
Ok. So 500 is good and hopefully 1000 will improve with optimization. Thanks for clarifying.

**Pull request merged**
