### PR TITLE
GCS: Module tab cleanup

### PR DESCRIPTION
**Pull request by tracernz**
- Clarify auto/manual modules much more
- Move UAVO->Widget relations to UI file
- ConfigTaskWidget (UAVO->widget relations) now supports arbitrary mapping of checkbox state to enum options
- Move GPS to own tab and add constellations + auto-setup
- General improvements

screenshot from 2016-05-15 18-18-58

### CODE REVIEW

**Comment by tracernz** [comment]
Ahh, there is a mixture of True/False and TRUE/FALSE throughout all the UAVOs... sigh.. :(

**Comment by tracernz** [comment]
Changed TaskInfo to TRUE/FALSE since there are a lot of settings objects using uppercase.

**Comment by tracernz** [comment]
Added a logging tab, should be handy with OpenLager coming soon. Should probably extend Logging so the custom option can be customised.

screenshot from 2016-05-15 20-21-53

**Comment by mlyle** [comment]
Beautiful.

**Pull request merged**
