### PR TITLE
gcs: channel test: only prevent on actuator ERROR

### PR DESCRIPTION
**Pull request by mlyle**
(not warning).

Prevents clipmgmt from preventing testing

relates #699, but should happen anyways.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/721)

### CODE REVIEW

**Comment by fujin** [comment]
lgtm :+1:

**Comment by tracernz** [comment]
Should probably stop on critical too, no?

**Comment by mlyle** [comment]
Sigh, you're right.  Though... I don't really see much point in this test/alarm check.

**Comment by tracernz** [comment]
:lgtm: when Jenkins is done.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/721#-:-KBkXnaUtWhUWacIZUJN:-1201941801)_

**Pull request merged**
