### PR TITLE
GCS: Use Qt 5.8.0

### PR DESCRIPTION
**Pull request by tracernz**
Waiting on official 5.8.0 release (currently expected next week). I have spun a Windows 5.8.0-rc build and found no issues in a basic smoke test involving connecting + doing basic configuration.

@mlyle This relaxes the Qt version requirements slightly, so the Makefile won't blow up when Qt SDK isn't found unless you're building GCS. It makes uavogen stricter in that it will only accept Qt versions with the same major and minor version, and same or newer patch release. That means I can use a PPA (e.g. https://launchpad.net/~beineri) that only maintains the latest patch release for each version for the doc builder which makes it feasible to use Travis-CI rather than having to maintain Jenkins etc. on my owm server. :+1: Also means you can build firmware a little easier since it only needs uavogen. What do you think?

Supersedes #1481.

Blockers:
- [x] Qt official release (~~~[expected 17/1/17](http://lists.qt-project.org/pipermail/releasing/2017-January/004415.html)~~~ [expected 23/1/17](http://lists.qt-project.org/pipermail/releasing/2017-January/004419.html)).
- [x] Breakpad source needs upgraded and then warnings fixed to compile with C++11, or alternately link with a static lib (much better idea anyway).
- [x] Qwt source needs fixed (deprecated QStyle* deps).
- [x] Manhattan style needs fixed/dropped (deprecated QStyle* deps), was fixed in TauLabs/TauLabs#1291 but it was rejected. Necessary for widget editing mode.
- [x] Intermittent (seen it once on my machine, every build on Travis-CI) issue with pulseaudio failing to be found by linker. It's pulled in by QtMultimedia in Notify plugin. Looks like an upstream bug.
- [x] ```/Users/mike/dev/dronin/ground/gcs/src/plugins/config/textbubbleslider.h:32:10: fatal error: 
      'QtUiPlugin/QDesignerExportWidget' file not found
#include <QtUiPlugin/QDesignerExportWidget>```
- [x] ?? (haven't got a working ~~~Linux or~~~ macOS build yet)
- [ ] Need to run `qbs setup-toolchains --detect` on Windows somehow (since it currently doesn't use our Qt SDK installer target :(
- [ ] Possible: Clean up and finish Windows Qt auto-install script (uses online installer, auto-selects Qt 5.8/MSVC __AND__ MinGW)
- [ ] Possible: come up with an alternate way to bootstrap Windows build environment. Maybe a shell script that runs under default msys Git shell, runs Qt installer, and sets up bash profile?
- [ ] UI issues?

### CODE REVIEW

**Comment by tracernz** [comment]
And already fixed a typo, s/PATH/PATCH/ :stuck_out_tongue:

**Comment by tracernz** [comment]
We fail on Linux due to another old dep (Qwt.. GLC_Lib... ugggh):
```
compiling /home/mike/dev/dronin2/ground/gcs/src/libs/qwt/src/qwt_raster_data.cpp
/home/mike/dev/dronin2/ground/gcs/src/libs/qwt/src/qwt_plot_canvas.cpp: In member function ‘virtual void QwtPlotCanvas::drawBorder(QPainter*)’:
/home/mike/dev/dronin2/ground/gcs/src/libs/qwt/src/qwt_plot_canvas.cpp:940:29: error: ‘QStyleOptionFrameV3’ is deprecated [-Werror=deprecated-declarations]
         QStyleOptionFrameV3 opt;
                             ^
In file included from /home/mike/dev/dronin2/ground/gcs/src/libs/qwt/src/qwt_plot_canvas.cpp:17:0:
/home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qstyleoption.h:142:60: note: declared here
 typedef Q_DECL_DEPRECATED QStyleOptionFrame QStyleOptionFrameV3;
                                                            ^
cc1plus: all warnings being treated as errors
Makefile:10386: recipe for target '.obj/debug-shared/qwt_plot_canvas.o' failed
```

**Comment by tracernz** [comment]
Qt installer is now headless. 5.8.0-rc_605 version of this branch on Travis-CI: https://travis-ci.org/tracernz/dronin/builds/191918549

**Comment by mlyle** [comment]
Holy crap re: headless :D  

I like the rest of stuff.  I think the uavobjectgenerator stuff is debatable, but the only real solution is to eliminate the qt dependency.

**Comment by tracernz** [comment]
Updated OP with list of blockers thus far.

**Comment by tracernz** [comment]
With breakpad statically linked (we already build it with make breakpad_install so I just used that... will need to do something for Windows), I'm down to these:
```
Project MESSAGE: QMAKE_CXX = /usr/bin/ccache g++
Project MESSAGE: QMAKE_CC = /usr/bin/ccache gcc
/home/mike/dev/dronin2/ground/gcs/src/libs/qwt/src/qwt_plot_canvas.cpp: In member function ‘virtual void QwtPlotCanvas::drawBorder(QPainter*)’:
/home/mike/dev/dronin2/ground/gcs/src/libs/qwt/src/qwt_plot_canvas.cpp:940:29: warning: ‘QStyleOptionFrameV3’ is deprecated [-Wdeprecated-declarations]
         QStyleOptionFrameV3 opt;
                             ^
In file included from /home/mike/dev/dronin2/ground/gcs/src/libs/qwt/src/qwt_plot_canvas.cpp:17:0:
/home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qstyleoption.h:142:60: note: declared here
 typedef Q_DECL_DEPRECATED QStyleOptionFrame QStyleOptionFrameV3;
                                                            ^
/home/mike/dev/dronin2/ground/gcs/src/plugins/coreplugin/manhattanstyle.cpp: In member function ‘virtual void ManhattanStyle::drawControl(QStyle::ControlElement, const QStyleOption*, QPainter*, const QWidget*) const’:
/home/mike/dev/dronin2/ground/gcs/src/plugins/coreplugin/manhattanstyle.cpp:609:38: warning: ‘QStyleOptionTabV3’ is deprecated [-Wdeprecated-declarations]
         if (const QStyleOptionTabV3 *tab = qstyleoption_cast<const QStyleOptionTabV3 *>(option)) {
                                      ^
In file included from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h:45:0,
                 from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qcombobox.h:45,
                 from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/QComboBox:1,
                 from /home/mike/dev/dronin2/ground/gcs/src/plugins/coreplugin/manhattanstyle.cpp:40:
/home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qstyleoption.h:284:58: note: declared here
 typedef Q_DECL_DEPRECATED QStyleOptionTab QStyleOptionTabV3;
                                                          ^
/home/mike/dev/dronin2/ground/gcs/src/plugins/coreplugin/manhattanstyle.cpp:609:86: warning: ‘QStyleOptionTabV3’ is deprecated [-Wdeprecated-declarations]
         if (const QStyleOptionTabV3 *tab = qstyleoption_cast<const QStyleOptionTabV3 *>(option)) {
                                                                                      ^
In file included from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h:45:0,
                 from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qcombobox.h:45,
                 from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/QComboBox:1,
                 from /home/mike/dev/dronin2/ground/gcs/src/plugins/coreplugin/manhattanstyle.cpp:40:
/home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qstyleoption.h:284:58: note: declared here
 typedef Q_DECL_DEPRECATED QStyleOptionTab QStyleOptionTabV3;
                                                          ^
/home/mike/dev/dronin2/ground/gcs/src/plugins/coreplugin/manhattanstyle.cpp:610:31: warning: ‘QStyleOptionTabV3’ is deprecated [-Wdeprecated-declarations]
             QStyleOptionTabV3 adjustedTab = *tab;
                               ^
In file included from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h:45:0,
                 from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qcombobox.h:45,
                 from /home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/QComboBox:1,
                 from /home/mike/dev/dronin2/ground/gcs/src/plugins/coreplugin/manhattanstyle.cpp:40:
/home/mike/dev/dronin2/tools/Qt5.8.0-rc/5.8/gcc_64/include/QtWidgets/qstyleoption.h:284:58: note: declared here
 typedef Q_DECL_DEPRECATED QStyleOptionTab QStyleOptionTabV3;
                                                          ^
/home/mike/dev/dronin2/ground/gcs/src/plugins/boards_brainfpv/brainre1configuration.ui: Warning: Z-order assignment: '' is not a valid widget.
/home/mike/dev/dronin2/ground/gcs/src/plugins/boards_brainfpv/brainre1configuration.ui: Warning: Z-order assignment: '' is not a valid widget.
```

**Comment by mlyle** [comment]
So, I've picked this up on my Linux machines.

1. The quasi-headless installer works great!  URLs are correct, etc.
2. Build blows up on manhattan style, i think as expected.
3. Lyle.org blows up from Make 3 not having the 'undefine' keyword.

**Comment by tracernz** [comment]
Updated with latest progress. Just a few small issues with setup of Windows environment remaining AFAIK. Have working builds on all 3 platforms. Have not checked for UI issues very deeply (@mlyle noted some earlier). See OP for checklist of known issues.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
Current status:  Linux builder has entire procedure done

Mac builder has qt 5.8.0 but old breakpad still.

Nothing done to windows.

Firing a couple builds to see where we are-- this branch and vanilla.

Jenkins, build artifacts please

**Comment by mlyle** [comment]
Old breakpad on mac because:

```
  BUILDING     https://github.com/d-ronin/breakpad.git @ 20170129
ERROR: Unknown or empty profile 'clang'.
ERROR: Unknown or empty profile 'clang'.
```

**Comment by mlyle** [comment]
Was necessary to run`"/Users/build/dRonin/tools/Qt5.8.0/Qt Creator.app/Contents/MacOS/qbs" setup-toolchains --detect`
 by hand on mac.    Then the first build of breakpad didn't work, but the second identical one did? heh.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
On windows, with the dronin bash_profile activated, you should be able to run `qbs setup-toolchains --detect` manually (bash_profile adds QtCreator/bin to PATH so qbs should be available). Then `make breakpad_install`, and everything should then work. This is the part I need to work on to make it easier/automatic. :D

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Time to (softly) commit to this path, since the builders are now set up that way.

**Pull request merged**
