### PR TITLE
gcs: collapse buttons together, improve workflow in upgrade

### PR DESCRIPTION
**Pull request by mlyle**
In preparation for deeper work.  Speedy review and merge appreciated.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/769)

### CODE REVIEW

**Comment by tracernz** [comment]
Is there a good reason for separate no and ignore buttons? I like the idea of ignoring for the rest of the session when the no or ignore (keep whichever you think is best and ditch the other IMO) is clicked. Simplifying the options to just two seems better if we can.

**Comment by mlyle** [comment]
OK.  It's kinda been nice in testing, but you're right that this is an unnecessary option.

**Comment by mlyle** [comment]
(done, but unbuilt)

**Comment by tracernz** [comment]
Tested on CC3D, seems good.

**Pull request merged**
