### PR TITLE
Auto-enable modules based on port configuration

### PR DESCRIPTION
**Pull request by tracernz**
Seems to work well. Can't do S.PORT because there are two different modules for that??? I'm unfamiliar with FrSky stuff so don't know why we need two separate modules or how to decide which one to enable if possible, any suggestions welcomed. Also, cleaned up the FrSky config stuff to not need an ugly define added to lots of files.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/787)

### CODE REVIEW

**Comment by mlyle** [comment]
One is sport, one is sensor hub-- so there's separate types and separate modules (you could even run them both at once).

**Comment by tracernz** [comment]
On CC3D, code size without:
- Code size: 110168
- Heap remaining: 2532

With:
- Code size: 110144
- Heap remaining: 2532

> One is sport, one is sensor hub-- so there's separate types and separate modules (you could even run them both at once).

No, I've done sensor hub. But there are two S.PORT modules, UAVOFrSKYSPortBridge and UAVOTaranis.

**Comment by mlyle** [comment]
Oh, sorry-- UAVOTaranis is the pipxtreme one for ground-side use.

**Comment by tracernz** [comment]
S.PORT done. One small problem with this, it uses TaskInfo to indicate which modules are enabled on the modules tab, but F1 doesn't have TaskInfo... :/

**Comment by tracernz** [comment]
Found a mistake in the original commit (had altered the S.PORT checkbox rather than MSP). Fixed the mistake, and added a commit to clear the checkboxes upon board connection. This stops the state being retained from the last connected board when the TaskInfo UAVO is not present on the new board (i.e. F1 boards).

**Comment by tracernz** [comment]
jenkins, build artifacts please

Need some test on this.

**Comment by mlyle** [comment]
Passes smoke test.  Need more detailed test on this, but we'll take it together for the release.

**Pull request merged**
