### PR TITLE
Eliminate all warnings seen in CI

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by mlyle** [comment]
This fixes #783 as seen in CI, but from discussion from @tracernz I think this is not all needed to close that bug.

**Review by tracernz — APPROVED** [review]
Thank you 😀. I think there are still some other things that clang picks up (useless compares etc.)?

**Comment by tracernz** [comment]
What version of osx + xcode is CI running?

**Comment by mlyle** [comment]
<pre>builds-Mac-mini:~ build$ uname -a
Darwin builds-Mac-mini.lan 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
builds-Mac-mini:~ build$ clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
</pre>

**Comment by tracernz** [comment]
That would likely be the difference then:
```
$ uname -a
Darwin macbook.bertie.nz 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
$ clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Pull request merged**
