### PR TITLE
Remove uavtalkrelay plugin

### PR DESCRIPTION
**Pull request by PTDreamer**
I wrote this long time ago for a specific user. I doubt anyone else has ever used this or even knows what is does.

### CODE REVIEW

**Comment by mlyle** [comment]
Does the wireshark stuff require this to be useful?

**Comment by PTDreamer** [comment]
No not at all this was supposed to be used in an operator and supervisor
setup where you handover the control of the set of uav objects you select
to another instance of the gcs connected through an ip network.

Em 06/12/2016 16:39, "Michael Lyle" <notifications@github.com> escreveu:

**Comment by mlyle** [comment]
I see, the UDP mirror stuff is separate!   Awesome, I love deleted code :)

**Comment by mlyle** [comment]
jenkins, build artifacts please

(Just to test it builds OK on all platforms)

**Comment by mlyle** [comment]
@PTDreamer Thanks much :)

**Pull request merged**
