### PR TITLE
actuator: don't LPS forever in failsafe

### LINKED ISSUE #724: Report: Hangtime stays engaged in failsafe
The hangtime is correct for low throttle while valid signal but failsafe kicks in LPS for ~25 seconds when hangtime is set to 2 seconds. This may be expected behavior just not what I was expecting :)

### PR DESCRIPTION
**Pull request by mlyle**
fixes #724

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/726)

### CODE REVIEW

**Comment by fujin** [comment]
Gosh darn off by one. :+1:

**Comment by mlyle** [comment]
Off by .00000000000000000000000000000000000034 here. ;)

The main problem is the 0 value is now used during failsafe.

**Comment by pug398** [comment]
Just for info with LPS+Failsafe, failsafe would kick in when ArmedTimeout expired so it was somewhat adjustable after all :)

**Comment by tracernz** [comment]
Discussed on IRC, seems reasonable. We can consider a different value for failsafe in future but that's outside the scope of this PR.

**Pull request merged**
