### PR TITLE
flight: naze32: include buffer sizes for things

### PR DESCRIPTION
**Pull request by mlyle**
This was on CC3D but not on Naze32; probably was "lost" during
introduction of PIOS_HAL to naze32 target.

Also remove a duplicate HPWM define.

Likely frees noticeable memory on naze32.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/766)

### CODE REVIEW

**Comment by mlyle** [comment]
Does this fix #761?

**Comment by mlyle** [comment]
(Also, I noticed-- WDG is turned off on Naze32.)

**Comment by tracernz** [comment]
> probably was "lost" during introduction of PIOS_HAL to naze32 target.

Looks like it never had them.

**Comment by mlyle** [comment]
Had at least the telem ones in pios_board.c, possibly others

**Comment by tracernz** [comment]
Ah, of course. I was only looking in pios_config.h.

**Comment by dustin** [comment]
This appears to fix #761 
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/766#-:-KCEETu5Y1QpSaH7N6Ef:-1117398134)_

**Pull request merged**
