### PR TITLE
GCS:Config: Warn if hangtime is used without switch arming

### LINKED ISSUE #735: GCS should strongly urge user to use switch arming with hangtime

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #735.
screenshot from 2016-03-14 19 24 42

---

This change is [Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/799)

### CODE REVIEW

**Comment by mlyle** [comment]
please remove the space on "Hang Time" so it's our special compound word ;)  yay marketing

**Comment by mlyle** [comment]
Code looks good to me.

**Comment by tracernz** [comment]
> please remove the space on "Hang Time" so it's our special compound word ;) yay marketing

Done.

**Comment by mlyle** [comment]
Woops ;)

```
/var/lib/jenkins/jobs/dron/workspace/Nodes/master/ground/gcs/src/plugins/config/configstabilizationwidget.cpp:67:27: error: cannot convert ‘UAVObject*’ to ‘UAVObjectField*’ in assignment
     manualControlSettings = getObjectManager()->getObject(ManualControlSettings::NAME);
```

**Comment by tracernz** [comment]
Yay! :-P Will fix up when I get a chance.

**Comment by mluessi** [comment]
Nice :). How about also adding a warning to the tab where the arming mode is configured? It's possible that a user sets up HangTime&#x2122; with switch arming configured and then later changes the arming mode.

**Comment by tracernz** [comment]
@mluessi Probably a good idea to duplicate it there. I'll wait until I get home tonight to fix this because I want to fix the commit and force-push so that it's atomic.

**Comment by tracernz** [comment]
Shows on arming config page now too.

**Pull request merged**
