### PR TITLE
Allow selection of thrust mode within stabilization bank

### PR DESCRIPTION
**Pull request by mlyle**
Builds upon #2090 to allow configuration of thrust modes within a stabilization bank.

### CODE REVIEW

**Comment by mlyle** [comment]
screenshot from 2018-03-08 15-02-13

**Comment by ufoDziner** [comment]
Jenkins, build artifacts please.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Rebased

**Review by tracernz — APPROVED** [review]

**Pull request merged**
