### PR TITLE
GCS:CrashReporter: Use JSON service instead of forum

### PR DESCRIPTION
**Pull request by tracernz**
@dustin has completed the other end so this can be pushed now. I'd like to write JSON services class in utils at some point so the code can be shared with autotune and perhaps some new services in future.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/130)

### CODE REVIEW

**Comment by tracernz** [comment]
So the crashreporterapp works fine on OSX, it just never gets called by the crash handler. The file I sent as a dummy dump came out looking proper at the other end too @dustin. :+1:

**Comment by PTDreamer** [comment]
Is this being testes on a DMG or APP Bundle?

**Comment by tracernz** [comment]
App bundle in the build directory.

**Comment by PTDreamer** [comment]
Is the crash handler binary on the same dir?

**Comment by tracernz** [comment]
crashreporter.app and dronin GCS.app are both in build/ground/gcs/bin.

**Comment by tracernz** [comment]
Ahh, there's also the crashreporterapp binary in dronin GCS.app/Content/MacOS

**Comment by PTDreamer** [comment]
Yeh the .app shouldn't be there, no idea why it is, can't reproduce it.
The one that should get called is the ...GCS.app/Contents/MacOS/crashreporterapp does it work if you manually run it?

**Comment by tracernz** [comment]
Yes, it runs fine if I pass a filename as an argument, and submits the file successfully.

**Comment by PTDreamer** [comment]
Sorry I can't help more since I can't reproduce.
Debugging should be simple just check what is being called on the LaunchUploader function libcrashreporter-qt/libcrashreporter-handler/Handler.cpp. The new process gets spawned on the execl call.

**Comment by tracernz** [comment]
Yep, I've only just looked at it while testing this as I don't usually run GCS on OSX. I'll look into it more later today. Will let you know if I get to the bottom of it.

**Comment by mlyle** [comment]
This has accumulated conflict.

**Comment by tracernz** [comment]
Rebased and removed phpBB stuff, since the autotune PR has already merged nothing else uses phpBB anymore.

**Comment by mlyle** [comment]
WORKSFORME

**Pull request merged**
