### PR TITLE
PIOS F0 & sim support, various code cleanup and factoring improvements

### PR DESCRIPTION
**Pull request by mlyle**
This is the first fraction of #1148, separated for easier review.  Will rebase 1148 on top once this lands.

### CODE REVIEW

**Comment by tracernz** [comment]
I've had another read through this. Looks pretty good. What's the motivation for reading the LED value? I think you should make the declaration conditional on sim unless there's some purpose for it that extends to STM32 targets (in which case you should implement it for STM32).

**Comment by mlyle** [comment]
Thanks for the read-through.  Will make the declaration conditional.

It's there so when I do actuator updates, I can send to the subsidiary microcontroller the LED status-- flyingpio is in charge of the heartbeat LED.

e.g. https://goo.gl/photos/bhhMX98mh6u6XAqr8 :) (click to play video)

**Comment by tracernz** [comment]
Sounds good. :+1:

**Comment by mlyle** [comment]
jenkins, test this please

**Pull request merged**
