### PR TITLE
UAVOs: restore limits

### PR DESCRIPTION
**Pull request by mlyle**
I screwed this up -- we had very few limits and I missed it in the diff.

### CODE REVIEW

**Comment by mlyle** [comment]
I guess we also lost category, which I'm inclined to remove because we've not really used it

**Comment by tracernz** [comment]
Category is used in the UAVO browser (although not by default).

**Comment by mlyle** [comment]
Yes-- which breaks it into hardware settings and everything else.

Do you really super want it back?  Because I can put it back, but it seems to add a *lot* of complexity to the uavo browser for little benefit.

If we're going to have a ton more UAVOs it might be nice, but we're up against pretty harsh limits on config flash.

**Comment by tracernz** [comment]
No that's fine.

**Pull request merged**
