### PR TITLE
OSD: update boot logo, add image scripts

### LINKED ISSUE #332: OSD: Update boot logo
Should be changed to new dRonin logo.

### PR DESCRIPTION
**Pull request by mluessi**
Added dRonin logo and new brainfpv logo. Also put the source images and the Python script used to generate the header file in the osd include dir.

Fixes #332

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/409)

### CODE REVIEW

**Comment by mlyle** [comment]
Have you eyeballed this on the OSD and it looks OK?

**Comment by mlyle** [comment]
:lgtm: 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/409#-:-K7YErF3tK-7kyM6Ac6I:980077423)*

**Comment by mluessi** [comment]
@mlyle yes, looks good on OSD (IMO)

**Comment by mlyle** [comment]
Cool, thanks :)

**Pull request merged**
