### PR TITLE
sparky: work around PPM suck by forcing 1MHz

### LINKED ISSUE #1071: Actuator auto-resolution changes break PPM in on Sparky1
Thanks to poor timer pin assignments

### PR DESCRIPTION
**Pull request by mlyle**
(only when appropriate).

Fixes #1071

### CODE REVIEW

**Comment by mlyle** [comment]
Confirmed on Sparky1-- Make PPM great again.

**Comment by mluessi** [comment]
Code looks good. I wonder if a better solution would be to have an option to only use the first 5 PWM outputs; they use different timers and could run faster than the timer used for PPM. The downside would be that the user would need to configure this and so it becomes less user friendly.

**Comment by tracernz** [comment]
So to be clear this has always been an issue when using output channels 6 & 10 with oneshot?

**Comment by mlyle** [comment]
@tracernz when moving them to a rate other than 1MHz or using oneshot, yes..  With the new autodetect code, they are always set to a rate other than 1MHz.

**Comment by tracernz** [comment]
Should ignore the bank in pios_servo if max_pulse for the bank is 0. And the time base would have already been set by the call in pios_board.c (with the fixed / 1 MHz config in board_hw_defs.c).

**Comment by mlyle** [comment]
That would be an alternate approach, though it will still fail in some cases this will work.

**Pull request merged**
