### PR TITLE
package: windows: explicitly provide .zip extension

### PR DESCRIPTION
**Pull request by mlyle**
[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/544)

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Artifact showed up, not that it really matters without the dot.

**Comment by tracernz** [comment]
Oh, duh. -_-

**Comment by mlyle** [comment]
Worked on the hotfix build

**Pull request merged**
