### PR TITLE
transmitter_control: properly handle inverted throttle

### LINKED ISSUE #508: Inverting throttle channel freezes radio wizard
[Reported on FPVLAB by traxx2003](http://fpvlab.com/forums/showthread.php?30000-Brain-FPV-Flight-Controller-Open-Source-%28Tau-Labs%29-Full-Graphic-OSD/page165) on Brain with a Futaba R7008SB (SBUS) receiver. The wizard freezes when the throttle channel is inverted.

### PR DESCRIPTION
**Pull request by mlyle**
fixes #508

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/510)

### CODE REVIEW

**Comment by mlyle** [comment]
Have not tested myself.

**Comment by mluessi** [comment]
Now it freezes at the step where the maximum extents are detected.

**Comment by mlyle** [comment]
Yah looks like I'm missing the ! From the if test.  Can't fix until late today

**Comment by mlyle** [comment]
I inverted the test, and re-pushed, but I'll be unable to test myself until later today.

**Comment by mlyle** [comment]
Confirm I was able to go through input wizard with / without throttle inverted with this change.

**Pull request merged**
