### PR TITLE
Initial pass of rebranding stuff, changing stuff TauLabs -> dRonin

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tgreer** [comment]
Slightly screwed up cos I don't understand github, but https://github.com/d-ronin/dronin/pull/40 should be included with this I think/hope?

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please.

**Comment by mlyle** [comment]
OSX build still messed up.

**Comment by mlyle** [comment]
OSX packaging works.  Gonna take a lot of work to make this work for Windows and Linux.

OSX icon is missing because of removed taulabs.icns hack in top level makefile.  Will need to open new issue and replace with something new on subsequent PR.  There are multiple hacks for OSX icon management in the packaging stuff that need cleanliness applied.

**Comment by mlyle** [comment]
3cb47516 built by jenkins on x86-64 successfully.  (packaging broken)
3cb47516 built and packaged on OSX successfully.

**Comment by mlyle** [comment]
6d042fe, built and packaged on OSX, installed, reset configuration, looks OK.

**Comment by mlyle** [comment]
6d042fe flown from installed package on sparky2 on OSX.

**Comment by mlyle** [comment]
6d042fe built, packaged, and installed on Windows 10 successfully.  Ran/smoke-tested after installation.   Tested initial GCS configuration (developer.xml), shortcuts, uninstaller.

**Comment by mlyle** [comment]
branding1

**Comment by jhitesma** [comment]
Minor compared to build issues...but CONTRIBUTING.md still references the Tau wiki.  Only noticed because I just edited the wiki page

**Comment by mlyle** [comment]
@jhitesma yah, the bar here for this PR is very low-- basically "works adequately on all 3 platforms for other people to be able to make progress".  This is supposed to be the one that breaks and then fixes the build and packaging the "most".

**Comment by tracernz** [comment]
GCS seems to run okay on Linux x64 after the above fixes. I'm ready to merge this tomorrow if nothing comes up.

**Comment by mlyle** [comment]
Decided to tangle the brain packaging stuff up in this, since there's common changed files.  Plan on going through another test sequence later today..

**Comment by mlyle** [comment]
73bcbef, merged along with all other PRs except 63 (conflicts) ("kitchensink" branch) ... builds and installs fine on OSX.

**Comment by tracernz** [comment]
Builds and runs okay on Linux x64.

**Comment by mlyle** [comment]
make standalone is broken on linux, but this is deliberate (pending further packaging work).

73bcbef works on windows-- builds, packages.  package executes/smoke tests OK.  uninstall OK.

**Comment by tracernz** [comment]
Okay, merging this since it touches too many files to sit around. It seems to be okay on all three platforms and we can fix any breakage if it occurs afterwards.

**Pull request merged**
