### PR TITLE
flight: support openlog on sparky2

### PR DESCRIPTION
**Pull request by henn1001**
tested ->  #450

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/556)

### CODE REVIEW

**Comment by mlyle** [comment]
stupid jenkins

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by henn1001** [comment]
spambot!

**Comment by mlyle** [comment]
Thanks very much for opening this and testing it :)

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please (was out of disk space on builder)

**Comment by mlyle** [comment]
Uh I missed it on the other port.  Sorry.  Looks great.

**Pull request merged**
