### PR TITLE
WIP: System settings refactor dronin

### PR DESCRIPTION
**Pull request by kubark42**
See https://github.com/TauLabs/TauLabs/pull/2104.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/186)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
Exciting stuff.  Need to figure out how this sequences in re: release, especially since it's currently multirotor only.  @tracernz, your thoughts?

**Comment by kubark42** [comment]
This is for testing only. There's only so much coverage I could give, and it needs testing on more exotics such as tricopters and octos to make sure I didn't mess anything up.

I think the other platforms will integrate quickly enough, now that the framework is in place. But I thought this was a good stopping place for the time being, especially because there might be architectural concerns raised, and I would prefer to address those now before duplicating too much work.

FWIW, I'd suggest for the moment that conversation happen at https://github.com/TauLabs/TauLabs/pull/2104. This is only because it will make it easier to link to the relevant conversation at https://github.com/TauLabs/TauLabs/issues/2061. 

P.S. There was only one tiny conflict in the includes of the header file in ```systemod.c```. Aside from that, the code submissions are identical.

**Comment by mlyle** [comment]
Fails build:

```
/var/lib/jenkins/jobs/dron/workspace/Nodes/master/ground/gcs/src/plugins/config/configvehicletypewidget.cpp:329:6: error: unused parameter ‘index’ [-Werror=unused-parameter]
 void ConfigVehicleTypeWidget::switchAirframeType(int index)
      ^
/var/lib/jenkins/jobs/dron/workspace/Nodes/master/ground/gcs/src/plugins/config/configvehicletypewidget.cpp:528:6: error: unused parameter ‘comboboxIndex’ [-Werror=unused-parameter]
 void ConfigVehicleTypeWidget::doSetupAirframeUI(int comboboxIndex)
```

**Comment by kubark42** [comment]
Yeah, it's going to fail because of --Werror catching all the now unused variables resulting from massive commented sections. Those will get cleaned up as the PR moves forward, but they're all in the non-multirotor platforms so I took the expedient route to get this 1-st stage of refactoring out the door.

**Comment by mlyle** [comment]
This is incomplete, and because of cross-project conflict I doubt you're interested in completing this.

**Pull request closed without merging**
