### PR TITLE
GCS: Various improvements to board support

### PR DESCRIPTION
**Pull request by tracernz**
These commits are improvements in preparation for future work (they were cherry-picked from that branch).
* Cleanup unused cruft in board plugins
* Add support for SRXL to underlying setup code (but not actually in UI, my plan is to replace SUMD once that driver is integrated into SRXL)
* Add a couple of convenience functions for UAVO handling. Especially useful in board plugins.

### CODE REVIEW

**Comment by yamahabest** [comment]
I have been working on adding Ibus to all boards, and some other small stuff. I could now also add SRXL in the same go.
Will you also, in the end, add SRXL to the UI? Perhaps you could also add Ibus then?

**Comment by tracernz** [comment]
You are welcome to do it. :-)

**Comment by yamahabest** [comment]
Let me see, I still have to figure that out.
Probably best if this is merged to next first, then I can pull it into my branch.

**Comment by tracernz** [comment]
That will be the simplest way. 👍 (@mlyle :wink:)

**Comment by mlyle** [comment]
OK, mergin' blind, can always fix it later ;D

**Pull request merged**
