### PR TITLE
Build: Windows build improvements, VS2015, Pick up QT 5.6.1

### LINKED ISSUE #295: OpenGL / Mesa on windows needs a permanent fix

### LINKED ISSUE #373: Need to ship MSVC runtime...
User reported that he has an error message show up every time he boots the GCS, but can continue beyond that, and the GCS still works:
> Does it matter that I get an error everytime I launch Dronin or Tau that says: "The program can't start because MSVCR120.dll is missing if I hit "OK" it launches and runs fine

Same problem exists on Tau as well.

### PR DESCRIPTION
**Pull request by mlyle**
Fixes #295 
Fixes #373 
Connects to #290
Supersedes #1142

### CODE REVIEW

**Comment by mlyle** [comment]
Opening when not complete to begin testing original CI with these change sets.

Jenkins, build artifacts please.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
Made some minor CI conf changes-- so that any node with 'winx86' in the name is recognized as Windows.  Testing that out.   Jenkins, build artifacts please.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
OK, that's one.  Can we repeat it?

Jenkins, build artifacts please

**Comment by jhitesma** [comment]
Tried GCS from this on my old slow system with windows 10.  Samsara is about 13 seconds from click until GCS is usable.  New test build is 16-17 seconds.  With about half a second variation between tests.

Overall feel seems just as responsive when actually being used, and the starting time is close enough that it felt about the same to me until I pulled out the stopwatch.

**Comment by mlyle** [comment]
Thanks @jhitesma for the report.

Note whether or not we use MSVC on a slave is just a single jenkins environment variable for the node --- which is currently turned on.

We should merge this and then decide what to do with MSVC vs. not.

**Comment by tracernz** [comment]
Looks good.

**Pull request merged**
