### PR TITLE
gcs: Set default heli swashplate config to CCPM 3-servo 120-degree

### PR DESCRIPTION
**Pull request by ekaszubski**
Sets default swashplate config selection box to ccpm 3-servo 120-degree

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/517)

### CODE REVIEW

**Comment by tracernz** [comment]
I'd prefer `m_ccpm->ccpmType->setCurrentIndex(m_ccpm->ccpmType->findText(QString::fromUtf8("CCPM 3 Servo 120º")));` so it won't break if the list changes, and it's a bit clearer that you intend the default to be 120.

**Comment by ekaszubski** [comment]
@tracernz totally agree, didn't know that was an option

**Comment by ekaszubski** [comment]
@tracernz Implementation updated, seems to work fine now. Let me know if I should be doing it a different way.

**Comment by tracernz** [comment]
Looks alright. The whole way this thing works is severely ugly though. :-P

**Comment by ekaszubski** [comment]
Just wanted to clarify the need for this PR:
- Previous default swashplate config is "custom/advanced" which relies on manually setting all the mixer values, so clearly the default needs to change
- 3-servo 120-degree is by far the most common setup for the kinds helicopters that would be candidates for running dRonin (number of control axes, size, no integrated flight controller board)

Examples:
- [T-Rex 450](http://www.align.com.tw/helicopter-en/trex450/)
- [Oxy 3](http://www.oxyheli.com/products/oxy-3-helicopter-kit)
- [HD Heli Cell 500](http://www.hd-helicopters.com/helicopter/hd-500-cell-dbds1)
- [Goblin 380](http://www.goblin-helicopter.com/shop/product_info.php?cPath=96_152&products_id=25983)
- [Goblin 500](http://www.goblin-helicopter.com/shop/product_info.php?cPath=96_164&products_id=26463)

Exceptions:
- [Velos 880](http://www.velos-rotors.com/velos-880) (4-servo 90-degrees)

**Pull request merged**
