### PR TITLE
radiocombridge: remove doubled watchdog reg

### LINKED ISSUE #825: pipxtreme firmware broken in next?
Just been trying out the next build and it seems like the pipxtreme firmware is broken. Im trying to load it onto my oplink but it just goes into a boot loop once flashed. Ive tried my own built firmware and also the firmware from the build at the bottom of https://github.com/d-ronin/dRonin/pull/801
I can go back to the stable release and it works again ok. Ive tried using a stable version of the GCS to flash the next build firmware just incase it was that but still get into a boot loop.

### PR DESCRIPTION
**Pull request by mlyle**
@rabno1, @pug398-- does this fix things?  if it does, it's a regression we picked up from #807 

hoped: fixes #825

---

This change is [Reviewable](https://reviewable.io/reviews/d-ronin/dronin/827)

### CODE REVIEW

**Comment by rabno1** [comment]
Worked for me thanks. I replaced rediocombridge.c with the one above, rebuilt the pipxtreme firmware and that worked fine. my previously built firmware gave me the bootloop.
Hope what i did to test this was ok?

**Comment by mlyle** [comment]
Perfect, but it's easier to just checkout the PR branch.  

I add a line to my .git/config that looks like:
        fetch = +refs/pull/_/merge:refs/remotes/prm/_

under the main dronin [remote] section.  And then 'git fetch upstream' (or whatever you call the dronin remote) will get a prm per PR, and you can do git checkout prm/827 to get this PR checked out on top of next.

**Comment by mlyle** [comment]
P.S. Thanks for the test.

**Comment by rabno1** [comment]
No problem.  Ill work on getting the checkout working. I only got everything installed and done my first next build yesterday LOL

**Comment by mlyle** [comment]
Next is scary.. It tries to break your stuff :P

**Comment by dustin** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/827#-:-KDZTskVefu4zvJauYQ3:1417088721)_

**Pull request merged**
