### PR TITLE
Multiplex SRXL RX Driver

### PR DESCRIPTION
**Pull request by tracernz**
SRXL (and variants) is supported by most non-Spektrum/FrSky receivers. This driver supports the original (and open) Multiplex SRXL standard (http://www.multiplex-rc.de/service/downloads/schnittstellenbeschreibungen.html?eID=dam_frontend_push&docID=4233). It should be extended in future to support more variants, e.g. JR, Graupner HoTT (and we can then drop that driver). At least Jeti, Weatronic and Multiplex can output Multiplex SRXL standard.

Tested on a Jeti RSat2 receiver before rebase to current next.

Blocked by #991 conflict.

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

@ufoDziner please ground test with your new Weatronic radio :)

**Comment by ufoDziner** [comment]
Could not get SRXL to work with a cc3d or Brain on Main port.  Tested using Multiplex 12 & 16 options, as well as Weatronic 16.  Interestingly, I couldn't get PPM to work on the Brain either.  Used the same receiver on each, connecting through the Rx port on each.  Probably a known limitation for people, but I could only get a maximum of 12 channels using PPM (there is a 16 option as well) and still have it communicate with the FC.

Edit: Sadly I didn't thank you for putting this together so quickly.  So, THANK YOU.  I'm really looking forward to it working!

**Comment by tracernz** [comment]
Currently only 12 PPM channels are supported on all targets except Naze, which curiously supports 8.
https://github.com/d-ronin/dRonin/search?p=1&q=PIOS_PPM_NUM_INPUTS&utf8=%E2%9C%93

**Comment by m-thread** [comment]
"Could not get SRXL to work with a cc3d or Brain on Main port."
Well I had the same experience when implementing this in LibrePilot last spring. My theory is that it's the design of the inverter on the Main port that makes the signal level shift compared to using the Flexi port. This could probably be addressed by adding external pull up/down though. We opted eventually to not having it available on Main port but just on the Flexi port.

**Comment by ufoDziner** [comment]
Success!!!  I verified that at least some of this works.  Successfully tested with a Sparky 2 using the Flexi port.  Will continue to test on other ports on the Sparky 2 and other Flight Controllers.

**Comment by ufoDziner** [comment]
Okay... Works with Brain on Flx port, cc3d on Flexi port, and Sparky 2 on Flexi port and Rcvr Port.  Flex port, pins 1,2, &4 must be used.  These tests were done using the SRXL Multiplex 12 setting it the Transmitter.  I will test with the SRXL Multiplex 16 settings later.

Thanks @m-thread for the info.

**Comment by ufoDziner** [comment]
There appears to be one portion of the signal that is potentially not being recognized.  There is a "Sum Signal Off While In Failsafe" option which I have active, but the failsafe in the wizard does not acknowledge that there is no signal.  It also seems that the SRXL Multiplex 12 is working, but the SRXL Multiplex 16 is not.  Unfortunately I don't have a way to look at the signal, but should have a logic analyzer in hand when I return from a trip in 2 weeks.  If there is anything else I can do to test prior to then, please advise.

**Comment by tracernz** [comment]
Rebased and added RE1, untested.

**Comment by mlyle** [comment]
@tracernz, @ufoDziner --- should this be tracked to merge, or should we wait for multiplex16 support?  Getting late in samsara..

**Comment by tracernz** [comment]
@mlyle It should be merged for Samsara IMO, what date are we shooting for? I'm not sure what boxes my RC gear is in at the moment but I can check with my RX and see what's up when I unpack it.

**Comment by mlyle** [comment]
Nominal release date is July 3, but we're going to be late, I think.  

I'm doing crude project management in https://forum.dronin.org/forum/d/23-samsara-next-release-work-in-progress

**Comment by ufoDziner** [comment]
I attempted to capture Multiplex 12 signal with a logic analyzer. The results are here:

https://dl.dropboxusercontent.com/u/59924814/Weatronic_Capture.zip

Failsafe activated after 5 seconds in the Failsafe files.
If this worked, I will do it again with Multiplex 16, and Weatronic 16.

**Comment by mlyle** [comment]
What software package are you using on the logic analyzer? is this the saleae stuff?

**Comment by hjns** [comment]
He's using Saleae, I just opened the files on Linux with Saleae Logic.  Their software opens the files even if you don't have an analyzer attached.

**Comment by mlyle** [comment]
@hjns cool, thanks.

**Comment by tracernz** [comment]
That capture looks good. I'm most interested in Multiplex 16-channel and Weatronics 16-channel with/without failsafe. Hopefully the Weatronic stream has a failsafe flag, since they violate the Multiplex spec (SRXL packets should only be sent when a signal is received from the tx).

**Comment by ufoDziner** [comment]
Great!  I did that one for a comparison, as it's already working.  I will get the others this evening.  I'll do 10sec captures with first five normal, last 5 failsafe. Unless you need something else.

**Comment by ufoDziner** [comment]
New file with all the data.

https://dl.dropboxusercontent.com/u/59924814/Weatronic_Capture.zip

**Comment by tracernz** [comment]
Had a bit of a look at your data. The reason Multiplex 16 doesn't work is because there is no data in any of those captures. Multiplex 12 looks good except the Rx continues to output packets in failsafe mode which is incorrect (per the Multiplex spec). I'm looking at Weatronic 16 now, hoping it includes a failsafe flag.

**Comment by tracernz** [comment]
P.S. Multiplex 12 works perfectly including failsafe with my Jeti RX.

**Comment by ufoDziner** [comment]
If there is no data in the Weatronic captures as well, then I probably did something wrong.

**Comment by tracernz** [comment]
The Weatronic 16 and Multiplex 12 captures look good, all have data. It's just the Multiplex 16 capture that is empty, which would explain why it's not working for you at all.

**Comment by mlyle** [comment]
Passed on from IRC:  
[Weatronic_Capture16.zip](https://github.com/d-ronin/dRonin/files/322090/Weatronic_Capture16.zip)
[Weatronic_16_SRXL_RangeTest_ch16.zip](https://github.com/d-ronin/dRonin/files/322091/Weatronic_16_SRXL_RangeTest_ch16.zip)

**Comment by ufoDziner** [comment]
Thanks.  I tried to attach a zip earlier and it was rejected (that's why I used the dropbox link).

**Comment by ufoDziner** [comment]
Jenkins, build artifacts please.

**Comment by tracernz** [comment]
Weatronic support added. Bench tested by @ufoDziner.

**Comment by ufoDziner** [comment]
Successfully bench tested, and flown on OG Brain, and Brain RE1.  No issues.  Woot!

**Comment by mlyle** [comment]
Awesome---- thanks much @tracernz and @ufoDziner

**Comment by ufoDziner** [comment]
@tracernz Attempted to capture the Multiplex SRXL 16 data again.  Let me know if it works.

https://dl.dropboxusercontent.com/u/59924814/Multiplex16_Capture.zip

**Comment by tracernz** [comment]
It now has data. Does it work with a flight board?

**Comment by ufoDziner** [comment]
Nope.  Tried several times.  Multiplex 12 and Weatronic 16 both work, but Multiplex SRXL 16 does not.

**Comment by tracernz** [comment]
Okay, thanks. I'll write some tools to spit your captured data back into a board so I can test.

**Comment by tracernz** [comment]
Ah, just noticed the issue. Your Rx is sending the sync byte of 0xA1, that means 12 channels, should be 0xA2 for 16 channels.

screenshot from 2016-06-22 21-07-42

**Comment by tracernz** [comment]
Have written code for and tested next with my little rx packet generator:
- Multiplex 12
- Multiplex 16
- Weatronic 16

All is well.

**Comment by tracernz** [comment]
Remembered to test MainPort on both CC3D and Brain. Both worked perfectly with my Jeti RX (Rsat2).

**Comment by ufoDziner** [comment]
Successfully tested Weatronic 16 on Brain MainPort as well.  Woot!

**Pull request merged**
