### PR TITLE
gcs: fix up build dependencies to remove erratic behavior

### LINKED ISSUE #313: GCS build seems to be missing UAVO dependency
Changing an UAVO, e.g., adding a field to an enum, doesn't seem to trigger rebuilding the parts of the GCS that depend on the UAVO. When looking at the UAVO in the UAVO browser, the object is grayed out and the fields that have been added to the enum are missing.

Observed on Linux

### PR DESCRIPTION
**Pull request by mlyle**
This also removes a non-functional unit test from uploader plugin.

Fixes #313 

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/341)

### CODE REVIEW

**Comment by mlyle** [comment]
Manually editing systemalarms.h from the synthetics, and inhibiting the synthetic build... now does this:

```
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/coreplugin/mainwindow.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/coreplugin/versiondialog.cpp
compiling .moc/debug-shared/moc_versiondialog.cpp
compiling /Users/mlyle/dronin/build/uavobject-synthetics/gcs/systemalarms.cpp
compiling /Users/mlyle/dronin/build/uavobject-synthetics/gcs/uavobjectsinit.cpp
compiling .moc/debug-shared/moc_systemalarms.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/uavobjectutil/uavobjectutilmanager.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/sysalarmsmessaging/sysalarmsmessagingplugin.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/systemhealth/systemhealthgadgetwidget.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/logging/logfile.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/uavsettingsimportexport/uavsettingsimportexport.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/uavsettingsimportexport/uavsettingsimportexportfactory.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/telemetryscheduler/telemetryschedulergadgetwidget.cpp
compiling .moc/debug-shared/moc_uavsettingsimportexport.cpp
compiling .moc/debug-shared/moc_uavsettingsimportexportfactory.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/uavobjectwidgetutils/configtaskwidget.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/config/configoutputwidget.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/config/vehicletrim.cpp
compiling /Users/mlyle/dronin/ground/gcs/src/plugins/setupwizard/pages/outputcalibrationpage.cpp
```

All 5 files that directly include systemalarms.h are rebuilt.

**Comment by PTDreamer** [comment]
Why do you say the unit test on the uploader plugin is non functional, it was working the last time I tried it.
Also since the PR title is not specific to the uploader plugin maybe you could fix the plugins build time dependencies on this changeset. Due to misunderstanding of how it works or simple typos the result plugins.pro file is quite a mess:
Example:
```
# BrainFPV LLC
plugin_boards_brainfpv.subdir = boards_brainfpv
plugin_boards_brainfpv.depends = plugin_coreplugin
plugin_boards_brainfpv.depends = plugin_uavobjects
plugin_boards_brainfpv.depends = plugin_uavobjectutil
plugin_boards_brainfpv.depends += plugin_uavobjectwidgetutils
SUBDIRS += plugin_boards_brainfpv
```
As it can be seen the dependencies are overwrites by using "=" instead of "+=".  That file is full of similar code.

**Comment by mlyle** [comment]
I'm sorry, it's just that the uploader plugin unit test is trivial and isn't run by the unit test.  If there's strong opposition I can put that back.

I was mostly touching DEPENDPATH to make sure that it paid attention to include dependencies, which I think is where we get into a lot of trouble with incomplete builds.  I'll skim the plugins.pro to see if I can make it better, though.

**Comment by mlyle** [comment]
OK, I went through the plugins.pro.  It was mostly the board plugins that were wrong.

**Comment by mlyle** [comment]
For reference, this is the entirety of the uploader plugin unit test:

```
void UploaderPlugin::testStuff()		
{		
    QCOMPARE(QString("hello").toUpper(), QString("HELLO"));		
    QCOMPARE(mf->isAutoUpdateCapable(), true);		
}
```

**Comment by PTDreamer** [comment]
> I'm sorry, it's just that the uploader plugin unit test is trivial and isn't run by the unit test. If there's strong opposition I can put that back.

That was intended to show how to use the plugins testing platform. It is triggered by the test command line option. It was never used but it seems like a nice thing to have. Maybe some proper wiki documentation can replace it.
The command to run is:
```
./drgcs --test Uploader
```
and the output will look like:
```
********* Start testing of UploaderPlugin *********
Config: Using QtTest library 5.5.0, Qt 5.5.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 4.9.1 20140922 (Red Hat 4.9.1-10))
PASS   : UploaderPlugin::initTestCase()
FAIL!  : UploaderPlugin::testStuff() Compared values are not the same
   Actual   (mf->isAutoUpdateCapable()): 0
   Expected (true)                     : 1
   Loc: [/home/jose/Code/dRonin/ground/gcs/src/plugins/uploader/uploaderplugin.cpp(65)]
PASS   : UploaderPlugin::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted
********* Finished testing of UploaderPlugin *********
```

**Comment by mlyle** [comment]
@PTdreamer -- that's really cool, is there any chance we could teach the unit test in the build to drive this?  (Also to have --test run all the tests).

**Comment by mlyle** [comment]
Updated to take the unit test change out.  I like the idea of GCS unit tests, but if we're to have them A) it should be altered to pass, B) make all_ut_run should run them.

**Comment by PTDreamer** [comment]
> @PTdreamer -- that's really cool, is there any chance we could teach the unit test in the build to drive this? (Also to have --test run all the tests).

Drive this as a target yes, integrating with google test no idea. It can produce an xUnit compatible xml so it can be handled by jenkins.
I'll make a PR with a command line option to run all gcs tests.

**Comment by PTDreamer** [comment]
Also the QTestLib platform can do not only tests but also benchmarking

**Comment by tracernz** [comment]
Seems to do the right thing. Merging now that tests have been removed from the PR.

**Pull request merged**
