### PR TITLE
Replace naze graphics with render of an actual naze

### PR DESCRIPTION
**Pull request by DTFUHF**
Spek port is blue, usb is a bit green, crystal is purple, no transparency, these can be fixed if needed.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/171)

### CODE REVIEW

**Comment by mluessi** [comment]
LGTM

**Comment by mlyle** [comment]
This is NazeR6.  Do we support nazer6?

**Comment by tracernz** [comment]
No. Also, fix the ports ;-).

**Comment by tracernz** [comment]
Can you do a top-down view render too? I'd like to create a connection diagram at some point.

**Comment by tracernz** [comment]
Oh yeah, needs to be a transparent PNG too, not white background.

**Comment by mlyle** [comment]
In renatus for now

**Comment by DTFUHF** [comment]
Pic replaced with a better one.

-Transparent PNG
-Square to camera
-Better colours
-Board "Front" to top of image

**Comment by tracernz** [comment]
Looks great, thanks! :-)

**Comment by tracernz** [comment]
```
[Warning] libpng warning: iCCP: known incorrect sRGB profile
[Warning] libpng warning: iCCP: cHRM chunk does not match sRGB
```
@DTFUHF I fixed the colour profile to get rid of the above warnings and cropped the image as much as possible (the large empty space around it just makes the image appear really small in uploader). Can you update your branch with the below image please? Will probably hold off on merging this until we support the rev. 6.

nazev6

**Comment by tracernz** [comment]
Good news is that I have the rev. 6 all go on a local branch with my new common MPU driver so I will merge this once the above PNG is committed and Renatus is off next.

**Comment by DTFUHF** [comment]
@tracernz updated the PNG. Thanks.

**Comment by tracernz** [comment]
Great, thanks! :lgtm_strong: 

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/171#-:-K8MwqplQ6gQok3axDVn:1724182098)*

**Pull request merged**
