### PR TITLE
flight: printf2 stack alignment change

### PR DESCRIPTION
**Pull request by mlyle**
Source: brainFPV/TauLabs#40 / @droney

Converted to diff and reformatted

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/394)

### CODE REVIEW

**Comment by mlyle** [comment]
I have not yet reviewed or vetted this.

(Not a fan of maintaining our own printf implementation-- is there a reason we can't just use the one in newlib?)

@droney thanks for the code/fix.

**Comment by droney** [comment]
I attempted to close this pull request as it was intended to be directed at brainfpv specifically since that fork currently uses printf2. Taulabs eliminated this module two months ago. Please close this pull request.... my attempt apparently did not work.

**Comment by mlyle** [comment]
@droney dRonin is a fork of TauLabs that supports BrainFPV, so I picked up your PR because of that.  (It may become the official BrainFPV firmware).

**Comment by droney** [comment]
I agree with you that newlib is the right long term solution. newlib has changed enough where I no longer see the stack alignment code in the printf function. I suspect when compiling with newlib for EABI platforms, stack alignment is handled for all public function calls. However I am not familiar enough with newlib to confirm this.

**Comment by mlyle** [comment]
Attribution fixed.

**Comment by mluessi** [comment]
Bench tested, works.

**Pull request merged**
