### PR TITLE
gcs: portable settings

### PR DESCRIPTION
**Pull request by mlyle**
possibly supersedes #268

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/603)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
This does what it says on Windows.  But, displaying the checkbox for portable settings should be conditional on it not being installed system-wide.

**Comment by tracernz** [comment]
I'll test this as well when you're done and happy to merge. I have read the code previously in @PTDreamer's original PR.

**Comment by mlyle** [comment]
@PTDreamer is back, so this probably gets abandoned / closed

**Pull request closed without merging**
