### PR TITLE
bl: fix partition erase

### PR DESCRIPTION
**Pull request by henn1001**
bug i stumbled upon today.
Would obviously mean that the bootloader version has to be bumped and updated for a new release.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/695)

### CODE REVIEW

**Comment by mlyle** [comment]
Good find.  Not something most people do, but we should bump bootloader vers too.  Are you willing to do that in this PR?

jenkins, test this please.

**Comment by henn1001** [comment]
Sure thing - i´ll read into it how to do it.

**Comment by mlyle** [comment]
It's BOOTLOADER_VERSION in board-info.mk

**Comment by henn1001** [comment]
Done!
We should also consider including other changes to the bl when this is merged before a new release.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
Yep, worth considering if there's anything else we'd like to do to BL.

**Comment by mlyle** [comment]
Yup.  Though this isn't enough of a change that we should advise users to upgrade the bootloader, IMO.  Just something nice to have when someone upgrades anyways.

**Comment by tracernz** [comment]
We should address https://github.com/d-ronin/dRonin/issues/147 if we're bumping the version too.

**Pull request merged**
