### PR TITLE
Rates/stabilization usability, and expoM

### LINKED ISSUE #108: expoM for Rate
There's some outstanding work that may need to be done in the GCS regarding curve display in the Advanced stabilization tab.

References #55 taulabs/taulabs#1785

### PR DESCRIPTION
**Pull request by mlyle**
Add expoM for rate mode, and associated UI graph widget, etc.  Also a lot of cleanups.

fixes #108 
Connects #1248 

Cleanups:
- GCS: rearrange UI based on what people actually use
- clean up assumptions infrastructure/DONT_BUILD_IF, make much more
  comprehensive
- factor stabilization scaling code to be common between axes, clean up
- remove attitude expo for dubious usefulness
- rename stab_settings to stab_modes to avoid very similar
  stabSettings
- Change RollMax, PitchMax, YawMax to elements of MaxLevelAngle in
  StabilizationSettings

Todo:
- [x] Link roll and pitch checkbox
- [x] Disable widgets when not connected

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
This is complete now, but needs a little more test from yours truly before broader use.

**Comment by mlyle** [comment]
button groups for 'defaults' not correct

**Comment by mlyle** [comment]
Tested LoS + brushed-- happy.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
(Still need the autotune wizard update for this--- not in this PR).

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by jhitesma** [comment]
Got this on the airbot F4 board tonight and played with the UI a little.  

It doesn't display well on my default window size:
screenshot

If I go full screen it's cramped but usable.
fullscreenshot

The graph doesn't seem to make as much sense to me as the demo @mlyle had shared when working on this...I also also limited to a max rate of 850...was hoping to set a max around 900 with a fairly flat center and quick fall off to see how it felt like I was able to do with the demo but couldn't seem to reproduce it.

Would be nice to have the option to link roll/pitch instead of having to adjust them manually.

Will play with it more tomorrow, gotta get some sleep right now.

**Comment by mlyle** [comment]
The max rate limit is probably from the default GyroRange of 1000 set in Revolution

**Comment by glowtape** [comment]
Flew a few packs on this. 540°, 21% transition and 200° center slope, similar to previous settings with expo3. Seemed to work out fine.

**Comment by mlyle** [comment]
@jhitesma  -- I padded this out so it should take up more vertical space now.  Still very crowded horizontally.

image

**Comment by jhitesma** [comment]
I always forget about GyroRange defaults.  Bumped it to 2k and it lets me go stupid crazy on max rate now ;)

Flew with 850/35/167 on roll and pitch and 720/35/157 on yaw (with 1k gyro) and WOW!

Loved it!  Got a great locked in autotune (~20ms tau) and this thing is flying better than ever.  With the settings above the control is what I've been searching for.  Go easy on the sticks and it's a docile puppy, but get past the magic point and boom it's a beast.  Was doing quad rotation flips/rolls and corner rolls without loosing altitude even without blipping the throttle.

With a bit of fine tuning on the UI this is a HUGE win :+1:

**Comment by ufoDziner** [comment]
jenkins, build artifacts please.

**Comment by ufoDziner** [comment]
Flew 2 packs worth LoS on an RE1.  Really like the ability to tweak the settings more than with just "expo".  Have no issues to report.

**Comment by mlyle** [comment]
image

**Comment by mlyle** [comment]
Functionally complete and flight tested.  Ready for review (UI test would be appreciated too).

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Ugh, need to rebase out a pound-on-keyboard commit comment :P

**Comment by mlyle** [comment]
Done.  That was stupid :P

**Comment by ufoDziner** [comment]
Not sure if this PR is the reason, but I just noticed that all of the motors are set to "None" on the Vehicle tab, but are assigned correctly on the Output tab.

**Comment by mlyle** [comment]
Not related-- just more instance of #315 #1220

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
Nice cleanup on the flight side. :+1: Not super happy with the way the GCS widgets are linked but it works so meh. :stuck_out_tongue:

**Pull request merged**
