### PR TITLE
***DO NOT MERGE*** No Baro code for tanto Brain ***DO NOT MERGE***

### PR DESCRIPTION
**Pull request by droidicus**
**_DO NOT MERGE**_
Please do not merge this, I will remove it manually once build artifacts are available.
**_DO NOT MERGE**_

### CODE REVIEW

**Comment by droidicus** [comment]
jenkins, build artifacts please

**Comment by droidicus** [comment]
jenkins, build artifacts please

**Comment by droidicus** [comment]
jenkins, build artifacts please

**Comment by fujin** [comment]
We should make the baro optional. :+1:

**Comment by mlyle** [comment]
...

**Pull request closed without merging**
