### PR TITLE
build: tools: bump openssl installer version

### PR DESCRIPTION
**Pull request by mlyle**
Thanks to @droney in #565 for pointing this out.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/566)

### CODE REVIEW

**Comment by pug398** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
@pug398 no need to test this one, it's only used in setting up a build environment (e.g. this will be building essentially plain next)

**Comment by pug398** [comment]
Ok I was looking to build something that basically only next build :/

**Comment by mlyle** [comment]
OK, then it'll be here shortly ;)

**Pull request merged**
