### PR TITLE
light telemetry improvements

### PR DESCRIPTION
**Pull request by mlyle**
* pick up changes from TL
* slightly increase buffer size
* Simplify scheduler / make it easy to add future frame types
* Adjust scheduler to try to fill link better and be fair between
different frame types
* Control selection of G frame type better-- don't initialize objects
that don't belong to us, and use the initialization to select which of
the sources (positionactual, baro, GPS) to use.
* Remove some redundant checks (module can only run if we have a port)

### CODE REVIEW

**Review by tracernz — APPROVED** [review]
Looks good. Will KipK's stuff be ok with potentially higher rate?

**Comment by mlyle** [comment]
@tracernz I'm not sure.  It's potentially 20% faster.

@kipk -- do you see any problems with this?  I'm working on lighttelemetry for other reasons, but it'd be nice to keep compatibility.

**Comment by tracernz** [comment]
Not a blocker for us imo, but would be nice to keep compatibility if possible.

**Comment by mlyle** [comment]
This half is good to merge, I think.

**Comment by KipK** [comment]
Hi.

I'm out of the community for monthes, so sorry for the lack of answers.


No problem to make evolve the protocols to your needs, LTM was only a kind of draft to my needs only :)

Best

**Comment by tracernz** [comment]
Thanks Kip, appreciate your input! 👍

**Pull request merged**
