### PR TITLE
stm32f0: rtc: change frequency to match other targets

### PR DESCRIPTION
**Pull request by mlyle**
This may solve PPM-related problems on flyingpi.

Untested.  Hat tip @jihlein for the question on IRC, which made me think of the supervisor-- I hadn't realized that PPM "started working eventually".

### CODE REVIEW

**Comment by mlyle** [comment]
@jihlein can you try this please?

**Comment by jihlein** [comment]
@mlyle - no joy, in fact after those few times it took a while for PPM to sync, I haven't been able to get it to sync again.  Not sure what I did different those few times.

FWIW - I had tried something similar with the PIOS_PPM_Supervisor SUPEVISEOR_TICK_DIVIDER, but it didn't help either.  I also raised the clock value from 40 MHz to 48 MHz just to see what would happen, that didn't help either, not that I expected it would.

EDIT-Something deeper is not right, I made some mods to put the RTC Tick on a GPIO pin, logic analyzer says it's 312.5 Hz.  Investigating......

**Comment by jihlein** [comment]
RTC Tick is fine, I used an LED toggle, on for one period, off for one period, and didn't account for that in my calculations.  Moral to the story - 6:00 am is too early to be working on this :)

**Comment by mlyle** [comment]
Bummer, I was "sure" it would be this.

**Comment by jihlein** [comment]
I was hopeful too.  I'll try to throw an SBUS receiver on it later, if that still works I think this is still a useful PR.

**Comment by jihlein** [comment]
No time like the present, just threw an SBUS rx on it, and it still calibrates and works correctly on the bench.  No flight test though.

Not sure what else we can test here, so I'm inclined to say it has no ill effects, and matches the other targets, so it's a useful change.

**Comment by mlyle** [comment]
Yah, I agree-- feel free to merge :D

**Comment by mlyle** [comment]
Thx.  I will think more about PPM.  I've gotten stuck a few times looking at it, but I never realized that it can eventually work, which I feel like is a pretty big clue.

**Comment by jihlein** [comment]
FWIW, I left some notes in #1420 detailing my observations so far.

**Comment by tracernz** [comment]
Thx for merging! 😀

**Pull request merged**
