### PR TITLE
flight: coalesce uav objects into library

### PR DESCRIPTION
**Pull request by mlyle**
This avoids building the UAVO's so many times, and it will allow us to shorten Windows link command lines so that jenkins etc work without putting things in a short path.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please.

**Comment by mlyle** [comment]
test this please

**Comment by mlyle** [comment]
test this please

**Comment by mlyle** [comment]
test this please

**Comment by mlyle** [comment]
test this please

**Comment by mlyle** [comment]
This includes the Taulabs/Taulabs#1895 fixes that were in Taulabs/Taulabs#1899.  Since both touch uavo build it made sense to combine them, to avoid dependency issues.

**Comment by mlyle** [comment]
test this please.  Getting much closer.

**Comment by mlyle** [comment]
test this please.  ccache problematic on windows. (8192 char command line limit??)

**Comment by mlyle** [comment]
test this pelase

**Comment by mlyle** [comment]
this this please

**Comment by mlyle** [comment]
test this please

**Comment by mlyle** [comment]
test this please.

**Comment by mlyle** [comment]
Got one green build.  Trying again.  Also did a rebase to next to eliminate the python commit / merge commit from being in the list.

**Comment by tracernz** [comment]
Looks good and builds successfully.

**Comment by mlyle** [comment]
Cool, thanks much for the merge!

**Pull request merged**
