### PR TITLE
GCS: s/taulabs/dronin/

### PR DESCRIPTION
**Pull request by tracernz**
Finally all gone except the taulabs.org string required for the Google Maps API key. A couple of other minor issues corrected too.

Note: this requires a clean build, must be missing deps somewhere.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/680)

### CODE REVIEW

**Comment by tracernz** [comment]
There are still some strings in translation files...

**Comment by tracernz** [comment]
Note: might break packaging, haven't looked (plugins dir name changed from taulabs to dronin).

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Looks like the commenting is just completely broken now.. dunno if API change or what

**Comment by mlyle** [comment]
Artifacts work nicely for me on Windows 10.

**Pull request merged**
