### PR TITLE
androidgcs: enhanced support -- maps, arch support, uavo collection

### LINKED ISSUE #705: ship android GCS
- [x] Building / running
- [x] Jenkins build
- [x] Some branding
- [x] Maps API key?
- [x] Store publishing etc?  Or just ask people to sideload.
- [x] Doesn't work in release config?  Wut?

Lots of people want this-- I was surprised.

### PR DESCRIPTION
**Pull request by mlyle**
Fixes #705

### CODE REVIEW

**Comment by mlyle** [comment]
1. I have a keyring and paid the Google Play $25 tax.
2. I have built and submitted this to the google play store-- in production-- as built with this revision, blindly (well, I ran the artifact in the emulator).  Will try downloading it to my phone tomorrow assuming it's approved.  I don't figure this is _that_ bad to do-- we don't have millions of people searching for this-- and this way I won't turn on side-loading on my phone and will get a more authentic end-user experience.

**Comment by mlyle** [comment]
Extended to fix crashes in core functionality due to our changes to telemetry/object persistence.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
edited jenkins config-- build androidgcs in both release and debug config.

jenkins, build artifacts please

**Comment by mlyle** [comment]
:( jenkins, build artifacts please

**Comment by mlyle** [comment]
Jenkins, build artifacts please

Ultimately we need infrastructure to auto-increment version numbers here...

**Comment by mlyle** [comment]
#1330 opened for followup work

**Comment by jhitesma** [comment]
Installed from App store on my Galaxy S7.   Used the OTG adapter that came with the phone.

Airbot revo acro with #1250 connected, but couldn't do much of anything due to UAVO mismatch.

DTFc on 74b7422c (Samsara.1) - won't connect.  Says "attempting USB HID connection" then nothing more.  Phone does recognize what's connected and offered GCS app, just can't connect.  Tried with and without battery.

Sparky on 85af0a4a (I don't even remember what this build was) - same as DTFc

Sparky updated to Samsara.1 - Got "Failed To Connect" first try.  Second try connected and "worked".

Sparky2 on Samsara.1 - Connected and "worked" no issues.

Man, I forgot what a mess this app is.  The Tuning screen is really confusing with the values in scientific notation in some places and labels on the sliders that don't make immediate sense to me.  Browser is functional but not very user friendly.  "Tablet Control" causes spectacular freeze crash.  Map worked.  

Didn't try actually updating any settings yet since the UI is just so user hostile.  But will give that a try in a bit.

**Comment by jhitesma** [comment]
Also tried on Naze32 running Samsara.1  No connection with HID or Serial.  Phone doesn't recognize it when I plug it in and doesn't offer to start the app like it does on other boards either.

**Comment by jhitesma** [comment]
Brain (original) on Samsara.1 - worked as well as any others.  Tried changing some settings in the browser and they updated and stuck no issues.

**Comment by mlyle** [comment]
> DTFc on 74b7422 (Samsara.1) - won't connect. Says "attempting USB HID connection" then nothing more. Phone does recognize what's connected and offered GCS app, just can't connect. Tried with and without battery.

There's one wonky thing that you may be hitting here-- it tries to connect to the bootloader, too.  So if you click 'connect' before it's into the main firmware it won't work, requiring a disconnect and reconnect.  (DTFc pauses for longer for bootloader because of another bug).

**Comment by mlyle** [comment]
Nah, nevermind, dtfc won't presently work

**Comment by dustin** [comment]
I tried quanton on my N7 with a USB OTG cable.  Said it was going to attempt to connect, but I never got any further information telling me what was happening.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
This is as good as it's gonna get for now.

image

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
I think this would work pretty well if it didn't get confused by the bootloader.

**Comment by tracernz** [comment]
Ready to merge? Unless there are some Java/Android devs around we can't really review it properly so test is good enough. :grimacing:

**Comment by mlyle** [comment]
Yes, ready to merge IMO, especially since we're shipping it on the store in the current state.

**Pull request merged**
