### PR TITLE
packagework2: get packaging subsystems ready for tech preview 2

### PR DESCRIPTION
**Pull request by mlyle**
Work towards #284 preview release 2.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/289)

### CODE REVIEW

**Comment by mlyle** [comment]
Installer works well on Windows.

**Comment by mlyle** [comment]
Issue: zip paths on windows are all absolute and include build environment details (from package_all_compress)

Minor issue: package_all_compress includes windows installer if installer was built previously -- #217 would fix

**Comment by mlyle** [comment]
OSX works but icon placement on dmg is now bad.

**Comment by mlyle** [comment]
Icon for OSX package also bad

**Comment by mlyle** [comment]
This is slightly garish now but better than nothin'

dronosx

**Comment by mlyle** [comment]
OSX package good, now.

**Comment by dustin** [comment]
The background image needs like, props and gates and stuff.  Maybe some
waypoints.

**Comment by mlyle** [comment]
@varcht's thing that we use as a banner on facebook could potentially be coerced to work...  Can get fixed after this merges down.

**Comment by mlyle** [comment]
fixes #213

**Comment by mlyle** [comment]
I like this command:  `GCS_BUILD_CONF=release make -j4 all package_flight && make package_all_compress && make installer`

**Comment by mlyle** [comment]
latest version, with #289:
package_all_compress good on Linux. 
package_installer / deb good from command line on ubuntu 14.04.
package_installer / deb good from launcher on ubuntu 14.04

**Comment by mlyle** [comment]
latest version, with #289:
package_all_compress good on Windows
package_installer good on windows.

Black icon sometimes troublesome on both windows and linux (need to consider transparent ghosting for it too)

**Pull request merged**
