### PR TITLE
Naze32: Attempt retry with alternate EXTI config on failed MPU init

### LINKED ISSUE #938: Afromini Amaze boot failure
In the latest code, the Afromini Amaze (looks like a naze32, but with the interrupt on a different port) fails to initialize and hangs to the point where you can't talk to it via GCS.

So far, the following works around it just fine and gets it working, but other, narrower attempts haven't been successful.

```
diff --git a/flight/PiOS/Common/pios_mpu.c b/flight/PiOS/Common/pios_mpu.c
index ae07e4f..f51e348 100644
--- a/flight/PiOS/Common/pios_mpu.c
+++ b/flight/PiOS/Common/pios_mpu.c
@@ -421,11 +421,13 @@ static int32_t PIOS_MPU_Common_Init(void)
    /* Set up EXTI line */
    PIOS_EXTI_Init(mpu_dev->cfg->exti_cfg);

+#ifdef THIS_BOARD_SHOULD_NOT_BOOT
    /* Wait 20 ms for data ready interrupt and make sure it happens twice */
    if ((PIOS_Semaphore_Take(mpu_dev->data_ready_sema, 20) != true) ||
        (PIOS_Semaphore_Take(mpu_dev->data_ready_sema, 20) != true)) {
        return -PIOS_MPU_ERROR_NOIRQ;
    }
+#endif

    mpu_dev->task_handle = PIOS_Thread_Create(
            PIOS_MPU_Task, "pios_mpu", PIOS_MPU_TASK_STACK, NULL, PIOS_MPU_TASK_PRIORITY);
```

### PR DESCRIPTION
**Pull request by tracernz**
Should make Afromini Amaze work. Completely untested, but compiles. Please test @dustin.

Fixes #938

### CODE REVIEW

**Comment by tracernz** [comment]
P.S. I'd like to remove the Mpu6050IntPin field as part of this PR if it's successful.

**Comment by mlyle** [comment]
Shouldn't be part of this PR, since we probably want this to be one of two hotfix items and changing uavos in a hotfix is bad.

**Comment by tracernz** [comment]
Fair enough.

**Comment by dustin** [comment]
Two blinks.  Does not communicate with GCS.

**Comment by tracernz** [comment]
Yah, EXTI init fails the second time round. Got a fix that I need to clean up and push but the good news is that I have it working on my Amaze.

**Comment by dustin** [comment]
Oh good.  So many nazes. So difficult to tell them apart.

**Comment by tracernz** [comment]
@dustin Try now ;-)

**Comment by tracernz** [comment]
Works on my Rev. 5, Rev. 6, and Afromini Amaze.

**Comment by dustin** [comment]
Neat.  Fresh flash on the Amaze:

dronin_gcs

**Pull request merged**
