### PR TITLE
sim: cross-compile improvements and sample rate hack

### PR DESCRIPTION
**Pull request by mlyle**
If you install gcc6, on some distributions the compiler name is
arm-linux-gnueabihf-gcc-6 ... probe for this and use gcc6 if possible,
else fall back to arm-linux-gnueabihf-gcc.

### CODE REVIEW

**Comment by mlyle** [comment]
This last commit greatly reduces event system warnings on flyingpi and also seems to cure the every-other-message-bad phenomenon.

**Comment by mlyle** [comment]
Successful flight test with these changes.

**Comment by tracernz** [comment]
Shouldn't we prefer gcc5 since that's what we compile regular flight firmware with? :stuck_out_tongue: I'm also fine with this though, and we should probably decide if we want gcc6 for arm-none-eabi.

**Comment by mlyle** [comment]
> I'm also fine with this though, and we should probably decide if we want gcc6 for arm-none-eabi.

Yes.  I've been waiting for the 2nd release on the 6 series, and it just shipped.  https://launchpad.net/gcc-arm-embedded/6.0/6-2017-q1-update

**Comment by tracernz** [comment]
Great. :+1: Downloads: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

**Comment by mlyle** [comment]
Heh all those downloads:

```
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:0cda9ee9-0001-00c1-6128-920c81000000 Time:2017-03-01T01:07:48.3497287Z
</Message>
</Error>
```

**Comment by tracernz** [comment]
Great, first party support not always the best huh? No way to contact them about it either AFAICT.

**Comment by mlyle** [comment]
Looks like there's this at least https://bugs.launchpad.net/gcc-arm-embedded/+bug/1668379

**Pull request merged**
