### PR TITLE
flyingf4: remove target

### LINKED ISSUE #97: discussion: remove flyingf4?
Cons-- there's some users out there, it's cheap
Pros-- it's difficult to set up (no sensors onboard unlike flyingf3), using user USB is problematic, Voh is problematic.

### PR DESCRIPTION
**Pull request by mlyle**
not even compiled yet, just throwing this up here.

fixes #97

### CODE REVIEW

**Comment by mlyle** [comment]
discoveryf4 is left in because i have some plans for this for automated integration test.

**Comment by fujin** [comment]
aww lol I was just helping @jhitesma with his the other day! LGTM though. :+1:

**Comment by mlyle** [comment]
I'm sending him a sparky because flyingF4 is cursed.

**Comment by jhitesma** [comment]
Your help was much appreciated @fujin!  Even if flyingF4 is dead I learned a lot from messing with it and from your help.  

So much for my flying4f_mess branch though...guess the name was better than I expected :D

**Comment by dustin** [comment]
I approve of this message.

**Pull request merged**
