### PR TITLE
pios_video/brain: correct pixel timer threshold

### LINKED ISSUE #1518: Brain hanging on boot
* Seen in version (release version or githash): e55cc1bb09ca16d1fad1c2733d963e2fe396705b
* On flight controller (if applicable): Brain

Issue details:

No OSD at boot.   Can arm, but automatically disarms ~1s into flight.

Note:  I bisected this which pointed to e55cc1bb09ca16d1fad1c2733d963e2fe396705b -- e55cc1bb09ca16d1fad1c2733d963e2fe396705b^ (efb7bc7) is fine.

### PR DESCRIPTION
**Pull request by mlyle**
May fix #1518, untried

### CODE REVIEW

**Comment by dustin** [comment]
👎 no boots

**Comment by dustin** [comment]
👍 seems OK now.  Something ate my config during upgrade and caused all kinds of things to be broken.

**Comment by mluessi** [comment]
Verified working with an NTSC camera. Thanks @mlyle!

**Comment by mluessi** [comment]
See also #1521

**Pull request merged**
