### PR TITLE
taskinfo/modules: make case/naming consistent for frsky stuff

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by tracernz** [comment]
Did you shorten the name to SBridge rather than SensorHubBridge intentionally? I think it will be more confusing with SBridge and SPortBridge.

**Comment by mlyle** [comment]
Could change the other way, but it's 4 places to change it that way vs. 2 this way (they were mixed).

**Comment by mluessi** [comment]
I would prefer `SensorHubBridge`, as `SBridge` could also mean `SPortBridge`..

**Comment by jihlein** [comment]
Agree with mluessi, SensorHubBridge is more descriptive.

**Comment by mlyle** [comment]
Changed it the other way.

**Pull request merged**
