### PR TITLE
Make: Bump Qt to 5.5.1

### LINKED ISSUE #126: Consider updating to Qt 5.5.1 or 5.6
Even if we decide not to follow Qt 5.6, staying up-to-date on the 5.5 branch is still a good idea. Relevant changes:
- http://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.5.1
   * [QTBUG-46379] Tooltips on OS X are now transparent for mouse events.
 - [QTBUG-47775][Darwin] Fixed Info.plist creation when bundle name
   contains spaces.
 - ?
- http://code.qt.io/cgit/qt/qtquickcontrols.git/tree/dist/changes-5.5.1
- ?
- http://code.qt.io/cgit/qt/qtserialport.git/tree/dist/changes-5.5.1
   * [QTBUG-46875] Fixed crash while enumerating available ports
     on OS X 10.10
   * [QTBUG-47127] Available serial port information is not duplicated
     anymore on Windows.
- https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/dist/changes-3.5.1.md?h=3.5
 * Fixed crashes with code completion (QTCREATORBUG-14991, QTCREATORBUG-15020)
 * Added support for MSYS2 compilers and debuggers

### PR DESCRIPTION
**Pull request by tracernz**
For your consideration. I didn't note any issues but have done minimal with this so far.

Maybe plan to go to Qt 5.6 (and hopefully final Qt3D API) in post-Tanto?

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/486)

edit: mlyle: fixes #126

### CODE REVIEW

**Comment by tracernz** [comment]
Release announcement: http://blog.qt.io/blog/2015/10/15/qt-5-5-1-released/

Qt Changelogs:
qtactiveqt: http://code.qt.io/cgit/qt/qtactiveqt.git/tree/dist/changes-5.5.1 
qtbase: http://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.5.1
qtconnectivity: http://code.qt.io/cgit/qt/qtconnectivity.git/tree/dist/changes-5.5.1
qtlocation: http://code.qt.io/cgit/qt/qtlocation.git/tree/dist/changes-5.5.1
qtmultimedia: http://code.qt.io/cgit/qt/qtmultimedia.git/tree/dist/changes-5.5.1
qtquickcontrols: http://code.qt.io/cgit/qt/qtquickcontrols.git/tree/dist/changes-5.5.1
qtsensors: http://code.qt.io/cgit/qt/qtsensors.git/tree/dist/changes-5.5.1
qtserialport: http://code.qt.io/cgit/qt/qtserialport.git/tree/dist/changes-5.5.1
qtwebengine: http://code.qt.io/cgit/qt/qtwebengine.git/tree/dist/changes-5.5.1
qtwinextras: http://code.qt.io/cgit/qt/qtwinextras.git/tree/dist/changes-5.5.1

Qt Creator changelog: https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/dist/changes-3.5.1.md?h=3.5

**Comment by tracernz** [comment]
@mlyle: any chance we can get 5.5.1 on jenkins?

**Comment by mlyle** [comment]
Yah, we've got the hotfix out and are happy.  Soon hopefully for both of these tool things.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
Note unfortunately with how this works this requires a cutover in the .bash_profile on the windows builder unless we're exceptionally clever.  (which will break building old source).

**Comment by tracernz** [comment]
We will "break" old source anyway assuming there are regressions caused by upgrading Qt. What's your idea?

**Comment by mlyle** [comment]
No idea really, just a note that we will be unable to automatically build old code after this is done "for real".

(The windows toolchain switching is good on the ARM tools so it doesn't have this weakness-- as is the QT switching on all other platforms).

**Pull request merged**
