### PR TITLE
gcs: connmgr: only pop up error dialog on manual connect

### PR DESCRIPTION
**Pull request by mlyle**
Connects to #821

---

This change is [Reviewable](https://reviewable.io/reviews/d-ronin/dronin/836)

### CODE REVIEW

**Comment by tracernz** [comment]
Is there a reason manual connect should be any different? It seems the me that this is just masking an underlying issue which applies to both manual and automatic connections?

**Comment by mlyle** [comment]
@tracernz: It's pretty frequent to get jittery-enumeration and the failure message e.g. I see this 1 out of 5 times pulling a USB cable on my mac laptop, which I assume is from losing and gaining electrical contact.

There's similar things during reset sequences, too, which may be our fault in the firmware somehow, or may be the fault of the individual hardware -- some people tend to get enumerate, disappear, enumerate sequences on Windows.

**Comment by mlyle** [comment]
tested by @droidicus -- not regressed, at least.

**Comment by mlyle** [comment]
@pug398 tested a branch with this and likes the results

**Comment by mluessi** [comment]
Thanks!

**Pull request merged**
