### PR TITLE
Additional UAVO descriptions

### PR DESCRIPTION
**Pull request by yamahabest**
Filled descriptions as far as I could.
Not all are filled yet, those can be found by searching for "< description / >" (without spaces)

### CODE REVIEW

**Comment by mlyle** [comment]
@yamahabest I'll be pushing some commits into this to clean it up.

Can you please share how you did the reformatting so that I can look at clean diff / ensure future stuff is formatted this way?

**Comment by mlyle** [comment]
Deferred.  This needs to get fixed up properly and it's not possible to review with the indentation changes etc.

Suggested strategy might be-- reformat next release using the same procedure in a separate PR. Then take the diff piece by piece and apply it in.  Then fix up any remaining things missing descriptions.

**Comment by tracernz** [comment]
Yep, I'm willing to have another go at some kind of tool to generate canonical UAVO defs next cycle. Then we can remove all the legacy stuff from UAVOGen.

**Comment by yamahabest** [comment]
Hope this helps.
The tool I used (Notepad++ with XML Tools plugin, "pretty print" (Ctrl+Alt+Shift+B)) changed the 4 spaces indentation to tabs everywhere.

The indentation is a mess throughout the files. Some places spaces, some places tabs, even within files.

It is a shame though that github can't do in-line compares, that would make this a easier ("ignore whitespace changes").

**Comment by mlyle** [comment]
Superseded #1400

**Pull request closed without merging**
