### PR TITLE
Package:Linux: Fix udev rules not included in tar

### PR DESCRIPTION
**Pull request by tracernz**
*sigh*

(untested)

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
On road.  Yuck.  For now can we put it somewhere and kludge relnotes?  Seems better than hotfixing to include one file.

**Review by mlyle — APPROVED** [review]
Untested, looks sane

**Comment by tracernz** [comment]
Tested this and it works correctly.

> On road. Yuck. For now can we put it somewhere and kludge relnotes? Seems better than hotfixing to include one file.

Added as a release asset, and amended relnotes as appropriate.

**Comment by mlyle** [comment]
Thx, I think that's the best way (avoid the risk of cutting new artifacts).

**Comment by tracernz** [comment]
Tagged this as hotfix so it will show up for inclusion if we end up doing one later.

**Pull request merged**
