### PR TITLE
quanton/coptercontrol: fix serial telemetry

### LINKED ISSUE #317: CC3D:Telemetry on flex port not functional
Testing bluetooth on flex port at 57k

### LINKED ISSUE #319: Quanton:Telemetry on default uart4 not functional
Testing with xbee at 57k. Possibly related to #317

### PR DESCRIPTION
**Pull request by mlyle**
meh.  

I confirmed the other targets and none others have these issues.

Fixes #317 
Fixes #319 

Untested, but straightforward-- just like #267.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/320)

### CODE REVIEW

**Comment by mluessi** [comment]
LGTM. @pug398 do you mind testing this on quanton?

**Comment by mlyle** [comment]
Unfortunately @pug398 doesn't build.  I'm doing a few things for him, so if this requires test to merge I can look at including it in a package of a few things for him.

**Comment by tracernz** [comment]
Confirmed broken on next and fixed with this PR on Quanton.

Doesn't work on CC3D, board config plugin doesn't allow disabling Telemetry on USB and editing the UAVO in the browser still results in Telemetry being on HID.

**Comment by mlyle** [comment]
@tracernz-- were you trying CDC?  This isn't intended to change anything with CDC, but rather just communications out flexi/main when USB is disconnected.  Use case was an xbee/bluetooth module or whatever

**Comment by tracernz** [comment]
So turns out it's not possible to disable USBTelemetry on CC (we should fix that, it works on other targets). I powered from an external source and successfully tested telemetry on the flexiport.

**Pull request merged**
