### PR TITLE
GCS Branding, and main fixes

### PR DESCRIPTION
**Pull request by PTDreamer**
This PR externalizes GCS artwork and strings so rebranding is easier and also make it simpler to avoid conflicts across forks.
EDIT: So this in practice makes the branding artwork and strings move outside the gcs src directory and to the REP_SOURCE/branding directory. The placement is so in the future it can also be used by the packaging stuff.
It also fixes main and refactors main. The command line options are now using QCommandLineParser and examples are included for both argument passing to plugins and plugin tests using QTest.
Heavy rebasing was needed so please review with caution.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/181)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
@ptdreamer I sent you an organization invite because this is how Jenkins permissions are maintained.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by PTDreamer** [comment]
> @ptdreamer I sent you an organization invite because this is how Jenkins permissions are maintained.

Ok, thanks.

Just forced push again sorry, some unrelated commits slipped through the rebase.

**Comment by PTDreamer** [comment]
not ready for merging

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by PTDreamer** [comment]
please remove the WIP label, should be ready for review

**Comment by mlyle** [comment]
Reviewed 359 of 380 files at r1, 306 of 312 files at r2, 7 of 8 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ground/gcs/gcs.pri, line 66 \[r4\]](https://reviewable.io:443/reviews/d-ronin/dronin/181#-K4yzyS4VMvoG80wevsI:-K4yzyS4VMvoG80wevsJ:70228941) ([raw file](https://github.com/d-ronin/dronin/blob/78557ff2f18a47a74f6db0edfdc821a38fc5b566/ground/gcs/gcs.pri#L66)):*
Should be GCS_PROJECT_BRANDING_PRETTY here and in all files

---

*[ground/gcs/src/plugins/coreplugin/versiondialog.cpp, line 109 \[r4\]](https://reviewable.io:443/reviews/d-ronin/dronin/181#-K4z06HnzV9vDFeNFmFZ:-K4z06HnzV9vDFeNFmF_:115153864) ([raw file](https://github.com/d-ronin/dronin/blob/78557ff2f18a47a74f6db0edfdc821a38fc5b566/ground/gcs/src/plugins/coreplugin/versiondialog.cpp#L109)):*
This one is probably not OK because it drops the Tau Labs copyright notice.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/181)*

**Comment by mlyle** [comment]
Reviewable really struggled on this one, unfortunately :/

**Comment by PTDreamer** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[ground/gcs/gcs.pri, line 66 \[r4\]](https://reviewable.io:443/reviews/d-ronin/dronin/181#-K4yzyS4VMvoG80wevsI:-K4z2OR5CE2Ind7RPyRY:795135230) ([raw file](https://github.com/d-ronin/dronin/blob/78557ff2f18a47a74f6db0edfdc821a38fc5b566/ground/gcs/gcs.pri#L66)):*
Bahhh. Have to get my self a spelling checker for my code. Will fix

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/181)*

**Comment by mlyle** [comment]
I found one more thing, plugins/coreplugin/dialogs/importsettings.ui:14

Optional to fix for this.

So far looks good (tried it on Mac OS X) but I'm going to need to get through Windows and Linux too.

**Comment by PTDreamer** [comment]
*[ground/gcs/src/plugins/coreplugin/versiondialog.cpp, line 109 \[r4\]](https://reviewable.io:443/reviews/d-ronin/dronin/181#-K4z06HnzV9vDFeNFmFZ:-K4z4v_9d0rZBxX67F7q:160371012) ([raw file](https://github.com/d-ronin/dronin/blob/78557ff2f18a47a74f6db0edfdc821a38fc5b566/ground/gcs/src/plugins/coreplugin/versiondialog.cpp#L109)):*
Ack

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/181)*

**Comment by mlyle** [comment]
Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/181)*

**Comment by mlyle** [comment]
Clang complains on OSX:

```
/Users/mlyle/dronin/ground/gcs/src/plugins/coreplugin/versiondialog.cpp:109:2: error: 
      invalid argument type 'const char *' to unary expression
 -       "Copyright %0 %1, 2012-2015 Tau Labs, 2010-2012 OpenPilot. All rights reserved.<br/>"
 ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

(minus at beginning of line)

**Comment by PTDreamer** [comment]
> Reviewable really struggled on this one, unfortunately :/

Not only reviewable but also my browser :) . Opened an issue with them requesting an option to hide renamed/moved files from the diff which is a big part of this PR.

**Comment by mlyle** [comment]
> Not only reviewable but also my browser :) . Opened an issue with them requesting an option to hide renamed/moved files from the diff which is a big part of this PR.

It seems really nice for .. middle-sized PRs.  Not really small ones, not huge ones.

**Comment by mlyle** [comment]
This is happy on Mac OS X.  Windows/Linux testing soon.

**Comment by mlyle** [comment]
Works well on Linux.

**Comment by mlyle** [comment]
Build fails on windows, looking:

```
C:/Users/mlyle/dronin/ground/gcs/src/app/main.cpp: In function 'void displayHelpText(QString)':
C:/Users/mlyle/dronin/ground/gcs/src/app/main.cpp:95:47: error: 'appNameC' was not declared in this scope
     QMessageBox::information(0, QLatin1String(appNameC), t);
                                               ^
C:/Users/mlyle/dronin/ground/gcs/src/app/main.cpp: In function 'void displayError(const QString&)':
C:/Users/mlyle/dronin/ground/gcs/src/app/main.cpp:100:44: error: 'appNameC' was not declared in this scope
     QMessageBox::critical(0, QLatin1String(appNameC), t);
```

**Comment by mlyle** [comment]
Works on Windows with https://github.com/PTDreamer/dRonin/pull/1

**Pull request merged**
