### PR TITLE
flight:significant on screen display artificial horizon improvements

### LINKED ISSUE #530: OSD:  Should be able to align horizon
That is, the "virtual plane" and 0 datum for pitch/roll should be able to be moved downwards to compensate for camera tilt.

I suggest a cameratilt object in stabilizationsettings, which can be used for future enhancements in control reprojection.

### LINKED ISSUE #548: OSD should project horizon lines indefinitely
Not just limited to a narrow range of angles-- the ladder should go all the way around.

### LINKED ISSUE #549: OSD AI should respect position and size passed into it

### PR DESCRIPTION
**Pull request by mlyle**
Code clarity (though it's not perfect), infinite ladder, etc.

Allows one to specify camera tilt to align horizon lines.

Fixes #530 
Fixes #548 
Fixes #549

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/552)

### CODE REVIEW

**Comment by mlyle** [comment]
Selfie: 
0hfyxbi

**Comment by mlyle** [comment]
@hshred --- @ohmeye and others on IRC suggest we go for 15 deg spacing between "rungs".  AI in picture is set properly for camera, and is just a bit too busy IMO.

(or better yet, configurable, which the code is in better shape for.... but i don't really want to change the page UAVOs)

**Comment by mlyle** [comment]
er that should be @mluessi

**Comment by mluessi** [comment]
@mlyle thanks! I agree, 15 deg spacing would probably look better / less busy.

Code looks good to me. Do you want to change the spacing, after that I will test / merge.

**Comment by mlyle** [comment]
I think I'd prefer to leave as-is for this PR if that's OK.  UI and spacing should probably improve, but this is still better than before and at least compatible with old configs.

**Comment by mluessi** [comment]
Tested, thanks @mlyle!

**Comment by mlyle** [comment]
:) Thanks for the review and merge

**Pull request merged**
