### PR TITLE
uavsettings/upgrader: handle null settings well

### LINKED ISSUE #1697: Handling of upgrade of unitialized FC could be improved
Issue details:
When saving the "upgraded" settings, the GCS complains that it has no settings.
Only way to get out of the wizard is to abort.

If there are no settings, the last step of saving the "upgraded" settings can be omitted probably.

### PR DESCRIPTION
**Pull request by mlyle**
Now allow the user to "get out" after the dialog shows up.  Fixes #1697.

### CODE REVIEW

**Comment by mlyle** [comment]
This could be considered a bit of a hack, but if the return value is treated as whether the user has "completed the action" to the extent possible, it's sane.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
What does this do for the non-upgrader case? (harder to find that without a local checkout sorry)

**Comment by mlyle** [comment]
No one cares about the return value otherwise-- only upgrader.

**Review by tracernz — APPROVED** [review]
Thanks for checking. :+1:

**Pull request merged**
