### PR TITLE
GCS: Adds Select All/None buttons to UAV import dialog

### PR DESCRIPTION
**Pull request by jpbarraca**
In order to solve issue  #631 this patch will allow to rapidly select/deselect all settings loaded from a UAV file.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/655)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
Looks good apart from some minor cosmetic issues. Nice work.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[ground/gcs/src/plugins/uavsettingsimportexport/importsummary.cpp, line 52 [r1]](https://reviewable.io:443/reviews/d-ronin/dronin/655#-KAcSieNAGLhpkhxnm-r:-KAcSieNAGLhpkhxnm-s:833360272) ([raw file](https://github.com/d-ronin/dronin/blob/abd6f8dcee916af4fa6e1412ac54c9aa74348ca6/ground/gcs/src/plugins/uavsettingsimportexport/importsummary.cpp#L52)):_
remove space before semi-colon

---

_[ground/gcs/src/plugins/uavsettingsimportexport/importsummary.cpp, line 113 [r1]](https://reviewable.io:443/reviews/d-ronin/dronin/655#-KAcSg--jdi24WUpUajf:-KAcSg--jdi24WUpUajg:-1474058039) ([raw file](https://github.com/d-ronin/dronin/blob/abd6f8dcee916af4fa6e1412ac54c9aa74348ca6/ground/gcs/src/plugins/uavsettingsimportexport/importsummary.cpp#L113)):_
space around =

---

_[ground/gcs/src/plugins/uavsettingsimportexport/importsummary.cpp, line 114 [r1]](https://reviewable.io:443/reviews/d-ronin/dronin/655#-KAcSd2uOWv5xXCl8cWa:-KAcSd2uOWv5xXCl8cWb:-455036654) ([raw file](https://github.com/d-ronin/dronin/blob/abd6f8dcee916af4fa6e1412ac54c9aa74348ca6/ground/gcs/src/plugins/uavsettingsimportexport/importsummary.cpp#L114)):_
space after comma

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/655#-:-KAcSscsdsCx0GOllS7c:251084920)_

**Comment by tracernz** [comment]
Apologies for the slow review.

**Comment by tracernz** [comment]
:lgtm_strong:  Tested good.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/655#-:-KAi4l6-lz6vU3VFDPTM:-720490225)_

**Pull request merged**
