### PR TITLE
sparky: get serial telemetry working again

### PR DESCRIPTION
**Pull request by mlyle**
Fix regression spotted by @jhitesma that occurred in
taulabs/taulabs#1982 .

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/267)

### CODE REVIEW

**Comment by jhitesma** [comment]
Able to get a connection with this fix.  But RX only.  PFD responds but never get a link.

**Comment by mluessi** [comment]
What @jhitesma is observing sounds like TauLabs/TauLabs#1418. Can you try increasing the `.bInterval` (e.g. 8ms) and see if it fixes things? Using 1ms on F4 targets was working fine for me but stopped working when I updated my laptop to a 4.X Linux kernel. Users seeing this problem on Windows can sometimes fix it by switching to the "high performance profile".

**Comment by mluessi** [comment]
Wait, this is for serial telemetry, not USB. Maybe we have a race condition in the telemetry module or something?

**Comment by mluessi** [comment]
@mlyle how does this fix things? Isn't it just renaming a variable?

**Comment by mlyle** [comment]
@mluessi PIOS_HAL directly writes to pios_com_telem_serial_id for serial telemetry-- rf_id is for actual RF links.  Various older targets abused this, so this is part of the necessary change for PIOS_HAL.

**Pull request merged**
