### PR TITLE
picoC: Add alarm status for battery levels

### PR DESCRIPTION
**Pull request by henn1001**
Self-explanatory. 
Helps cleaning up picoC scripts in combination with the cell autodetection. :)

I´ll also update the wiki once this is merged.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/583)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
Looks good.  Can you please update the copyright and the last paragraph of the license from the LicenseTemplate.txt header and I'll merge?

**Comment by henn1001** [comment]
Like this?

**Comment by mlyle** [comment]
jenkins, test this please

Yes, exactly like that.

**Comment by henn1001** [comment]
*wiki updated

**Pull request merged**
