### PR TITLE
flashfs: move CRC to end of slot

### LINKED ISSUE #1084: System settings not saving on F1 and F3 targets
- Seen in version (release version or githash): 5fa45f2
- On flight controller (if applicable): SciSky, Sparky, Naze32Pro_, F3FC_, AQ32, BrainRE1, Quanton

Issue details: Unable to save any settings on F1 or F3 based targets.  After clicking on save, rather than returning a green checkmark, it returns a red x.  Settings are not saved, and heartbeat LED stops flashing.  

F4 boards work as expected, settings are saved and a green checkmark is immediately returned,

The two boards marks with \* are on my off tree branch, rebased to 5fa45f2, and exhibit the same problem.

Loading the Tanto release results in all targets functioning properly.

### PR DESCRIPTION
**Pull request by mlyle**
To not trigger alignment problems on F3.

Fixes #1084

### CODE REVIEW

**Comment by mlyle** [comment]
Untested so far.

**Comment by mluessi** [comment]
LGTM

**Comment by mluessi** [comment]
@mlyle can you test this? I don't have an F3 target to test. I suspect that #1084 is caused by this (i.e. `next` is currently broken).

**Comment by jihlein** [comment]
@mluessi just did a quick patch to my local build of next.  I can firm Sparky now works correctly.  Need to rebuild the whole branch and then I'll give the other targets a test.

**Comment by jihlein** [comment]
@mluessi, @mlyle, confirmed that SciSky, Sparky, Naze32Pro_, F3FC_, AQ32, BrainRE1, and Quanton all save settings correctly with this PR.  Didn't fly any of them, but all saved and recalled settings as expected.

**Comment by mlyle** [comment]
Yes, next is currently broken by this-- this is why it is marked blocker.

**Pull request merged**
