### PR TITLE
UAVOMSPBridge: Fix altitude and GPS speed scaling

### LINKED ISSUE #1023: UAVOMSPBridge sends altitude with wrong sign on F3/F4, Speed scaling wrong
Sends PositionActual.Down as altitude, which is opposite direction to MSP protocol and what MWOSD expects. See ShikOfTheRa/scarab-osd#245

https://github.com/d-ronin/dRonin/blob/014d78244bc98f566394e4d8f56c1fe3ac202255/flight/Modules/UAVOMSPBridge/UAVOMSPBridge.c#L461

MSP_RAW_GPS message specifies GPS_speed in cm/s whereas we send the value from GPSPosition.Groundspeed directly which is in m/s, needs multiplied by 100.

See MSP protocol spec: http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol

### PR DESCRIPTION
**Pull request by tracernz**
Flip sign on altitude (MSP wants Up, PositionActual UAVO is NED), scale GPS speed correctly (MSP wants cm/s, GPSPosition has m/s). Not tested.

Fixes #1023

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Looks great.

**Comment by cpusmith** [comment]
Just an FYI - the speed and altitude now work as tested.

**Comment by mlyle** [comment]
@cpusmith thanks for the followup :)

**Pull request merged**
