### PR TITLE
BrushedSparky: check in schematic for production version

### PR DESCRIPTION
**Pull request by mlyle**
This is essentially a modified Sparky2 with the addition of VTX
circuitry and replacing some of the PWM outputs with power FETs
to drive external motors.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
Missing gerbers and BOM. :-P Even if the gerbers aren't checked in it would be nice to have the BOM for repair purposes in combination with the assembly drawings. @peabody124

**Comment by tracernz** [comment]
Hardware design looks good, the SPort inverter is a nice addition, shame it didn't make it to the Sparky2.

**Comment by mlyle** [comment]
This one is trivial and doesn't need CI.  Mergin'.

**Pull request merged**
