### PR TITLE
gcs: performance/correctness: use const in foreach

### PR DESCRIPTION
**Pull request by mlyle**
Don't copy UAVO information so much.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/254)

### CODE REVIEW

**Comment by mlyle** [comment]
It seems like some of this could end up copying the entire data structure of UAVOs for most UAVO accesses.  Also puts the allocator through a lot of work.

**Comment by mlyle** [comment]
Makes the GCS noticeably snappier in test.

**Comment by PTDreamer** [comment]
This is great but unexpected. Most of the classes handled are shared implicitly which means that a new object is only created if written to.
http://doc.qt.io/qt-5/implicit-sharing.html

**Comment by mlyle** [comment]
While not all contents of the object might not get copied if it's a Q container or other implicitly shared object, there's still a shim object allocated/constructed for each one if it's not handled with a const reference.  We have 120 UAVOs, so each Get triggers this about 60 alloc/constructors/deletes.

**Comment by tracernz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/254)*

**Comment by tracernz** [comment]
:lgtm_strong: Looks good, works well.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/254#-:-K5O4pOOKhSH8D_-cGr5:1207925138)*

**Pull request merged**
