### PR TITLE
IBus Rx Driver

### LINKED ISSUE #988: FlySky i-bus protocol support
- Seen in version (release version or githash): 
  All
- On flight controller (if applicable):
  All

Issue details:
FlySky i-bus protocol is not available under serial port options. No FlySky i-bus protocol appears to be implemented. User with FlySky i-bus protocol radio only cannot make use of dRonin, requires switching to PPM or changing radio system.

### PR DESCRIPTION
**Pull request by tracernz**
First cut, totally untested, based on original baseflight implementation.

Needs:
- [x] Doxygen docs
- [x] Test on FlySky hardware
- [x] Added to more targets

Fixes #988

### CODE REVIEW

**Comment by mlyle** [comment]
Nice!  I've been asked about this a few times recently.

**Comment by fujin** [comment]
You're awesome @tracernz. :dancer:

**Comment by tracernz** [comment]
Started writing an RX packet generator firmware for STM32F4 Nucleo board. It can generate IBus packets which I have confirmed to some degree by testing with baseflight and cleanflight IBus implementations. Confirmed this implementation to work correctly with the generator (generating sine waves).

screenshot from 2016-05-14 14-20-12

Anybody got FlySky hardware to test? @bazyl78?

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
Tested on Sparky1, Naze32 and BrainFPV with my IBus generator board.

**Comment by tracernz** [comment]
Would be nice to get this in so I can rebase SRXL on top of it. Looks like it's already picked up some conflict I'll have to fix tonight.

**Comment by tracernz** [comment]
Rebased on next to resolve conflict. #1022 is waiting on this.

**Comment by tomasa73** [comment]
The link to the build with iBus support doesn't work. Also don´t find it in Jenkins, I'm interested to try it on a CC3D.

**Comment by tracernz** [comment]
Jenkins, build artifacts please

These should come back soon @tomasa73. Would really appreciate test!

**Comment by tomasa73** [comment]
Great! I´ve downloaded the software and will install fw later today. Will report back results.

**Comment by tomasa73** [comment]
The Tx wizard fails on the "Center all sticks" stage. No input is detected. So the wizard fails. Also not possible to do a manual setup.

**Comment by tomasa73** [comment]
I fiddled around a bit and managed to do a manual setup of the tx. Succeded to allocate 8ch. I use the Flysky i6 with a 10ch custom firmware. Did a short and easy testflight, and it seemed ok. Will do more testflight later.

**Comment by tomasa73** [comment]
Have flied 3 lipos in stabilized mode..not comfortable in acro yet. It flies as it does with PPM/PWM. As for function, I would say yes. Is it possible to add the 2 extra channels ?

**Comment by tracernz** [comment]
Yes, can add the two extra channels. Will likely be a few days as I'm really busy at the moment.

**Comment by tracernz** [comment]
Rebased. I'll add the extra channels in a future PR to aid with merging this speedily (since 8 channel version is already tested).

**Comment by tomasa73** [comment]
Is the TX wizard in the GCS corrected in this version ?

**Comment by mlyle** [comment]
@tomasa73 I don't have hardware to test, but it really ought to work-- did you configure the port to ibus, then reset/reboot it before trying the tx wizard?

**Comment by tracernz** [comment]
@tomasa73 Thanks for your help with testing this. Let us know if you have any further issues with setup. You could also try #1050 which adds 10 channel support.

**Comment by tomasa73** [comment]
@mlyle Yes, I have restarted the FC several times. It´s just as that part of the wizard doesn´t recognize the input when the fc is using ibus. It works with PWM and PPM.

**Pull request merged**
