### PR TITLE
pios_video: eliminate line_counter

### PR DESCRIPTION
**Pull request by mlyle**
Test status: works on seppuku/pal

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
@hshred what do you think of this?

**Comment by mlyle** [comment]
@mluessi  --- what do you think of this?

**Comment by mluessi** [comment]
Doesn't seem to work with OG Brain for some reason. Tested with NTSC camera, CPU is at 100% with no OSD. Current next works fine.

**Comment by mlyle** [comment]
@hshred -- ahh i see one dumb bug that would have triggered with NTSC.

Fixed, but deferring for now.  Thanks for taking a look.

**Comment by mlyle** [comment]
@mluessi -- at this point please hold off on this change set, since it will conflict with #1640, and I see one thing that can be done better after doing #1640.   But it's been sitting for 2 months while I've been asking for your help with it...

**Comment by mlyle** [comment]
Superseded #1640

**Pull request closed without merging**
