### PR TITLE
gcs: simplify ccache usage

### PR DESCRIPTION
**Pull request by mlyle**
This formula works on Windows, too... lets the toplevel makefile to decide whether to ccache and where to find it.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/504)

### CODE REVIEW

**Comment by mlyle** [comment]
So far, this seems to work nicely.   I'm still going to poke at it a bit more.

A ccache.exe is at http://jar.lyle.org/~mlyle/ccache.exe   built from ccache-3.2.3 with a slight makefile tweak so zlib stuff could be found.

**Comment by mlyle** [comment]
`make -j4 all` on a slow windows VM was 10 mins 5 seconds hitting the cache.  Not great, but better than builds were before.

**Comment by tracernz** [comment]
Nice idea. If only it would work on OS X. ;-)

**Comment by tracernz** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/504#-:-K8hKUcb_-PJlvat_DO-:-1868698381)_

**Comment by mlyle** [comment]
I spent a few minutes looking at if there was any new developments or anything I could reasonably do... not really. (re: osx)

**Comment by droidicus** [comment]
Tested on Windows 10 with @mlyle provided ccache.exe above.
Before running make all_clean && make all -j4:

```
real    18m55.900s
user    0m0.015s
sys     0m0.016s
```

After running make all_clean && make all -j4 (after first run to load ccache):

```
real    4m49.475s
user    0m0.000s
sys     0m0.000s
```

Still about half the speed of the Linux VM I set up, but a significant speedup for sure.

**Pull request merged**
