### PR TITLE
flight: fix PPM input with PPM+OUTPUTS+ADC on quanton

### LINKED ISSUE #1483: PPM input pin does not work if PPM+OUTPUTS+ADC is chosen
* Seen in version (release version or githash): next
* On flight controller (if applicable): quanton

Issue details: if selecting PPM+OUTPUTS+ADC the PPM input pin does not work, with PPM+OUTPUTS the PPM input works as expected.

### PR DESCRIPTION
**Pull request by openha**
edit by mpl: fixes #1483

### CODE REVIEW

**Comment by openha** [comment]
Jenkins, build artifacts please

**Comment by openha** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, build artifact please

**Comment by mlyle** [comment]
@openha --- thanks very much for figuring this out.

Have you tested it and confirmed it fixes the problem and allows PPM to work?

**Review by tracernz — APPROVED** [review]
Looks good.

**Comment by openha** [comment]
No, I haven't tested it yet, could not manage to setup a build. Waiting for artifacts for this PR to test.

**Comment by mlyle** [comment]
jenkins, build artifacts please

I'm not good at typing lately :P

**Review by mlyle — APPROVED** [review]
:+1:

**Comment by mlyle** [comment]
@openha --- glad to merge as soon as you're happy with it / sure it works.  Thanks again.

**Comment by openha** [comment]
Confirmed, PPM input works with PPM+OUTPUTS+ADC, channel 9 and 10 tested for PWM output on correct pins and working. Thanks!

**Pull request merged**
