### PR TITLE
FlightGear: Fix build on macOS and Windows

### PR DESCRIPTION
**Pull request by tracernz**
Oops, merged FG too quick. :blush:

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Woops.  Thanks much for cleaning up.

**Comment by xfce** [comment]
Is there a UG about using FG with dronin?

**Comment by tracernz** [comment]
@xfce No, this is brand new code written a week ago: https://github.com/d-ronin/dRonin/pull/1805

**Pull request merged**
