### PR TITLE
flyingpio: set default to SBUS

### PR DESCRIPTION
**Pull request by mlyle**
This is a hack pending #1228, but at least stops my test rig from
repeatedly tripping over it.

### CODE REVIEW

**Comment by tracernz** [comment]
PPM seemed like a better default since it has much more universal support?

**Comment by mlyle** [comment]
It's just me using this, and ultimately either way it needs to be specified on the command line.

**Comment by tracernz** [comment]
Alright, any reason to target Quixote if it's just for you?

**Comment by mlyle** [comment]
Yes, so I can fly quixote builds on flyingpi without failing to make the receiver work each time :(

**Comment by tracernz** [comment]
Haha, okay, so we are not targeting general availability this cycle then? :stuck_out_tongue:

**Comment by mlyle** [comment]
Right now anyone who uses it has to compile it?  AKA cross-compiled for ARM is not in any artifacts.  You also have to build a kernel from our kernel source fork, etc, etc, etc.  There are a lot more things that have to happen to make this target turnkey-- having to edit this variable is the smallest of concerns...

**Comment by tracernz** [comment]
Alright, Artifice it is.

**Pull request merged**
