### PR TITLE
Autotune: Send compressed raw tune data to cloud

### LINKED ISSUE #1876: GCS/Autotown: Record tune sample data in Autotown
Would be nice to grab at very least the raw tune data (a few kb binary blob) and stick it in autotown as a blob (cloud storage, linked to the datastore entries we already do?). @dustin

### PR DESCRIPTION
**Pull request by mlyle**
Also display per-axis taus properly.

Fixes #1876

### CODE REVIEW

**Comment by mlyle** [comment]
Untested.

**Review by dustin — APPROVED** [review]
Seems fine.

Can we do an isolated test of what this might look in a bad case just to make sure there's not a column limit hidden somewhere?

I assume you're just using the normal API to extract it and don't need any other special support.

**Review by tracernz — APPROVED** [review]
Looks ok.

**Comment by mlyle** [comment]
http://dronin-autotown.appspot.com/api/tune?tune=ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAsPibygkM is a tune shared with this

**Comment by mlyle** [comment]
Added a couple of python commits --- including the jupyter notebook we've been passing around -- successfully pulls/processes the autotune directly from the tune API.

https://nbviewer.jupyter.org/github/mlyle/dronin/blob/mpl-tunedatasend/python/nb_autotune.ipynb

**Comment by mlyle** [comment]
This is the last remaining thing to merge before cutting a preview build.

**Pull request merged**
