### PR TITLE
gcs: Reformat

### PR DESCRIPTION
**Pull request by mlyle**
This did a few things I don't like, like:

```
 #ifdef Q_OS_LINUX
     QApplication::setAttribute(Qt::AA_X11InitThreads, true);
-    // This should have faster performance on linux
+// This should have faster performance on linux
```

But it's a vast improvement overall, I think.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Force-pushed: forgot about the templates.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Review by tracernz — APPROVED** [review]
:grin:

**Comment by tracernz** [comment]
Looks like the UAVO templates can do with some help (they have trailing whitespace etc.). Can clean them up later.

**Comment by mlyle** [comment]
Yah the formatter breaks them because they're not valid C++.  But I care about them a lot less-- they're not edited much etc.

**Pull request merged**
