### PR TITLE
gcs: usbmonitor_mac: fix lock model, work around dup devs

### LINKED ISSUE #792: Multiple devices in bootloader state (spurious)
Seems to mostly happen on OSX.  Need to fix.

### PR DESCRIPTION
**Pull request by mlyle**
This is slightly hacky.

The hope: it largely fixes #792

---

This change is [Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/795)

### CODE REVIEW

**Comment by tracernz** [comment]
Plugged board in, it connected fine, click reboot, and it reboots but the BL device removed callback never comes... The dup device filter stops it from duplicating but it doesn't emit the signal so things don't happen like they normally would. Note, I have debug messages enabled and I added the `"Added: <serial>"` and `"Removed: <serial>"` messages where the device added/removed signals are emitted.

```
20:48:23[DEBUG]USBMonitor: Device attached event
20:48:23[DEBUG]USBMonitor: Adding device
20:48:23[DEBUG]Added:  "32001A001857334635343820+BL"
20:48:26[DEBUG]USBMonitor: Device detached event
20:48:26[DEBUG]Removed:  "32001A001857334635343820+BL"
20:48:26[DEBUG]USBMonitor: Device attached event
20:48:26[DEBUG]USBMonitor: Adding device
20:48:26[DEBUG]Added:  "32001A001857334635343820+FW"
20:48:26[DEBUG]Automatically opening device
20:48:26[DEBUG]ConnectionManager::devChanged autoconnected USB device
20:48:26[DEBUG][SystemHealth] Warning: The SystemHealth SVG does not contain a graphical element for the  "Geofence"  alarm.
20:48:26[DEBUG][SystemHealth] Warning: The SystemHealth SVG does not contain a graphical element for the  "GyroBias"  alarm.
20:48:27[DEBUG]Connection with the autopilot established
20:48:29[DEBUG]TelemetryMonitor: connected
20:48:29[DEBUG]ConfigGadgetWidget onAutopilotConnect
20:48:29[DEBUG]Checking object  "HwSparky"
20:48:29[DEBUG]ConfigGadgetWidget onAutopilotConnect
20:48:29[DEBUG]Checking object  "HwSparky"
20:48:41[DEBUG]USBMonitor: Device detached event
20:48:41[DEBUG]Removed:  "32001A001857334635343820+FW"
20:48:41[DEBUG]USBMonitor: Device attached event
20:48:41[DEBUG]USBMonitor: Adding device
20:48:41[DEBUG]Added:  "32001A001857334635343820+BL"
20:48:42[DEBUG]USBMonitor: Device attached event
20:48:42[DEBUG]USBMonitor: Adding device
20:48:42[DEBUG]Added:  "32001A001857334635343820+FW"
20:48:42[DEBUG]Automatically opening device
20:48:42[DEBUG]ConnectionManager::devChanged autoconnected USB device
20:48:42[DEBUG]Connection with the autopilot established
20:48:44[DEBUG]TelemetryMonitor: connected
20:48:44[DEBUG]ConfigGadgetWidget onAutopilotConnect
20:48:44[DEBUG]Checking object  "HwSparky"
20:48:44[DEBUG]ConfigGadgetWidget onAutopilotConnect
20:48:44[DEBUG]Checking object  "HwSparky"
```

**Comment by mlyle** [comment]
I see.  This is very helpful.  For now we can hack and just send the signal anyway, I think.

**Comment by tracernz** [comment]
I agree, going to try that right now.

**Comment by mlyle** [comment]
Hacked in here, now ZZZ for real.

(For consideration-- we might want to compare the prefix of the serial number not containing the +BL/+FW/+UP, emit a removal and remove that from the list if there's a duplicate).

**Comment by tracernz** [comment]
This appears to be an OSX bug, because the BL device goes away in System Info but we never get a callback to say it's been removed.

**Comment by mlyle** [comment]
I believe the root cause of it not going away is because we still have it open.

**Comment by tracernz** [comment]
Good point.

**Comment by mlyle** [comment]
Yes-- I will fix it that way tomorrow.

(Only use serial number up to + to decide whether it's duplicate... remove existing one from list and emit removal [which will trigger close and real-removal].. then add to list and emit add like normal.)

**Comment by mlyle** [comment]
Tried that new approach here.

**Comment by tracernz** [comment]
Works around the underlying issue successfully. Merging.

**Pull request merged**
