### PR TITLE
NOTFORMERGE: autotune: hack to run in rate mode

### PR DESCRIPTION
**Pull request by mlyle**
For discussion.

### CODE REVIEW

**Comment by mlyle** [comment]
getting this thing in line
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by ufoDziner** [comment]
Completed 3 rate mode autotunes to carefully build up to my normal setup, and found nothing dramatically unsafe.  I videoed the last rate mode autotune with my phone, but don't have one to associate with the normal autotune.  The quad is setup identically for both of  these instances.  The tunes and video are listed below.

Normal autotune - https://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoMLDuwoM
Normal autotune video - https://youtu.be/kcY7X28wjfU

Rate mode autotune - https://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoM2uiwsM

**Comment by jhitesma** [comment]
I wonder if it would be worthwhile to find someone who's not having luck autotuning and have them try this.  

I'm kind of tempted to try and make some kind of build designed to not be autotunable.  Like single piece frame with hard mounted DTFc (due to the MPU-6000) and see if I can replicate bad "normal" tunes then try a rate only tune to see if it's better....

**Comment by ufoDziner** [comment]
Two more tunes on a different quad.  Identical configuration on each.

Rate mode version - https://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoM_lhwgM

Normal version - https://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoP7swQsM

**Comment by ufoDziner** [comment]
jenkins, build artifacts please

**Comment by jhitesma** [comment]
Gave it a try on my DTFc angle arm thing.  

Baseline tune on Samsara.1:  
http://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoMve6wgM

Acro only tune:
http://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoMve6woM

Only difference was that they were both flown on the same pack so Samsara had a full charge while acro only was slightly less than full charge.

Tunes both felt about the same to me...but @mlyle indicated that the second tune's beta's were moving in the wrong direction.

**Comment by mlyle** [comment]
Well, not the "wrong" direction, but the opposite direction that any change from this PR should do.

**Comment by jhitesma** [comment]
Was able to do another test of this on another airframe on Saturday:
http://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoK31yAsM

Not sure I like the look of those numbers compared to the previous "normal" tune on the same setup:
http://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICA4NC7xgoM

I did have a motor fall off between tunes and had to re-attach it...but the quad still seemed to be flying ok :)  The acro autotune was somewhat scarier this time though, it started very mild, in fact I didn't fully realized I was in autotune (I thought I still had an expoM build on here and forgot I had flashed this build to test) but a bit more than halfway through it got pretty violent and the oscillations got really large.  I was able to maintain control but started to get a bit worried.

FWIW this build is a flat frame, 230 CF build, I do have O-rings on the board.  My previous tests (and I believe @ufoDziner's as well) were all with angled motors.

**Comment by ufoDziner** [comment]
Just ran this on a DTFc built that I could not get normal autotune to work on, due to extreme oscillations even with lowered P and I.  I was able to get through the entire tune with no issues using 12/18 for P/I in the rate tune.  The tune it produced however, is unflyable.  I will try later with lower defaults to see if maybe it was still over tuned.

Produced tune: https://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAoJv1rQoM

**Comment by ufoDziner** [comment]
jenkins, build artifacts please.

**Comment by mlyle** [comment]
Superseded by other work.

**Pull request closed without merging**
