### PR TITLE
Watchdog: Change the order of task vs. watchdog initialization

### PR DESCRIPTION
**Pull request by mlyle**
The tasks run immediately after they are created, which means the watchdog
won't have been registered yet before it the UpdateFlag reset function is
called on it. The result was a crash.

This fixes the order of initialization.

---

This change is [Reviewable](https://reviewable.io/reviews/d-ronin/dronin/809)

### CODE REVIEW

**Comment by mlyle** [comment]
Both we (and they) were very sloppy here.

**Comment by mlyle** [comment]
Tests well.

**Comment by tracernz** [comment]
Hahaha. Will merge when Jenkins is done.

**Comment by kubark42** [comment]
Yup, should have tested it before pushing the `PIOS_ASSERT()` change. It seemed so logical at the time...

**Comment by tracernz** [comment]
Stuff happens, no harm done.

**Pull request merged**
