### PR TITLE
flash: eliminate disused "OTA" partition type

### PR DESCRIPTION
**Pull request by mlyle**
mentioned by @henn1001 

Deleting code is fun.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/704)

### CODE REVIEW

**Comment by tracernz** [comment]
What was it for?

**Comment by mlyle** [comment]
jenkins, test this please (restarted because of upgrades)

**Comment by mlyle** [comment]
Don't know.  Looks like it was introduced mid-2013 in c8ce8714d and never used.

**Comment by mlyle** [comment]
Tested on lux-- firmware still works, erasing firmware parts still works.

**Comment by dustin** [comment]
:lgtm: 

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/704#-:-KBfPFgH-8qrxEiBTLAw:980077423)_

**Pull request merged**
