### PR TITLE
gcs: dtfc: mark target as upgradable

### LINKED ISSUE #1077: Auto update on DTFc not working
- Seen in version (release version or githash): 85af0a4a
- On flight controller (if applicable): DTFc

Issue details:
Tried to update my DTFc now that it's in next.  Connected the board and it was detected and offered to update.  But when I hit "Yes" on update nothing happened.

Tried it on my Sparky next and it appeared to work...but after the final reboot board wouldn't connect.  Then tried my Sparky2 and Brain both of which worked as expected no issues.  Plugged the Sparky back in and it was detected as running 85af0a4a and I was able to re-load configs and get it working.  

But DTFc still doesn't update.  Detects but doesn't do anything after being detected and saying "yes"

Screencast of me trying to update the DTFc (and then sparky) here: https://youtu.be/zC4PHrKJgZ0

@tracernz said a debug log would help, but I need guidance on how to generate one.  Will also try a newer set of artifacts tonight to see if it's still happening.

### PR DESCRIPTION
**Pull request by mlyle**
fixes #1077

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
@jhitesma -- when this builds could you try it pretty please?

**Comment by jhitesma** [comment]
Upgraded my DTFc no issues.

**Comment by mlyle** [comment]
@jhitesma , @tracernz thx much

**Comment by DTFUHF** [comment]
Thanks for the fix guys :)

**Pull request merged**
