### PR TITLE
[WIP / FOR TESTING] Flight: adding gyro down-sampling & additional filtering functionality

### PR DESCRIPTION
**Pull request by Trex4Git**
I had now some time to setup dRonin build environment and rebase my old work from Taulabs to latest dRonin/next.

Detailed info and discussion is still there: https://github.com/TauLabs/TauLabs/pull/1781

Has someone tested this, or has some input for further work that should be done ?

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/713)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
I have not tested yet :/

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
what the.. it's building the wrong rev.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
what the... :(

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
tried upgrading ghprb to fix this; it didn't work at all, so had to downgrade.  problem still present.

**Comment by Trex4Git** [comment]
Maybe I made some mistakes.

But it compiled fine for me. Flashed it on Sparky2 and Quanton, and I also did not noticed problems at a quick check.

**Comment by mlyle** [comment]
Yes, for whatever reason jenkins likes building the wrong rev of this.  I can't figure out why.

**Comment by Trex4Git** [comment]
I created a new brach now from latest next, chery-picked the commits, and forced a push to github. 
Does it work now ?

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
Yes, it apparently builds the right thing now.  Very, very odd.

**Comment by mlyle** [comment]
Looks like the lux needs files added:

```
var/lib/jenkins/jobs/dron/workspace/Nodes/master/build/fw_lux/pios_mpu9250_spi.o: In function `PIOS_MPU9250_Task':
/var/lib/jenkins/jobs/dron/workspace/Nodes/master/flight/PiOS/Common/pios_mpu9250_spi.c:821: undefined reference to `cic_apply_higher_order_int_stage'
/var/lib/jenkins/jobs/dron/workspace/Nodes/master/flight/PiOS/Common/pios_mpu9250_spi.c:831: undefined reference to `cic_apply_comb_stage'
/var/lib/jenkins/jobs/dron/workspace/Nodes/master/flight/PiOS/Common/pios_mpu9250_spi.c:842: undefined reference to `cic_get_decimation_output'
```

**Comment by tracernz** [comment]
This clashes with one_true_mpu big time :(.

**Comment by Trex4Git** [comment]
@mlyle:
I wasn`t aware that there is a new target with a SPI connected MPU9250 (Lux).
So the cic.c must be included for Lux to fix this. And i can also make the other changes needed to enable this for the Lux.

Or should the Lux be excluded from this like the SmallF1 targets ?

@tracernz:
What do you mean with "one_true_mpu big time" ?

A global measured/calculated  "loop" time/update rate ?

**Comment by tracernz** [comment]
@Trex4Git #757 replaces the separate MPUxxx0 drivers with a common one that auto-detects which type of MPU is present.

**Comment by Trex4Git** [comment]
I think a common MPU Driver might be harder to maintain and also has some Overhead, especially for SmallF1 targets.

But if this will come, i might try to include this donwsampling also there.
Or if there is no further interest in the downsampling stuff, i can stop the work on it.

Edit:
Added changes for Lux.

**Comment by tracernz** [comment]
Not having a common driver is much more of a nightmare to maintain, with subtle differences between them despite being almost entirely the same. We would need multiple drivers on some F1 targets, since different revisions have different models of MPU, a much larger overhead.

**Pull request closed without merging**
