### PR TITLE
gcs: configurations: housekeeping

### LINKED ISSUE #352: Win 10 GCS Next crashes on startup
Running windows 10 on an older Alienware laptop.  Built a current "next", but am experiencing crashes on startup.  After the build, I navigated to build->ground->gcs->bin and double click on drgcs.exe.  The following is my git information, and a screenshot of the message I get when it crashes.

ufo@Wes-M11x MINGW32 ~/Documents/GitHub/dRonin ((2b9582a...))
$ git describe
preview-20151218-70-g2b9582a

gcs-crash

### PR DESCRIPTION
**Pull request by mlyle**
Adjust the stylesheets to have more common ground.  Fix #352 (I hope).  Needs test.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/365)

### CODE REVIEW

**Comment by mlyle** [comment]
Will try to test tomorrow.

**Comment by mlyle** [comment]
Tests fine.  Unable to repro #352 with this code.  @ufoDziner any chance you could test?

**Comment by ufoDziner** [comment]
Tested, and it fixed the issue.  Well done!

**Comment by mlyle** [comment]
@ufoDziner Cool, thank you!

**Pull request merged**
