### PR TITLE
PiOS:F3/F4: Remove FreeRTOS

### PR DESCRIPTION
**Pull request by tracernz**
- Removed FreeRTOS from all F3/F4 specific stuff. 
- Replaced FLASH_FREERTOS macro with `defined(PIOS_INCLUDE_FREERTOS) || defined(PIOS_INCLUDE_CHIBIOS)`

Relates to #169
Blocked on #166

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/505)

### CODE REVIEW

**Comment by tracernz** [comment]
As discussed on IRC, F4 done as well pending #166.

**Comment by tracernz** [comment]
Mmmmm. I wonder how #166 managed to build...

**Comment by tracernz** [comment]
Because the offending lines are newer, I guess I need to rebase it too then..

**Comment by mlyle** [comment]
Needs rebase and then hopefully we can speedily merge

**Comment by tracernz** [comment]
Rebased, let's see what Jenkins thinks.

**Comment by tracernz** [comment]
Uggghhhh... looks like I lost some commits here somewhere. I think my local branch on this machine must have been out-of-date :(.

**Comment by mlyle** [comment]
:(

**Comment by tracernz** [comment]
There are a few changes to simulation target, it was using static allocations for GCS receiver for ChibiOS and the disable IRQ functions were nops with ChibiOS. Hopefully these are now fixed and nothing has broken. Can you please test that @mlyle?

**Comment by tracernz** [comment]
Also, once F1 moves on we can get rid of the xHigherPriorityTaskWoken pattern throughout PiOS.

**Comment by mlyle** [comment]
Happy in sim.  Happy in bench test of flight boards.  Sane reviewed set of removed files.  Woot.

**Comment by tofly1990** [comment]
Hi,I have same questions that ChiBiOS will resulting in  reboot on my sparky2 board(used taulabs firmware),but FreeRtos is OK! is dRonin have same problem?

**Comment by tracernz** [comment]
We have fixed a few bugs in the ChibiOS shim over the last few months. Give it a try I guess.

**Comment by mlyle** [comment]
Yah, we have about 150 sparky2 boards using dRonin without any known reboot issues.

**Comment by tofly1990** [comment]
I play fixedwing with sparky2, it always reboot about one hour later; I will try it with dRoini firware, hope it works ok!!! Tankyou...

**Comment by mlyle** [comment]
@tofly1990 Yes, chibios targets had a bug that rebooted at 71.5 minutes / 4294 seconds-- we fixed that.

**Comment by tofly1990** [comment]
great!!!  I will test it .

**Pull request merged**
