### PR TITLE
modelview: change default gadget gemini->test quad x

### LINKED ISSUE #333: GCS: Change ModelView Gadget default model
Change the model from the Gemini model to something basic like 'Test Quad X'

### PR DESCRIPTION
**Pull request by mlyle**
Fixes #333

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/367)

### CODE REVIEW

**Comment by mlyle** [comment]
Still WIP; need to verify, just getting opened.

**Comment by mlyle** [comment]
Confirmed this works.  Also confirmed Gemini is 180 degrees off / should come out.

**Comment by mluessi** [comment]
Doesn't seem to work on Linux. It still shows the Gemini. Rebuilding the whole GCS and deleting the GCS config doesn't help.

**Comment by mlyle** [comment]
Hmm.. it works for me.  There's no more mention of the gemini in the GCS configs.

Any chance you have a system installation it's somehow using the config file from?

**Comment by mlyle** [comment]
(It does take deleting the GCS config though, for sure).

**Comment by mluessi** [comment]
Never mind, it works. I had deleted `~/.config/dRonin` instead  of `~/.config/dr`. When did we change the config directory? I think `~/.config/dr` is not ideal, as it may clash with some other software.

**Comment by mlyle** [comment]
@PTDreamer 's branding branch ended up doing it

**Pull request merged**
