### PR TITLE
pios_hal: frsky sport in noninverted, single wire mode

### PR DESCRIPTION
**Pull request by mlyle**
re: discussion in https://forum.dronin.org/forum/d/214-frsky-s-port-in-revo-hardware-tab/6

Needs verification.  Have only confirmed that this compiles-- no more.

### CODE REVIEW

**Comment by mlyle** [comment]
Only to merge if it attracts user interest / test.

jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Review by tracernz — APPROVED** [review]
Changes look good. Anybody tried this/want this?

**Comment by mlyle** [comment]
The artifacts are gone, don't know if the end user tried :P  This can sit until someone wants to try it or it accumulates conflicts, I guess.

@Dustin this isn't something you happen to want is it?

**Comment by mlyle** [comment]
jenkins, build artifacts please -- one last shot in case anyone wants to try

**Comment by pug398** [comment]
@mlyle this is for all F4 or just revo? I have a modded X4R-SB.

**Comment by pug398** [comment]
@mlyle Jenkins appears to be hung.

**Comment by mlyle** [comment]
@pug398 -- should be any F4.

I kicked Jenkins.. once again it has a big backlog :/  Need to figure out why Windows 10 likes hanging on the builder about once a week :/

**Comment by pug398** [comment]
@mlyle In trying this on a seppuku I have not been able to save any hardware changes to ports without the board resetting and changes not saved. After not being able to save s.port non inverted on any uart I tried complete erase and cannot save sbus on rcvr port either.

**Comment by pug398** [comment]
@mlyle whoops I am greatly mistaken. The buttons on the bottom of the hardware page are cut off with only the very tops showing. My bad memory thought the right most button was save but it is "reboot". I can say that button works very well :)

**Comment by pug398** [comment]
Looks like this is working. I have telemetry on the Taranis using single wire non inverted s.port on seppuku uart4.

**Comment by pug398** [comment]
@tracernz if you could shorten the message box on Seppuku hardware page I think the buttons would reappear.

**Pull request merged**
