### PR TITLE
GCS:Config: Add scroll areas around tabs to avoid squeezing

### PR DESCRIPTION
**Pull request by tracernz**
Fixes some annoying graphical issues in the modules and attitude tabs of config plugin.

Need to check a CI build to make sure I've got the right changes here because I had to do an interactive stage (mixed up some other stuff in my tree).

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
Jenkins seems ill. Built locally and tested, made another small tweak to the temperature plots on the gyro calibration page. Good to go now.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by mlyle** [comment]
Yay

**Pull request merged**
