### PR TITLE
Revo: Upgrade to ChibiOS, add some missing modules, rename

### LINKED ISSUE #204: Rename Revomini to Revolution
The OP Revolution target had been named Revomini, which is confusing to users as this name is largely unknown. I suggest we rename it to Revolution or maybe OP-Revolution.

### PR DESCRIPTION
**Pull request by tracernz**
Not flight tested yet, only brief bench test. Recalibrated the idle count for CPU load. Enabled some modules including flash logging which required re-jigging of the external flash partition table. I also added checks during init and LED panic codes.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/166)

mpl edit: fixes #204 connects #169

### CODE REVIEW

**Comment by tracernz** [comment]
I should really check that the bootloader hasn't suffered any regression..

**Comment by tracernz** [comment]
For interests sake I calibrated the idle counts/sec on FreeRTOS (proved to be pretty unnecessary), while the CPU load isn't exactly infallible the numbers still look good for Chibi:
```
ChibiOS:
HeapRemaining: 97888
CPULoad: 19%

FreeRTOS:
HeapRemaining: 90532
CPULoad 29%
```

**Comment by tracernz** [comment]
Merged @jihlein's renaming PR into this branch. I haven't reviewed it in any detail.

**Comment by mlyle** [comment]
This needs a rebase.  Since it includes a merge, you probably want git rebase -p upstream/next.  Maybe if it doesn't hate you, it'll do the right thing.

**Comment by tracernz** [comment]
Yeah, I'll do that when I'm at a PC, can probably wait until after the release anyhow.

**Comment by tracernz** [comment]
Rebased onto next.

**Comment by tracernz** [comment]
Rebased and fixed conflict.

**Comment by mlyle** [comment]
Sorry, there's conflicts again and a lot of total serialization needed :(

There's a minor coptercontrol->cc3d related conflict, and on kitchensink there's also a small conflict with my uavobjects change.

I'm pulling this into kitchensink (easy to merge these up myself) and will play with this.  Also will give review.

**Comment by mlyle** [comment]
Needs rebase :(

**Comment by tracernz** [comment]
Rebased hopefully for the last time. Had accumulated a lot of conflict in a short time.

**Comment by mlyle** [comment]
Wow, I swore I pushed the button on this earlier.  Guess not.

**Pull request merged**
