### PR TITLE
flight: althold: fix integral calculation, dT

### PR DESCRIPTION
**Pull request by mlyle**
Supersedes #633.  Code by @droney rebased-- some small edits to commit messages; last commit 'squashed'.

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/707)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by cpusmith** [comment]
Loaded above artifact on Sparky 2 and Sparky 1. Took off in Horizon mode, after stabilizing switched to to Alt hold mode. Performed side to side and forward backward maneuvers then flew in FPV for 5 minutes. No issues. Actually, much better altitude handling as it doesn't drop as much under acceleration.

**Comment by mlyle** [comment]
@cpusmith--- thanks so much for testing, it's a big help.

**Comment by cpusmith** [comment]
@mlyle Enjoyed it. I have Sparky 1.1 on a 250 and a 330 and a Sparky 2 on a 450. I'll run Jenkins last on the 450 and one of the latest Next on the others so let me know if there's anything else that needs testing.

**Pull request merged**
