### PR TITLE
GCS: Fail unit tests if plugins failed to load

### PR DESCRIPTION
**Pull request by tracernz**
Good for things like #2166 (although we don't currently run regular CI tests on Windows).

### CODE REVIEW

**Comment by tracernz** [comment]
Note: should fail currently as the fix for above issue hasn't merged... let's check:
build artifacts please

**Comment by tracernz** [comment]
Ahhh. Of course we don't build GCS tests on the release builder. Not sure this will be as useful as I had hoped but at least it will catch mac (and general *nix) loading issues.

**Comment by tracernz** [comment]
(Note the fail here was unrelated/due to flight test)

**Comment by mlyle** [comment]
Wow, that one on flight test looks like it actually *did* get stuck somehow.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Sucks that the error strings here didn't tell us of the true problem (though wine -did-).

Just an aside: I think on MacOS and Linux, we had libuploader in the search path and loading a plugin that depended upon it loaded the library... but didn't init the plugin.  This is bad because we could have called into the plugin before the plugin init code had all run.  Whereas on Windows it wasn't able to load it at all.  (So we shouldn't "fix" the load path issue).

**Pull request merged**
