### PR TITLE
GCS Usage Stats: Notify user, save config

### LINKED ISSUE #470: Add opt-in for usage statistic and sharing of private data
The GCS currently silently publishes usage statistics, including private information like the IP address and flight controller serial number. IMO, this is not acceptable and we should require users to opt-in. The easiest solution would be to add a pop-up dialog asking users for permission with check boxes defaulting to true.

### PR DESCRIPTION
**Pull request by mluessi**
Tested on Linux. 

Fixes #470

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/475)

### CODE REVIEW

**Comment by PTDreamer** [comment]
Can you explain the content of the PR? I don't understand the relation of the import settings dialog to the usage stats plugin nor the changes to the later.

**Comment by mluessi** [comment]
@PTDreamer currently, the usage stats settings don't get saved. I'm not sure if I did it the correct way; I basically copied what the notify plugin is doing. The other addition is adding a notification to the dialog that pops up when first creating the settings, it informs users that the gcs is sending stats to the maintainers.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by PTDreamer** [comment]
> @PTDreamer currently, the usage stats settings don't get saved. I'm not sure if I did it the correct way; I basically copied what the notify plugin is doing. The other addition is adding a notification to the dialog that pops up when first creating the settings, it informs users that the gcs is sending stats to the maintainers.

So that means that only the users which have never installed the dRonin GCS will see warning right?

**Comment by mlyle** [comment]
> So that means that only the users which have never installed the dRonin GCS will see warning right?

Yes.  Hopefully the people who installed preview 3 saw the relnote.

**Comment by mlyle** [comment]
Close on OSX:
image

Resizing it makes all the text appear.

**Comment by mlyle** [comment]
Confirmed that saving the settings is persisted.

**Comment by mlyle** [comment]
image

is it working when taller.

It's 25 pixels taller, and that's enough that the other elements start to spread out a little.  So recommend increasing y size of dialog by 25px.

**Comment by mluessi** [comment]
Done, made the dialog 230px tall (was 204).

**Comment by mlyle** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/d-ronin/dronin/475#-:-K8Qjd-IlmVWjB-VJvk8:1417088721)*

**Pull request merged**
