### PR TITLE
gcs: revolution: boardplugin-- put back to how it was

### PR DESCRIPTION
**Pull request by mlyle**
Before #617.

Connects to #817.

Connects to #716.

### CODE REVIEW

**Comment by tracernz** [comment]
getInputType should only check things that are set by setInputType, otherwise the wiring diagram could be wrong. Also need to check that the wiring diagram is actually correct, particularly for S.BUS. It may be a good idea to just separate the CC3D and Revo connection diagrams to avoid icky workarounds if they're different.

**Comment by mlyle** [comment]
@tracernz Are you sure?

If someone has DSM set on a (non-standard) port already, and they pick DSM again, I don't think it should think the existing configuration is not DSM and switch the ports on them (even if the wiring diagram is wrong in that case).

**Comment by mlyle** [comment]
Also if we do it just like that, and someone picks DSM,... in the case where we would have shown a bad wiring diagram before, we'd now configure DSM to an additional port and make it not work at all, which doesn't seem good.

**Comment by mlyle** [comment]
From applyHardwareConfiguration in VehicleConfigurationHelper https://github.com/d-ronin/dRonin/blob/next/ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp#L127

```
    Core::IBoardType::InputType newType = m_configSource->getInputType();
    bool success = boardPlugin->setInputType(newType);
```

It looks like right now we'll happily create duplicate settings in these circumstances, etc.

I think we should suppress setting it if it's the same setting we currently have (though there are some risks there-- we preserve the user's configuration but do not necessarily have the right wiring diagram).

**Comment by tracernz** [comment]
Setup wizard, wiring diagram etc. don't support any configuration other than that set by the setup wizard. There code would all need to be extended to support anything else.

**Comment by tracernz** [comment]
For this release I think we should just fix what's there (make getInputType inverse of setInputType) since that's the way it's always supposed to have been. For next release we should look at overhauling the setup wizard and diagram functionality. I'd like the diagram to be more general and available somewhere other than setup wizard.

**Comment by mlyle** [comment]
@tracernz, if getinputtype is the inverse of setinputtype, I don't think it will handle any situation better.  I may not be understanding.

It seems like this is how it works:
1. If the thing is on the "correct" port-- e.g. if someone picks "DSM", and flexi is already configured to DSM--- the current code and what you want is the same.
2. If the thing is not on any port-- the current code and what you want is the same-- it will configure it and tell the user to reboot.
3. a. If the thing is on the "wrong" port-- if someone picks "DSM", and mainport is configured to "DSM."-- both your proposed and old code will end up configuring flexiport to DSM and leaving the main port as DSM (nonfunctional config).   Current code in this PR will not tell the user to reboot, your proposed code will tell the user to reboot.

b. If I add a line to the above based on original config, it will leave mainport configured to DSM and not touch flexiport, and not tell the user to reboot.  If the user looks at the wiring diagram, it will be wrong for mainport DSM.

c. Alternatively, I could change the code to de-configure RX protocols before setting the configured type.   It would work right, but would silently move mainport to flexiport.

**Comment by tracernz** [comment]
None are particularly appealing but that has been the situation longer than you or I have been involved ;-). I have some ideas to make this a lot better which have been sitting in my head for a while, will discuss with you this evening and maybe get working on it.

**Comment by tracernz** [comment]
Let's just do this for now.

**Pull request merged**
