### PR TITLE
GCS: Roll Qt to 5.9.2 (LTS)

### LINKED ISSUE #1951: GCS: Crash on mac when using a proxy server (pac only I think)
* Seen in version (release version or githash): Release-20170717 (neat)

Issue details:
Upstream Qt bug can cause a crash when attempting to obtain the system proxy settings. Looks like it's fixed in Qt 5.9 (https://github.com/qt/qtbase/commit/20f7cfcbdab795b1730e3d1d14fc3833a7f5e705).

See https://forum.dronin.org/forum/d/393-dronin-neat-release-2017-07-17/26 for original report by user geoffmunn and https://gist.github.com/tracernz/41d37fd1461606fc78234ca43187fa40 for the stack trace. Thanks Geoff! :+1:

### PR DESCRIPTION
**Pull request by tracernz**
Plus required changes. Good on Linux, not tested yet on macOS/Windows.

TODO:
- [x] Test macOS
- [ ] Test Windows
- [x] Check Qt install script.. it needs additional packages selected I think

Fixes #1951

### CODE REVIEW

**Comment by mlyle** [comment]
Fuck yah.  OK, let's try Linux first.

**Comment by mlyle** [comment]
jenkins, test this please

**Review by mlyle — APPROVED** [review]
Code changes look good to me... I will need a couple-few days to stage tests and things before merge.

**Comment by mlyle** [comment]
Uh installer doesn't really install anything except Creator by default wtf? :p   

jenkins, test this please

**Comment by tracernz** [comment]
Yeah, I'll fix the installer script. 😉

**Comment by tracernz** [comment]
Automatic install script updated (and re-instated as I had removed it in this patch set temporarily), selects correct packages. ;)

**Comment by tracernz** [comment]
Just need to check Windows now.

**Comment by mlyle** [comment]
Not installed on Windows Ci yet, just added to mac, for tryin' now:

jenkins, build artifacts please

**Comment by mlyle** [comment]
Passed on OSX.

Tomorrow is a busy day for me, but Weds I will work on getting this merged for real.

**Comment by tracernz** [comment]
Haven't done a Qt 5.9 build on Windows at all to date. One thing I might do for Windows is set `C:\Qt` rather than `QT_SDK_PATH` in https://github.com/d-ronin/dRonin/pull/1966/commits/dba9369175bf0cd2e5698fd5d4bbe558cf49befe#diff-d848f181cd782d5d32ac4749ce706bf1R178 so the qt_sdk_install target can work in an existing setup.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
About to merge-- but any and all regressions here are my fault, since I'm merging it before @tracernz is ready and would prefer.

**Comment by tracernz** [comment]
Thanks for merge! I'll follow up with another PR to tidy up some nits. :+1:

**Pull request merged**
