### PR TITLE
attitudesettings: listen to accels slightly less

### PR DESCRIPTION
**Pull request by mlyle**
Was 0.5, now 0.33; so lop a third of it off.  It won't entirely fix
attitude biasing when pulling G's, but it will make it a little better.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
I'm not sure it's a good idea to mess with this so late. It affects more than just the horizon on the OSD.

**Comment by mlyle** [comment]
Yup.  Let's see if anyone has anything great to say about it.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
One flight test from Malcurin- feedback was it was same or slightly worse for attitude biasing in leveling modes.

**Comment by mlyle** [comment]
abandon, rebase too hard for what this is.

**Pull request closed without merging**
