### PR TITLE
Rename sim to flightd

### PR DESCRIPTION
**Pull request by mlyle**
Sim has not been an accurate name for some time.  In preparation for further packaging work, put this right.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
Ahhh, conflict. :( No comments on this after a few days so once rebased LGTM. 👍

**Review by tracernz — APPROVED** [review]

**Comment by mlyle** [comment]
rebased, sane this time.

jenkins, build artifacts please

**Pull request merged**
