### PR TITLE
gcs: some compilers don't know num_motors is always inited

### PR DESCRIPTION
**Pull request by mlyle**
This change is [Reviewable](https://reviewable.io/reviews/d-ronin/dronin/808)

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
```
compiling /var/lib/jenkins/jobs/dronin/workspace/Nodes/master/ground/gcs/src/plugins/config/vehicletrim.cpp
moc /var/lib/jenkins/jobs/dronin/workspace/Nodes/master/ground/gcs/src/plugins/config/configvehicletypewidget.h
/var/lib/jenkins/jobs/dronin/workspace/Nodes/master/ground/gcs/src/plugins/config/cfg_vehicletypes/configmultirotorwidget.cpp: In member function ‘virtual void ConfigMultiRotorWidget::setupUI(SystemSettings::AirframeTypeOptions)’:
/var/lib/jenkins/jobs/dronin/workspace/Nodes/master/ground/gcs/src/plugins/config/cfg_vehicletypes/configmultirotorwidget.cpp:209:5: error: ‘numMotors’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     for (int i = labels.length() + 1; i <= numMotors; i++)
     ^
compiling .moc/release-shared/moc_configccpmwidget.cpp
cc1plus: all warnings being treated as errors
moc /var/lib/jenkins/jobs/dronin/workspace/Nodes/master/ground/gcs/src/plugins/config/cfg_vehicletypes/configfixedwingwidget.h
```

**Comment by mlyle** [comment]
Self-merging because critical

**Comment by tracernz** [comment]
I guess the compiler can't see that Q_ASSERT will trigger SIGABRT in the default case. Probably should just remove the default case since a compile failure is better than a runtime one when an airframe type isn't handled.

**Pull request merged**
