### PR TITLE
Attitude improvements

### PR DESCRIPTION
**Pull request by mlyle**
Connects to #863.

* Calculate in a way that behaves the same no matter the sampling rate.
* Similarly, filter acceleration data in a sample-rate invariant way
* Adjust the default values to be a "compromise value" that behaves
something between how F1 and F3 do it currently.
* Rename accelkp/accelki to acckp/accki, and magkp/magki to mgkp/mgki
because the values have changed.

This is not sufficient to be without anomaly, but a good starting point of discussion.  Unclear if this should make it into Artifice.

### CODE REVIEW

**Comment by mlyle** [comment]
So basically, this seems to do slightly better in tests of "hold by usb cord and flop around maniacally, then set down flat on desk and watch attitude".

**Comment by ufoDziner** [comment]
Jenkins build artifacts please.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by ufoDziner** [comment]
Not sure what happened, but my seppuku will not save any settings.  First artifacts appeared to work, but I didn't review them before the second set was built.  Installed second set, upgraded, and now settings won't save.  It appears that they import, but just won't save.  Tested with the first build again, and it won't save them either.  Suggestions?

**Comment by mlyle** [comment]
Are you using the upgrade routine in GCS or upgrading by hand and importing?

It's possible your settings flash is full of obsolete UAVOs-- the upgrader erases the settings partition to deal with this.

Try right-clicking on settings and picking 'erase'.

**Comment by mlyle** [comment]
The settings partition in the browser on the firmware pane, that is.

**Comment by ufoDziner** [comment]
I ran the GCS update.  My settings were definitely old.

I entered the bootloader, right clicked on settings then "erase".  Even after that, I cannot save any changes.  Just trying to add the receiver protocol I get the red X on the save button after a save attempt, and then my setting is gone upon reboot.  I do have an unusual error for me, "There were problems with the UAVObject events or callbacks".

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by ufoDziner** [comment]
Flight test footage.  https://youtu.be/_V9RSP92Wv0

**Comment by glowtape** [comment]
I flew around a bit in my backyard.

Before when doing FFF and "fast curved flight" (FCF :D ), the AH would slide off screen and then took a few seconds to get back when coasting. Going into FFF and make it go offscreen, then enter a fast curve or some other manoeuver often ended up in the AH suddenly coming in from the side at a large angle to the real horizon, just to slide offscreen again, when you change direction, in a way unrelated to the actual flying. Essentially, it was pretty useless in acro flight.

Now, the artificial horizon doesn't veer off much from the position you'd actually expect it to be. In FFF or FCF, it picks up the expected bias, but once you start coasting, the artificial horizon line snaps back to the real one pretty fast. Queueing a bunch of different manoeuvers other than FFF/FCF doesn't upset it much either (before the AH went AWOL).

I had the camera angle set up and by chance the AH movement seemed to fit the FOV of my DALRC 2.5mm well enough (I picked up in IRC yesterday that FOV could be calibrated for, but didn't really spot anything regarding it in the OSD code, tho).

This fix should help newbies learning acro, too. Back when I did it, attitude mode was a failsafe to rescue the quad. Obviously that didn't always go well, when the computed attitude was completely off.

**Comment by mlyle** [comment]
@glowtape ArtificialHorizonMaxPitch should be set to half the VFOV of the camera.  VFOV is 60% of DFOV in 3:4 video, so 30% of the diagonal FOV is about correct -- so the default config of 30 is about right for a 100 degree fov camera.

The way I do it is experimentally.  I point the quad at a distant horizon-- perhaps my desk 20 feet away.  then i pitch up and down until the horizon and the desk move up and down in the video at very close to the same rate.

**Pull request merged**
