### PR TITLE
pios_servo: factor common between f1/f3/f4

### LINKED ISSUE #368: pios_servo should be refactored common between F1/F3/F4
@droidicus, you'd started on this-- ideally pios_servo would move to Common/ with a few ifdefs about what prescaler arrangements we use.  Are you willing to pick this up for the release after Renatus?

### PR DESCRIPTION
**Pull request by mlyle**
fixes #368 

Untested, but it compiles, so it's perfect.

Needs careful test across multiple timers F1/F3/F4
- [x] test on F1
- [x] test on F3
- [x] test on F4

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/620)

### CODE REVIEW

**Comment by droidicus** [comment]
Tested next + #620 + #569 on a sparky2 150mm quad with 1104s, oneshot on outputs 1-4, in both leveling and altitudehold. Flew well, no issues noted.

**Comment by mlyle** [comment]
Flown on Brain, on 150 quad.  Happy.

Flown on sparky2, on 500 quad.  Happy.

**Comment by mluessi** [comment]
Very nice :)

**Comment by mluessi** [comment]
Code looks correct (compared it to existing code for F0/F1/F3/F4)

**Comment by pug398** [comment]
Flight test on F1/F3 still needed?

**Comment by mlyle** [comment]
Ideally yes.

**Comment by pug398** [comment]
jenkins, build artifacts please

**Comment by pug398** [comment]
Don't see any issues with flight on 280 CC3D quad with Oneshot and 250 Sparky1 quad
with 400hz SK.

**Comment by mluessi** [comment]
Thanks for the test @pug398 !

**Pull request merged**
