### PR TITLE
uavobjectmanager: correct some bugs

### PR DESCRIPTION
**Pull request by mlyle**
- Reentrancy requires things that can change under the course of a loop
  to be volatile
- The logic to check num_pending before checking for a duplicate event
  type is obsoleted

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/248)

### CODE REVIEW

**Comment by mlyle** [comment]
could relate to #227

**Comment by jhitesma** [comment]
So I'm no longer reproducing #227 with this.  But @tracernz said he was still repoing it.

**Comment by mlyle** [comment]
@jihlein if you can easily try this i'd really appreciate it.

**Comment by mlyle** [comment]
Nevermind.  Problem came back for @jhitesma

**Comment by jihlein** [comment]
Was going to try anyway, but after rebasing to the current next, my build environment is no longer working.  I can't build a working GCS in the Windows environment.

**Comment by mlyle** [comment]
What error do you get?  

There's two things I can think of in recent changes that are relevant:

* The build environment only looks inside tools/ for arm compilers and no longer searches for system installations.
* The build environment doesn't look on its own for a QT install, expecting you to be running from an environment with Qt already in the path-- as described here -- https://github.com/d-ronin/dRonin/wiki/Development-Windows-setup :

```
Start a shell using the "Git bash" program shortcut in the right-click context menu.

... 

Type this command to install a bash_profile suitable for developing the project: cp dronin/make/winx86/bash_profile ~/.bash_profile. Next, ensure that the bash_profile is executable by typing chmod 755 ~/.bash_profile . You may have to edit bash_profile if you have changed any installation paths from the default. Then exit from the terminal and start a new "Git bash" instance.
```

The old way of sh.cmd is deprecated because it resulted in a lot of drift between everyones' build environments that sometimes caused problems, this is easier to set up for new users, and it gives a real terminal.

**Comment by mlyle** [comment]
P.S. Sorry this broke-- I'm coalescing a lot of things and a lot of legacy from the build instructions.

**Comment by jihlein** [comment]
Okay, I can build again, but either due to problems with the environment, or this patch, things are not working.

First, the even system WCA box, while normally green, occasionally flashes yellow.  Second, I the boxes for configuration wizard and manual calibration are greyed out so there is no way to attempt calibration of the PPM receiver.  I'm going to back out this patch as see where that leads.

**Comment by mlyle** [comment]
Really strange.  Others have experienced this not fixing anything, but not helping anything (except @jhitesma got through the wizard with this once).

I will have PPM receivers in hand Tues (want to avoid dismantling the couple things I have PPM on for testing).

**Comment by jihlein** [comment]
This GCS build is a little odd too.  The map display initially comes up, but after halting-flashing-booting the target, the map is blank and won't recover without a GCS restart.  The GCS also take a long time to establish communication with the target.  Files with a .bin extension have a black icon when viewed thru GCS windows.

After reverting the patch, the GCS connects and generally responds better, and the input calibration icons are active.  All other issues remain.  I'm going to delete my build folder and rebuild the whole thing to see if that changes anything.

**Comment by jihlein** [comment]
Rebuilt after deleting build folder.  Still getting solid black icons for bin files, but map display seems stable.  Implemented this patch, reloaded on AQ32, and was able to complete PPM Rx setup wizard.  Flight software seems stable, but I still get the feeling the GCS is not quite right.  Applying and saving settings, on many of the pages, results in a red circle with an X in it, but the changed objects have saved correctly.  Will reset board to default settings and try complete setup from scratch tomorrow.

**Comment by mlyle** [comment]
Doesn't fix key bug, and I think this should get cleaned up in various ways.  I'd still like this change eventually, but marked WIP, moved post-renatus.

**Comment by mlyle** [comment]
I read this again,  Further reflection makes me think this is a bad idea.  withdrawing.

**Pull request closed without merging**
