### PR TITLE
actuator: fix channel passthrough

### LINKED ISSUE #1693: After upgrade from quixote to current next tx passthrough not working
* Seen in version (release version or githash): 0f0f1ee6 20170404

* On flight controller (if applicable): Quanton

Issue details: Tx passthrough not working after upgrade from Quixote. Accessory0 is assigned to sbus channel6 and is working range 172uS - 1811uS. Output7 is set to 1000uS - 2000uS and correctly works gimbal when slider is moved in output test. In mixersettings mixer7 is set to accessory0. This setup was working before upgrade. Have not erased and done a complete redo yet.

### PR DESCRIPTION
**Pull request by mlyle**
fixes #1693

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
@pug398 -- does this fix things?

This is just an interim thing, because the mechanism by which passthrough happens is going to change.  Thx for report.

**Comment by pug398** [comment]
@mlyle that fixed it :)
I am able to control output7 directly from the tx now. In my case that is gimbal pitch control.

**Comment by mlyle** [comment]
Cool.  Was my screwup :)   Thanks for spotting it.

**Review by tracernz — APPROVED** [review]
Thanks, also my bad for not spotting it in review. :+1:

**Comment by mlyle** [comment]
@tracernz you spot a reasonable fraction-- 60-70% -- of these things, which is a very high fraction to kill through casual code review.  I know for sure I'm nowhere near that high.

**Pull request merged**
