### PR TITLE
dtfc/lux: move to normal attitude module

### PR DESCRIPTION
**Pull request by mlyle**
This deprecates / kills off the old F1 accel/mag-only attitude module.

Depends on #1608 because it removes the module and F1 requires the attitude acro module.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
Awaiting a flight test.

**Comment by mlyle** [comment]
Flew on Lux.

There was some forward bias of attitude-- 2-3 degrees-- perhaps vibration related or because of frame warp on the Delrin frame.  Don't see how it could relate to this change.

Down to 9.3k of heap on my config with Autotune enabled.  So do not require decimation yet.  (Not sure why PikoBLX was closer to the edge-- need to try that myself...)

**Comment by mlyle** [comment]
Flew #1618, #1610, #1599... plus a change to decimate = 2 on Lux.  Set to 88Hz second order filter.  Did an autotune.  

Requires disabling the lowpass filter in the autotune script (for filtering change), but the results are good:

bokeh_plot 25
 
http://dronin.org/tunes#?key=ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICA0OCU3AgM

**Pull request merged**
