### PR TITLE
GCS: Only run qmake if pro/pri files change

### PR DESCRIPTION
**Pull request by tracernz**
Saves lots of time on incremental builds.

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
This might just be too naive. We might do too many things with files outside the ground tree I think.

**Comment by mlyle** [comment]
Incremental of GCS, no changes: `real	0m4.932s`
Incremental of GCS, after `touch`ing a UAVO: `real	0m20.679s`

**Review by mlyle — APPROVED** [review]

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Merge pretty please... this will make me much happier to work on UI :P

**Comment by tracernz** [comment]
Looks good. Let's see how it goes for a while. :grin:

**Pull request merged**
