### PR TITLE
Sparky2: Fix ADC config

### PR DESCRIPTION
**Pull request by tracernz**
ADC channels swapped. Checked against schematic, gerber, and tested.

@henn1001 The labels weren't wrong, just the channels. ;)

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/572)

### CODE REVIEW

**Comment by henn1001** [comment]
You sure? GPIO seems to be still messed up.

unbenannt

**Comment by henn1001** [comment]
I think the peripheral / timer was correct.. just the volt/current assignment was switched.
unbenannt

By the way - are we allowed to correct the schematics with photoshop-fu? :d Really confusing

**Comment by tracernz** [comment]
Ahhh, let me double check :P

**Comment by tracernz** [comment]
Ahh, the GPIOs are incorrect still, I shall fix. Everything else, including the schematic, is correct.
capture
(leftmost column is pin number for LQFP64)
capture2
capture3

**Comment by tracernz** [comment]
Note that fixing the GPIOs will have no functional impact since we always init both pins as ADC AF anyway.

**Comment by tracernz** [comment]
Fixed and force-pushed.

**Pull request merged**
