### PR TITLE
Flight: Fix broken Frsky Sport Telem on Next.

### LINKED ISSUE #679: FrSky S.Port Telemetry broken on next
FrSky S.Port Telemetry is broken on next with the following configuration:
Brain FC
FlxPort - S.Port telemetry
MainPort - S.Bus serial
RXPort - disabled

@jihlein it looks like this problem is corrected by reverting #403, not sure why

### PR DESCRIPTION
**Pull request by jihlein**
This PR corrects the conflict between PR #403 and PR #672, addressing Issue #679.

Can somebody with Frsky Sport telem and F4 test this?

[Review on Reviewable](https://reviewable.io/reviews/d-ronin/dronin/700)

mpl edit: fixes #679 (for linkage)

### CODE REVIEW

**Comment by pug398** [comment]
jenkins, build artifacts please

**Comment by pug398** [comment]
I think @droidicus may have to check this. Inverter board has that smell so I think I may have let invisible magic smoke out. I cannot even get the old setup to work now so something is wrong on my end :/

**Comment by ekaszubski** [comment]
I can test this on my sparky2 + custom inverter board. I just flew on 9ed2022ef9dd6f69cb2974702d43d514f962783c which was right before #403 was merged so luckily I avoided any of these issues.

**Comment by ekaszubski** [comment]
@pug398 @jihlein I can confirm S.Port telemetry works on sparky2 + custom inverter board + X6R/D16 with this PR as of f0de00ca7faaf946d656786aab719191094e0532.

**Comment by jihlein** [comment]
@ekaszubski, thanks for testing!

@pug398, if you can confirm Sparky still works, this PR should be okay.

**Comment by pug398** [comment]
Confirmed working on Sparky1 and Quanton as well.

**Comment by mlyle** [comment]
Nice!

**Comment by jihlein** [comment]
Cool, thanks for testing!

**Pull request merged**
