### PR TITLE
GCS:CrashReporter: Send Jenkins build info

### PR DESCRIPTION
**Pull request by tracernz**
So we can differentiate people's own builds from official ones, and additionally we can get the source artifacts for the exact build if we see something fishy. The env. vars come from Jenkins (https://wiki.jenkins.io/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-belowJenkinsSetEnvironmentVariables).

### CODE REVIEW

**Comment by tracernz** [comment]
build artifacts please

**Comment by tracernz** [comment]
test this please

**Comment by tracernz** [comment]
build artifacts please

**Comment by tracernz** [comment]
Works great on:
[Linux](http://dronin-autotown.appspot.com/api/crash/ahFzfmRyb25pbi1hdXRvdG93bnIWCxIJQ3Jhc2hEYXRhGICAgOjVv94JDA)
[macOS](http://dronin-autotown.appspot.com/api/crash/ahFzfmRyb25pbi1hdXRvdG93bnIWCxIJQ3Jhc2hEYXRhGICAgOiHxsYJDA)
Windows 10 "protects me" by preventing the crash reporter app from running. I think at this point I am ready to give up on supporting such a steaming pile of garbage. 😞 -e- And editing some settings + clicking through some scary warnings... then trying a few times, not changing anything... and then suddenly it started working for no apparent reason a few minutes later, reinforcing my earlier point, so [Windows](http://dronin-autotown.appspot.com/api/crash/ahFzfmRyb25pbi1hdXRvdG93bnIWCxIJQ3Jhc2hEYXRhGICAgOjRleULDA)

**Comment by mlyle** [comment]
Fine, I'll merge this, though i'm scurred.

**Comment by tracernz** [comment]
Thanks! 😀

**Pull request merged**
