### PR TITLE
GCS:Plugins: Untangle dependencies, only link required deps

### PR DESCRIPTION
**Pull request by tracernz**
Remove the practice of adding link flags in pri files that are included by other plugins (so they don't needlessly link things), and remove the practice of polluting INCLUDEPATH in a lot of pri files. Totally removed all *_dependencies.pri files which seemed to encourage the two former practices. I found once I did this that _many_ plugins were missing dependencies, so added all required to get a successful build.
Also remove two unused/unmaintained/uncompiled plugins (rather than fix them).

Needs tested on macOS and Windows.

Should help a lot with things like #1847, and I'm interested to see if it has any other effect on Windows in particular.

### CODE REVIEW

**Comment by tracernz** [comment]
jenkins, build artifacts please

**Comment by tracernz** [comment]
I should make sure plugins.pro reflects the same deps, and perhaps also see if any are not actually required.

**Comment by mlyle** [comment]
Portable and installer version work great on my Windows machine.

**Comment by mlyle** [comment]
Got this on OSX:
```
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtGui.framework/Versions/5/QtGui
  Referenced from: /Applications/dRonin GCS.app/Contents/MacOS/dRonin-GCS
  Reason: image not found

Binary Images:
       0x1040cb000 -        0x1040f3ff7 +org.dronin.gcs (1.3.1 - 1.3.1) <9B1C9E0A-63FA-3C6D-91AF-804830D7D93E> /Applications/dRonin GCS.app/Contents/MacOS/dRonin-GCS
       0x104109000 -        0x104127ff7 +libUtils.1.dylib (0) <B41A443A-125D-3869-B21E-FCD7955D9596> /Applications/dRonin GCS.app/Contents/Plugins/libUtils.1.dylib
       0x111c2d000 -        0x111c6adc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
```

Going to try last night's nightly.

**Comment by mlyle** [comment]
Argh, same issue on last night's nightly.

**Comment by tracernz** [comment]
Yeah, that's def. not from this.

**Comment by mlyle** [comment]
jenkins, build artifacts please

**Comment by mlyle** [comment]
Works great on OSX after "fix"

**Review by mlyle — APPROVED** [review]
Changes confined to build system, removal of a couple plugins, and changes to include paths.  Looks great.

**Comment by RossMay** [comment]
http://i.imgur.com/RaW2hEA.png
https://pastebin.com/gkpbYraF

On Windows

**Comment by mlyle** [comment]
@rossmay that's #1857 not this #1852.

**Pull request merged**
