### PR TITLE
rfm22b: Allow selection of hardware band.

### PR DESCRIPTION
**Pull request by mlyle**
For both Tau-style telemetry and OpenLRS.  Initial frequencies chosen
for Tau-style telemetry on 868 and 915 bands.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
This has sat around for a long time, we should probably just merge it since it looks fine.

**Comment by mluessi** [comment]
LGTM as well. Merging.

**Comment by mlyle** [comment]
@tracernz just tested this and confirmed it to work on 915MHz.

**Pull request merged**
