### PR TITLE
Add release announcements to welcome plugin

### LINKED ISSUE #974: Feature: Check from GCS for new release, and offer to download/update automatically
Could help getting users to the latest release.

### PR DESCRIPTION
**Pull request by mlyle**
Fixes #974

How it works:

We download a file from `http://dronin.org/relAnnounce/<<githash>>.json`

If it exists, and looks like:

```
{ 
"thresh" : 700, 
"text" : "<h1><font color=\"red\">Oh Shit</font></h1><p>Better upgrade now.  Get it <a href=\"http://dronin.org\">here</a>.  Fast.</p><p>A <font color=\"red\">CRITICAL</font> bug has been found that will make your quadcopter catch fire.</p>"
}
```

We compare thresh to a hash of our usage info.  Basically, thresh is the per-1000 number of users that should be notified (e.g. if it's 500, half of users will receive the announcement).  This can be used to slowly roll out upgrades.

If the threshold is met, something like this happens:

ohshit

Confirmed that links, etc, work.

### CODE REVIEW

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
Looks good. :+1:

**Comment by ufoDziner** [comment]
Seems better to refrain from using profanity if possible.  Maybe "Oh No!", "Whoa Nelly!", or my fave "Yipes!!!"

**Comment by mlyle** [comment]
Probably won't use that for a real release announcement ;)

**Pull request merged**
