### PR TITLE
Singleinstancegcs

### PR DESCRIPTION
**Pull request by PTDreamer**
Solves #1371 
If more then one instance is run it raises the first instance and exits silently.

### CODE REVIEW

**Comment by mlyle** [comment]
Nice :D

**Review by tracernz — APPROVED** [review]
Looks good, haven't tested. :+1: Sorry about slowness.

**Comment by mlyle** [comment]
Very nice on Linux and Windows :D  Will merge to pick up any other problems in mainline testing.

**Comment by tracernz** [comment]
Last couple of nightlies failed:

```
link /NOLOGO /DYNAMICBASE /NXCOMPAT /STACK:8388608 /DEBUG /OPT:REF /INCREMENTAL:NO /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:..\..\bin\drgcs.exe @C:\Users\build\AppData\Local\Temp\drgcs.exe.4440.3922.jom
singleapplication.obj : error LNK2019: unresolved external symbol __imp__GetUserNameW@8 referenced in function "public: void __thiscall SingleApplicationPrivate::genBlockServerName(int)" (?genBlockServerName@SingleApplicationPrivate@@QAEXH@Z)
..\..\bin\drgcs.exe : fatal error LNK1120: 1 unresolved externals
```

**Pull request merged**
