### PR TITLE
small SAFETY fixes to tx_control.

### PR DESCRIPTION
**Pull request by mlyle**

### CODE REVIEW

**Comment by mlyle** [comment]
Before, unchecking "take control" from GCS receiver (which resulted in invalid settings would leave the aircraft HALF disarmed.  UAVOs disarmed (flightstatus), blinking disarmed, etc.  But if control became valid again it would be immediately armed.  Fixed with this change.

**Comment by mlyle** [comment]
jenkins, test this please

**Comment by tracernz** [comment]
So you can still hand-over between GCS control and tx control without disarming?

**Comment by mlyle** [comment]
Yes-- if it's valid.  The issue here was if you trigger the "invalid rx" check-- from the wrong return code from the driver or whatever-- it's supposed to immediately disarm.  But it only ... kind-of disarmed.  Motors would stop, etc, but if the rx became valid again it would be immediately armed.

**Comment by tracernz** [comment]
Let's rewrite this whole mess next release like we discussed.

**Pull request merged**
