### PR TITLE
sanitycheck: Add Throttle configuration alarm, when collective is configured for multirotor.

### PR DESCRIPTION
**Pull request by glowtape**
Generates a configuration warning, if collective is configured on a multirotor. Over in #2101 it is mentioned that collective on a multirotor is a rare but possible configuration, so the CFG:THROTTLE OSD error might be a little unfortunate for OSD targets, but how common is that?

### CODE REVIEW

**Review by mlyle — APPROVED** [review]

**Comment by tracernz** [comment]
It's rather unfortunate to have an unmaskable warning on valid configurations. :/ 

-e- Wide variety of vehicle configurations is one of our strengths compared to other firmwares and I'd hate to see that go away.

**Comment by glowtape** [comment]
We could add a checkbox to the Input page, that only shows on a multirotor+collective configuration, labelled ~~"I better not be an idiot by declaring a collective control on a multirotor"~~ "Collective on multirotor intentional", and automatically clears the collective when saving with this unchecked.

**Comment by glowtape** [comment]
Or just a mere GCS side warning in the UI in that specific combo.

**Comment by mlyle** [comment]
Yah I was thinking a GCS side warning, turning collective yellow, but it's tricky how the input form is made.

**Comment by mlyle** [comment]
Thx, but superseded #2208

**Pull request closed without merging**
