### PR TITLE
pios_spi: eliminate interrupt

### PR DESCRIPTION
**Pull request by mlyle**
At best, it's useless/unused.. at worst, it busy-waits in an interrupt!

### CODE REVIEW

**Comment by jihlein** [comment]
Just did a short 3 minute flight in the backyard with this change on DTFC.  Seemed to work just fine, no odd behavior noted.  Hope to get to AQ32 later this evening.

**Comment by tracernz** [comment]
This looks okay, but I haven't tested it on hardware.

**Comment by jihlein** [comment]
Just verified this works on AQ32 with a short flight.  That covers an F3 and F4 target.

**Comment by tracernz** [comment]
Needs CC3D test IMO, don't want to get bitten by that again.

**Comment by jihlein** [comment]
Agreed, but can't help you there......

**Comment by tracernz** [comment]
I'll get it this evening, thanks for your help. :-)

**Comment by mlyle** [comment]
Bench tested #1186 + #1188 + #1195 on CC3D -- artificial horizon, saving / loading settings, etc.  All looks good.

**Pull request merged**
